Repository sonata-project/SonataAdminBundle, pull requests merged in 2018-12, with the labels that each got.

#5323 Implement getExtendedTypes
  src/Form/Extension/ChoiceTypeExtension.php
  src/Form/Extension/Field/Type/FormTypeFieldExtension.php
  src/Form/Extension/Field/Type/MopaCompatibilityTypeFieldExtension.php
  tests/Form/Extension/ChoiceTypeExtensionTest.php
  tests/Form/Extension/Field/Type/FormTypeFieldExtensionTest.php
Labels: critical, pedantic

#5322 Move commented method at the bottom of the class
  src/Admin/AdminInterface.php
Labels: patch

#5334 Remove "e" letter after delete checkbox in SonataAdmin/Collection tab…
  src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig
Labels: pedantic

#5335 Add ability to specify batch action confirmation template per action
  docs/reference/batch_actions.rst
  src/Controller/CRUDController.php
  tests/Controller/CRUDControllerTest.php
Labels: minor

#5345 Check "create" route existence in ModelAutocompleteType form field
  src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
Labels: patch

#5349 Improve css for single column dropdowns
  src/Resources/public/css/styles.css
Labels: patch

#5372 use ~ instead of null
  docs/cookbook/recipe_custom_action.rst
  docs/cookbook/recipe_custom_view.rst
  docs/cookbook/recipe_persisting_filters.rst
Labels: docs, pedantic

#5378 [Docs] fix file paths
  docs/cookbook/recipe_workflow_integration.rst
Labels: docs

#5365 [Docs] Update about customizing mosaic list
  docs/cookbook/recipe_customizing_a_mosaic_list.rst
Labels: docs

#5370 [Docs] be less verbose
  docs/cookbook/recipe_creating_an_admin_with_annotations.rst
Labels: docs

#5355 Remove assert against Form in CRUDController
  src/Admin/AdminInterface.php
  src/Controller/CRUDController.php
Labels: patch

#5373 [Docs] fixed order
  docs/cookbook/recipe_improve_performance_large_datasets.rst
  docs/cookbook/recipe_persisting_filters.rst
  docs/cookbook/recipe_sortable_listing.rst
  docs/reference/advanced_configuration.rst
  docs/reference/architecture.rst
  docs/reference/dashboard.rst
  docs/reference/form_types.rst
  docs/reference/routing.rst
  docs/reference/templates.rst
Labels: docs

#5380 Allow configuring default options for admin service
  docs/reference/configuration.rst
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataAdminExtension.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/SonataAdminExtensionTest.php
Labels: minor

#5377 [Docs] removed public: true for admin classes
  docs/cookbook/recipe_custom_action.rst
  docs/cookbook/recipe_custom_view.rst
  docs/cookbook/recipe_improve_performance_large_datasets.rst
  docs/cookbook/recipe_knp_menu.rst
  docs/cookbook/recipe_sortable_listing.rst
  docs/cookbook/recipe_workflow_integration.rst
  docs/getting_started/creating_an_admin.rst
  docs/getting_started/the_form_view.rst
  docs/reference/advanced_configuration.rst
  docs/reference/architecture.rst
  docs/reference/dashboard.rst
  docs/reference/form_types.rst
  docs/reference/routing.rst
  docs/reference/templates.rst
Labels: docs

#5385 [Docs] fixed indention
  docs/cookbook/recipe_customizing_a_mosaic_list.rst
Labels: docs

#5382 Revert "Add config for default mosaic background (#5366)"
  docs/cookbook/recipe_customizing_a_mosaic_list.rst
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataAdminExtension.php
  src/Resources/config/core.xml
  src/Resources/views/CRUD/list_outer_rows_mosaic.html.twig
  src/Twig/GlobalVariables.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/Twig/GlobalVariablesTest.php
Labels: critical
