Repository sonata-project/SonataAdminBundle, pull requests merged in 2018-05, with the labels that each got.

#5098 Spell "deprecation" properly
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: pedantic

#5099 Add missing russian translation
  src/Resources/translations/SonataAdminBundle.ru.xliff
Labels: patch

#5100 Removed new warning produced by PHP7.2 in BaseFieldDescription.php
  src/Admin/BaseFieldDescription.php
Labels: patch

#5104 Added table-hover class to the table
  src/Resources/views/CRUD/base_list.html.twig
Labels: minor

#5103 Updating query parameter in URL and remeber opened tab after refresh.
  src/Resources/public/Admin.js
  src/Resources/views/CRUD/base_edit_form.html.twig
  src/Resources/views/CRUD/base_show.html.twig
Labels: minor
