Repository sonata-project/SonataAdminBundle, pull requests merged in 2018-02, with the labels that each got.

#4940 Update creating_an_admin.rst
  docs/getting_started/creating_an_admin.rst
Labels: docs

#4941 Don't show admin blocks in global search results when no filters are set for global_search
  src/Block/AdminSearchBlockService.php
  tests/Block/AdminSearchBlockServiceTest.php
Labels: patch

#4949 Fix including wrong template
  src/Resources/views/CRUD/Association/edit_one_to_many.html.twig
Labels: patch

#4918 Use ModelAutocompleteType without a linked admin class
  src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
Labels: patch

#4950 Class loader does not have 4.0 version
  composer.json
Labels: pedantic

#4956 Better handling of ChoiceFieldMaskType option 'map'
  src/Form/Type/ChoiceFieldMaskType.php
  src/Resources/views/Form/form_admin_fields.html.twig
  tests/Form/Type/ChoiceFieldMaskTypeTest.php
Labels: patch

#4948 Moved Twig getTemplate calls to Twig extension
  docs/reference/batch_actions.rst
  docs/reference/templates.rst
  src/Resources/config/twig.xml
  src/Resources/views/CRUD/Association/list_many_to_many.html.twig
  src/Resources/views/CRUD/Association/list_many_to_one.html.twig
  src/Resources/views/CRUD/Association/list_one_to_many.html.twig
  src/Resources/views/CRUD/Association/list_one_to_one.html.twig
  src/Resources/views/CRUD/action.html.twig
  src/Resources/views/CRUD/base_edit.html.twig
  src/Resources/views/CRUD/base_history.html.twig
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/CRUD/base_show.html.twig
  src/Resources/views/CRUD/batch_confirmation.html.twig
  src/Resources/views/CRUD/delete.html.twig
  src/Resources/views/CRUD/list__action.html.twig
  src/Resources/views/CRUD/list__batch.html.twig
  src/Resources/views/CRUD/list__select.html.twig
  src/Resources/views/CRUD/list_array.html.twig
  src/Resources/views/CRUD/list_boolean.html.twig
  src/Resources/views/CRUD/list_choice.html.twig
  src/Resources/views/CRUD/list_currency.html.twig
  src/Resources/views/CRUD/list_date.html.twig
  src/Resources/views/CRUD/list_datetime.html.twig
  src/Resources/views/CRUD/list_email.html.twig
  src/Resources/views/CRUD/list_html.html.twig
  src/Resources/views/CRUD/list_outer_rows_list.html.twig
  src/Resources/views/CRUD/list_percent.html.twig
  src/Resources/views/CRUD/list_string.html.twig
  src/Resources/views/CRUD/list_time.html.twig
  src/Resources/views/CRUD/list_trans.html.twig
  src/Resources/views/CRUD/list_url.html.twig
  src/Resources/views/empty_layout.html.twig
  src/Resources/views/standard_layout.html.twig
  src/Twig/Extension/TemplateRegistryExtension.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
  tests/Twig/Extension/TemplateRegistryExtensionTest.php
Labels: minor

#4961 Add admin code to Twig get_admin_template function
  docs/reference/batch_actions.rst
  docs/reference/templates.rst
  src/Resources/config/twig.xml
  src/Resources/views/CRUD/Association/list_many_to_many.html.twig
  src/Resources/views/CRUD/Association/list_many_to_one.html.twig
  src/Resources/views/CRUD/Association/list_one_to_many.html.twig
  src/Resources/views/CRUD/Association/list_one_to_one.html.twig
  src/Resources/views/CRUD/base_history.html.twig
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/CRUD/list__action.html.twig
  src/Resources/views/CRUD/list__batch.html.twig
  src/Resources/views/CRUD/list__select.html.twig
  src/Resources/views/CRUD/list_array.html.twig
  src/Resources/views/CRUD/list_boolean.html.twig
  src/Resources/views/CRUD/list_choice.html.twig
  src/Resources/views/CRUD/list_currency.html.twig
  src/Resources/views/CRUD/list_date.html.twig
  src/Resources/views/CRUD/list_datetime.html.twig
  src/Resources/views/CRUD/list_email.html.twig
  src/Resources/views/CRUD/list_html.html.twig
  src/Resources/views/CRUD/list_outer_rows_list.html.twig
  src/Resources/views/CRUD/list_percent.html.twig
  src/Resources/views/CRUD/list_string.html.twig
  src/Resources/views/CRUD/list_time.html.twig
  src/Resources/views/CRUD/list_trans.html.twig
  src/Resources/views/CRUD/list_url.html.twig
  src/Twig/Extension/TemplateRegistryExtension.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
  tests/Twig/Extension/TemplateRegistryExtensionTest.php
Labels: patch

#4963 Catch all clicks on a link
  src/Resources/views/CRUD/Association/edit_many_script.html.twig
Labels: patch

#4971 Update installation.rst
  docs/getting_started/installation.rst
Labels: docs

#4975 Update installation docs
  docs/getting_started/installation.rst
Labels: docs

#4972 improve mosaic template
  src/Resources/public/css/styles.css
  src/Resources/views/CRUD/list_outer_rows_mosaic.html.twig
Labels: minor

#4933 Use form event listener to fix preValidation
  src/Admin/AbstractAdmin.php
  src/Controller/CRUDController.php
  tests/Admin/AdminTest.php
Labels: patch

#4976 Improve docs: Getting started
  docs/getting_started/creating_an_admin.rst
  docs/getting_started/installation.rst
  docs/getting_started/the_form_view.rst
  docs/getting_started/the_list_view.rst
Labels: docs

#4981 Replace string types with FQCN types in docs
  docs/cookbook/recipe_file_uploads.rst
  docs/cookbook/recipe_select2.rst
  docs/reference/extensions.rst
  docs/reference/form_help_message.rst
  docs/reference/form_types.rst
Labels: docs

#4983 Make search result page less heavy
  src/Resources/views/Block/block_search_result.html.twig
Labels: minor

#4984 Fix docs for custom action
  docs/cookbook/recipe_custom_action.rst
Labels: docs
