Repository sonata-project/SonataAdminBundle, pull requests merged in 2018-03, with the labels that each got.

#4991 Fix creating admin docs
  docs/getting_started/creating_an_admin.rst
Labels: docs

#4990 Fix fatal error in strict mode: strlen() expects parameter 1 to be string, null given
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
Labels: patch

#4993 Empty boxes configuration docs
  docs/images/empty_boxes_fade.png
  docs/images/empty_boxes_hide.png
  docs/images/empty_boxes_show.png
  docs/reference/search.rst
Labels: docs

#4995 Improve create action docs
  docs/cookbook/recipe_custom_action.rst
Labels: docs

#4987 check `sonata_admin.field_description`, somewhere is null;
  src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
Labels: patch

#4996 Avoid trying to use non public getters on `BaseFieldDescription`
  src/Admin/BaseFieldDescription.php
  tests/Admin/BaseFieldDescriptionTest.php
  tests/Fixtures/Entity/Foo.php
Labels: patch

#4998 Allow `null` values as argument 1 for `FieldDescriptionInterface::getFieldValue()`
  src/Admin/BaseFieldDescription.php
  src/Admin/FieldDescriptionInterface.php
  tests/Admin/BaseFieldDescriptionTest.php
Labels: patch

#5002 Improve installation docs
  docs/getting_started/installation.rst
Labels: docs

#5004 Configurable button_create template in base_list view
  src/Resources/views/CRUD/base_list.html.twig
Labels: patch

#5006 Replaced calls to internal Twig Environment loadTemplate method with load
  UPGRADE-3.x.md
  src/Twig/Extension/SonataAdminExtension.php
  tests/Controller/HelperControllerTest.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: patch

#5008 Update documentation for symfony4
  docs/cookbook/recipe_custom_action.rst
  docs/cookbook/recipe_customizing_a_mosaic_list.rst
  docs/cookbook/recipe_data_mapper.rst
  docs/cookbook/recipe_delete_field_group.rst
  docs/cookbook/recipe_dynamic_form_modification.rst
  docs/cookbook/recipe_file_uploads.rst
  docs/cookbook/recipe_improve_performance_large_datasets.rst
  docs/cookbook/recipe_knp_menu.rst
  docs/cookbook/recipe_lock_protection.rst
  docs/cookbook/recipe_overwrite_admin_configuration.rst
  docs/cookbook/recipe_select2.rst
  docs/cookbook/recipe_sortable_listing.rst
  docs/cookbook/recipe_sortable_sonata_type_model.rst
  docs/getting_started/creating_an_admin.rst
  docs/getting_started/installation.rst
  docs/getting_started/the_form_view.rst
  docs/reference/action_create_edit.rst
  docs/reference/action_export.rst
  docs/reference/action_list.rst
  docs/reference/action_show.rst
  docs/reference/advanced_configuration.rst
  docs/reference/architecture.rst
  docs/reference/batch_actions.rst
  docs/reference/breadcrumbs.rst
  docs/reference/child_admin.rst
  docs/reference/conditional_validation.rst
  docs/reference/configuration.rst
  docs/reference/console.rst
  docs/reference/dashboard.rst
  docs/reference/extensions.rst
  docs/reference/field_types.rst
  docs/reference/form_help_message.rst
  docs/reference/form_types.rst
  docs/reference/preview_mode.rst
  docs/reference/routing.rst
  docs/reference/saving_hooks.rst
  docs/reference/security.rst
  docs/reference/templates.rst
  docs/reference/translation.rst
  docs/reference/troubleshooting.rst
Labels: docs

#5010 Minor composer improvements
  composer.json
Labels: pedantic

#5011 Add missing french translation for toggle_navigation
  src/Resources/translations/SonataAdminBundle.fr.xliff
Labels: patch

#4331 Added FilterPersister to customize the way filters are stored
  UPGRADE-3.x.md
  docs/cookbook/recipe_persisting_filters.rst
  docs/index.rst
  docs/reference/configuration.rst
  src/Admin/AbstractAdmin.php
  src/Controller/HelperController.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataAdminExtension.php
  src/Filter/Persister/FilterPersisterInterface.php
  src/Filter/Persister/SessionFilterPersister.php
  src/Resources/config/core.xml
  tests/Admin/AdminTest.php
  tests/Controller/HelperControllerTest.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
  tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php
  tests/Filter/Persister/SessionFilterPersisterTest.php
Labels: minor

#5018 Fix missed controllers in documentation
  docs/cookbook/recipe_custom_action.rst
  docs/reference/architecture.rst
  docs/reference/routing.rst
Labels: docs

#5019 Add sf4 support to explain command
  src/Command/ExplainAdminCommand.php
  tests/Command/ExplainAdminCommandTest.php
Labels: patch

#5017 Add required option to editable list choice
  docs/reference/field_types.rst
  src/Twig/Extension/SonataAdminExtension.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: minor

#5023 Fixed a form type to FQCN in CollectionType docs
  docs/reference/form_types.rst
Labels: docs

#5020 removed old code
  src/DependencyInjection/SonataAdminExtension.php
  src/Resources/config/core.xml
Labels: pedantic

#4992 Fix editable relation on list
  src/Controller/HelperController.php
  tests/Controller/HelperControllerTest.php
Labels: patch

#4980 Move templates from AbstractAdmin and Pool to TemplateRegistry
  UPGRADE-3.x.md
  docs/reference/templates.rst
  src/Admin/AbstractAdmin.php
  src/Admin/Pool.php
  src/Block/AdminListBlockService.php
  src/Controller/CRUDController.php
  src/Controller/CoreController.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/Resources/config/block.xml
  src/Resources/config/core.xml
  src/Resources/config/twig.xml
  src/Resources/views/CRUD/action.html.twig
  src/Resources/views/CRUD/base_edit.html.twig
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/CRUD/base_show.html.twig
  src/Resources/views/CRUD/batch_confirmation.html.twig
  src/Resources/views/CRUD/delete.html.twig
  src/Resources/views/empty_layout.html.twig
  src/Resources/views/standard_layout.html.twig
  src/Templating/MutableTemplateRegistryInterface.php
  src/Templating/TemplateRegistry.php
  src/Templating/TemplateRegistryInterface.php
  src/Twig/Extension/SonataAdminExtension.php
  src/Twig/Extension/TemplateRegistryExtension.php
  tests/Admin/AdminTest.php
  tests/Admin/PoolTest.php
  tests/Block/AdminListBlockServiceTest.php
  tests/Controller/CRUDControllerTest.php
  tests/Controller/CoreControllerTest.php
  tests/Controller/HelperControllerTest.php
  tests/Templating/TemplateRegistryTest.php
  tests/Twig/Extension/FakeTemplateRegistryExtension.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
  tests/Twig/Extension/TemplateRegistryExtensionTest.php
Labels: minor

#5033 Fix mocks
  tests/Controller/HelperControllerTest.php
Labels: pedantic

#5035 Document another way to add dashboard action
  docs/cookbook/recipe_custom_action.rst
Labels: docs

#5039 Add pool alias
  src/Resources/config/core.xml
Labels: patch

#5041 Add SonataAnnotationBundle to docs
  docs/cookbook/recipe_creating_an_admin_with_annotations.rst
  docs/images/admin_with_annotations.png
  docs/index.rst
Labels: docs

#5042 Simplify template based on inline standard
  src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig
Labels: patch

#5047 Fix for hidden jQuery UI dialog close button
  docs/reference/configuration.rst
  src/DependencyInjection/Configuration.php
  tests/DependencyInjection/SonataAdminExtensionTest.php
Labels: patch

#4977 Fix error if no object in relationship
  src/Resources/views/CRUD/Association/list_many_to_one.html.twig
Labels: patch

#5051 Disable form submit buttons when the form gets submitted
  src/Resources/public/Admin.js
Labels: patch
