Repository sonata-project/SonataAdminBundle, pull requests merged in 2018-09, with the labels that each got.

#5144 #5137 handle ArrayCollection from PHPCR in SimplePager
  UPGRADE-4.0.md
  src/Datagrid/SimplePager.php
  tests/Datagrid/SimplePagerTest.php
Labels: patch

#5219 Fix negative admin unique id on 32 bits platforms
  src/Admin/AbstractAdmin.php
Labels: patch

#5223 Updated Luxembourgish translations
  src/Resources/translations/SonataAdminBundle.lb.xliff
Labels: patch

#5198 Add runtime exception
  src/Controller/CRUDController.php
  tests/Controller/CRUDControllerTest.php
Labels: minor

#5228 Fixed controller reference deprecations
  docs/cookbook/recipe_knp_menu.rst
  docs/reference/annotations.rst
  docs/reference/form_types.rst
  docs/reference/routing.rst
  src/Annotation/Admin.php
  src/Command/GenerateAdminCommand.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/Route/RouteCollection.php
  tests/Command/ExplainAdminCommandTest.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
  tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php
  tests/Fixtures/Command/explain_admin.txt
  tests/Fixtures/Command/explain_admin_empty_validator.txt
Labels: patch

#5093 Adds a maker to generate admin class, controller and services for a given entity
  .travis/before_install_test.sh
  docs/reference/console.rst
  docs/requirements.txt
  src/DependencyInjection/Compiler/AdminMakerCompilerPass.php
  src/DependencyInjection/SonataAdminExtension.php
  src/Maker/AdminMaker.php
  src/Resources/config/makers.xml
  src/Resources/skeleton/Admin.tpl.php
  src/Resources/skeleton/AdminController.tpl.php
  src/SonataAdminBundle.php
  tests/DependencyInjection/Compiler/AdminMakerCompilerPassTest.php
  tests/Maker/AdminMakerTest.php
Labels: minor

#5234 [Docs] Fixed method visibility and `TYPE_EQUAL` filter constant at docs
  docs/cookbook/recipe_select2.rst
  docs/reference/action_create_edit.rst
  docs/reference/action_list.rst
  docs/reference/action_show.rst
  docs/reference/batch_actions.rst
  docs/reference/extensions.rst
  docs/reference/field_types.rst
  docs/reference/form_help_message.rst
  docs/reference/routing.rst
  docs/reference/translation.rst
Labels: docs
