Repository sonata-project/SonataAdminBundle, pull requests merged in 2018-08, with the labels that each got.

#5175 Simple Typo fix
  docs/cookbook/recipe_delete_field_group.rst
Labels: docs

#5172 Update Mosaic Class
  src/Admin/AbstractAdmin.php
Labels: minor

#5177 Update security.rst
  docs/reference/security.rst
Labels: docs

#5170 Improve hint to exception message
  src/Admin/Pool.php
  tests/Admin/PoolTest.php
Labels: minor

#5176 Use consistent admin uniqids
  src/Admin/AbstractAdmin.php
  tests/Admin/AdminTest.php
Labels: minor

#5179 Added Dutch translation for link_edit
  src/Resources/translations/SonataAdminBundle.nl.xliff
Labels: patch

#5153 Split the helper controller into invokable CaSes
  UPGRADE-3.x.md
  src/Action/AppendFormFieldElementAction.php
  src/Action/GetShortObjectDescriptionAction.php
  src/Action/RetrieveAutocompleteItemsAction.php
  src/Action/RetrieveFormFieldElementAction.php
  src/Action/SetObjectFieldValueAction.php
  src/Controller/HelperController.php
  src/Resources/config/actions.xml
  src/Resources/config/core.xml
  src/Resources/config/routing/sonata_admin.xml
  tests/Action/AppendFormFieldElementActionTest.php
  tests/Action/GetShortObjectDescriptionActionTest.php
  tests/Action/RetrieveAutocompleteItemsActionTest.php
  tests/Action/RetrieveFormFieldElementActionTest.php
  tests/Action/SetObjectFieldValueActionTest.php
  tests/Controller/HelperControllerTest.php
Labels: minor

#5189 Add missing translation
  src/Resources/translations/SonataAdminBundle.fr.xliff
Labels: patch

#5187 SonataAdmin without User Bundle docs
  docs/cookbook/recipe_sonata_admin_without_user_bundle.rst
  docs/images/admin_without_user_bundle_login.png
  docs/index.rst
Labels: docs

#5192 Fix code highlight
  docs/cookbook/recipe_creating_an_admin_with_annotations.rst
  docs/cookbook/recipe_custom_action.rst
  docs/cookbook/recipe_delete_field_group.rst
  docs/cookbook/recipe_image_previews.rst
  docs/cookbook/recipe_knp_menu.rst
  docs/cookbook/recipe_select2.rst
  docs/cookbook/recipe_sonata_admin_without_user_bundle.rst
  docs/cookbook/recipe_sortable_listing.rst
  docs/cookbook/recipe_sortable_sonata_type_model.rst
Labels: docs

#5186 Fix tab id when it contains backslash
  src/Resources/views/CRUD/base_edit_form.html.twig
  src/Resources/views/CRUD/base_show.html.twig
Labels: patch

#5195 Fix check of form fields because it didn't check correctly
  src/Controller/CRUDController.php
  tests/Controller/CRUDControllerTest.php
Labels: critical, patch

#5205 use lowercase
  src/DependencyInjection/Compiler/ExtensionCompilerPass.php
Labels: critical, pedantic

#5203 Fixed error 500 when requesting short object description as json
  src/Action/GetShortObjectDescriptionAction.php
  tests/Action/GetShortObjectDescriptionActionTest.php
Labels: patch

#5131 Added an affirmative twig grant checker
  src/Resources/config/twig.xml
  src/Resources/views/Core/dashboard.html.twig
  src/Twig/Extension/SonataAdminExtension.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
  tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: minor

#5194 Use uniqid method to generate tab id
  src/Resources/views/CRUD/base_edit_form.html.twig
  src/Resources/views/CRUD/base_show.html.twig
Labels: minor

#5133 fixing negative result getNbResults, if there are not results
  src/Datagrid/SimplePager.php
  tests/Datagrid/SimplePagerTest.php
Labels: patch

#5166 Trigger event manually when iCheck input has changed
  src/Resources/public/Admin.js
Labels: patch

#5213 Add translation for zh_HK (Traditional Chinese)
  src/Resources/translations/SonataAdminBundle.zh_HK.xliff
Labels: patch
