Repository sonata-project/SonataAdminBundle, pull requests merged in 2018-06, with the labels that each got.

#5113 [Documentation] Added SonataAdminBundle link
  docs/index.rst
Labels: docs

#5115 updated docs for child admins
  docs/reference/child_admin.rst
Labels: docs

#5122 Apply new CS fixer rules
  src/Admin/BaseFieldDescription.php
  src/Datagrid/Datagrid.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  tests/Command/GenerateAdminCommandTest.php
  tests/Datagrid/PagerTest.php
  tests/DependencyInjection/Compiler/AnnotationCompilerPassTest.php
  tests/Form/Type/ModelTypeTest.php
Labels: critical, pedantic

#5126 Add missing polish translation
  src/Resources/translations/SonataAdminBundle.pl.xliff
Labels: patch

#5127 Add title attribute to sidebar toggle
  src/Resources/views/standard_layout.html.twig
Labels: minor

#5116 Fix display for empty initial value in choice field mask
  src/Resources/views/Form/form_admin_fields.html.twig
Labels: patch

#5136 Escape admin code in autocomplete
  src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
Labels: patch
