Repository sonata-project/SonataAdminBundle, pull requests merged in 2018-04, with the labels that each got.

#5050 Increase consistency on default page sizes
  src/Admin/AbstractAdmin.php
  tests/Admin/AdminTest.php
Labels: patch

#5054 Fix form types FQCN on Sonata Filters
  src/Form/Type/Filter/ChoiceType.php
  src/Form/Type/Filter/DateRangeType.php
  src/Form/Type/Filter/DateTimeRangeType.php
  src/Form/Type/Filter/DateTimeType.php
  src/Form/Type/Filter/DateType.php
  src/Form/Type/Filter/NumberType.php
  tests/Form/Type/Filter/DateTimeRangeTypeTest.php
Labels: patch

#5049 Force top: 0 on navbar positioning on mobile
  src/Resources/public/css/layout.css
Labels: patch

#5057 Corrected collapse parameters
  docs/reference/action_list.rst
Labels: docs

#5060 Remove alignment
  docs/reference/configuration.rst
Labels: pedantic

#5061 Delete sonata website on sidebar footer
  src/Resources/views/standard_layout.html.twig
Labels: minor

#5053 Allow to know which button triggered the submit button
  src/Resources/public/Admin.js
Labels: patch

#5068 Revert "Simplify template based on inline standard"
  src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig
Labels: patch

#5070 Calls to AbstractAdmin::getTemplate put back
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  src/Controller/CRUDController.php
  src/Twig/Extension/SonataAdminExtension.php
  src/Twig/Extension/TemplateRegistryExtension.php
  tests/Controller/CRUDControllerTest.php
  tests/Controller/HelperControllerTest.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
  tests/Twig/Extension/TemplateRegistryExtensionTest.php
Labels: patch

#5071 Set persistFilters option to true while setting the filter persister
  src/Admin/AbstractAdmin.php
  tests/Admin/AdminTest.php
Labels: patch

#5074 Fix tests
  tests/Controller/CRUDControllerTest.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: pedantic

#5058 Admin can have multiple parents now
  UPGRADE-3.x.md
  docs/reference/child_admin.rst
  src/Admin/AbstractAdmin.php
  tests/Admin/AdminTest.php
Labels: minor

#5046 [Doc] Added Workflow integration documentation
  docs/cookbook/recipe_workflow_integration.rst
  docs/images/admin_with_workflow.png
  docs/index.rst
Labels: docs

#5084 Update getting started docs
  docs/getting_started/creating_an_admin.rst
Labels: docs

#5086 Unify menu item generation
  src/Menu/Provider/GroupMenuProvider.php
  tests/Menu/Provider/GroupMenuProviderTest.php
Labels: patch

#5088 [tests] Simplify assets tests at `SonataAdminExtensionTest`
  tests/DependencyInjection/SonataAdminExtensionTest.php
Labels: pedantic

#5090 Fix a table cell align
  docs/reference/security.rst
Labels: docs
