Repository sonata-project/SonataAdminBundle, pull requests merged in 2018-11, with the labels that each got.

#5294 Fix the listMode view when sorting applied
  src/Resources/views/CRUD/base_list.html.twig
Labels: patch

#5300 updated bootstrap.php file
  tests/bootstrap.php
Labels: pedantic

#5310 Edit wrong example for command make:sonata:admin
  docs/reference/console.rst
Labels: docs

#5317 deprecate header_style
  UPGRADE-3.x.md
  src/Datagrid/ListMapper.php
Labels: minor

#5305 Fixed trying to access non-existing properties in strict_variables mode
  src/Resources/views/CRUD/Association/edit_many_to_many.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig
Labels: patch
