Repository sonata-project/SonataAdminBundle, pull requests merged in 2019-10, with the labels that each got.

#5702 Fix arguments passed to `transchoice()` Twig filter at `block_stats.html.twig`
  src/Resources/views/Block/block_stats.html.twig
Labels: patch

#5703 Fixed checks for array and traversable values
  src/Admin/AbstractAdmin.php
  src/Form/Type/ChoiceFieldMaskType.php
Labels: patch

#5709 [Docs] Update recipe removing unexisting method
  docs/cookbook/recipe_sonata_admin_without_user_bundle.rst
Labels: docs

#5718 Update SonataAdminBundle.zh_CN.xliff
  src/Resources/translations/SonataAdminBundle.zh_CN.xliff
Labels: pedantic
