Repository sonata-project/SonataAdminBundle, pull requests merged in 2019-11, with the labels that each got.

#5724 Change some test calls from isInstanceOf to assertInstanceOf
  tests/Action/AppendFormFieldElementActionTest.php
  tests/Action/GetShortObjectDescriptionActionTest.php
  tests/Action/RetrieveAutocompleteItemsActionTest.php
  tests/Action/RetrieveFormFieldElementActionTest.php
  tests/Action/SearchActionTest.php
  tests/Action/SetObjectFieldValueActionTest.php
  tests/Admin/AdminHelperTest.php
  tests/Admin/BaseFieldDescriptionTest.php
  tests/Admin/FieldDescriptionCollectionTest.php
  tests/Controller/CoreControllerTest.php
  tests/Controller/HelperControllerTest.php
Labels: pedantic

#5642 Add scalar value for _per_page to Datagrid in AdminStatsBlockService
  src/Datagrid/Datagrid.php
  tests/Datagrid/DatagridTest.php
Labels: patch

#5713 Toggle required attribute when using choice_field_mask_widget.
  src/Resources/views/Form/form_admin_fields.html.twig
Labels: patch

#5712 checking csrf_protection in delete method.
  src/Controller/CRUDController.php
  tests/Controller/CRUDControllerTest.php
Labels: minor

#5747 Escape backslashes in markdown
  docs/reference/form_types.rst
Labels: docs

#5748 Add the basic doctrine metadata
  docs/getting_started/creating_an_admin.rst
Labels: docs

#5759 Prevent installing Doctrine bundle 2
  composer.json
Labels: critical, patch
