Repository sonata-project/SonataAdminBundle, pull requests merged in 2019-07, with the labels that each got.

#5581 Fix and update doc about template in order to not use the Twig namespaced syntax
  docs/reference/templates.rst
Labels: docs

#5618 Replace `Twig_Environment` by its namespaced variant
  src/Controller/HelperController.php
  tests/Controller/CRUDControllerTest.php
  tests/Form/Widget/BaseWidgetTest.php
  tests/Menu/Integration/BaseMenuTest.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: pedantic

#5614 Prepare API narrowing
  src/Admin/AbstractAdmin.php
  src/Admin/AdminHelper.php
  src/Admin/BaseFieldDescription.php
  src/Controller/CRUDController.php
  src/Datagrid/Datagrid.php
  src/Datagrid/Pager.php
  src/Form/DataTransformer/ModelToIdPropertyTransformer.php
  src/Form/DataTransformer/ModelToIdTransformer.php
  src/Menu/Matcher/Voter/ActiveVoter.php
  src/Menu/Matcher/Voter/ChildrenVoter.php
  src/Security/Acl/Permission/AdminPermissionMap.php
  src/Security/Handler/AclSecurityHandler.php
  src/Templating/TemplateRegistry.php
  src/Templating/TemplateRegistryInterface.php
  tests/Admin/AdminTest.php
  tests/Datagrid/DatagridTest.php
  tests/Templating/TemplateRegistryTest.php
Labels: minor

#5578 Implements "format" option to show type "trans" as it is already in the list type "trans"
  docs/reference/field_types.rst
  src/Resources/views/CRUD/list_trans.html.twig
  src/Resources/views/CRUD/show_trans.html.twig
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: minor

#5632 Update constraint for "twig/twig" to ^2.10
  composer.json
Labels: patch

#5635 #5633 fix using Commands for symfony 2.8.x versions
  src/Command/CreateClassCacheCommand.php
  src/Command/ExplainAdminCommand.php
  src/Command/GenerateAdminCommand.php
  src/Command/GenerateObjectAclCommand.php
  src/Command/ListAdminCommand.php
  src/Command/SetupAclCommand.php
Labels: patch

#5639 Fix argument passed to `AbstractAdmin::toString()` at `base_list.htm.twig`
  src/Resources/views/CRUD/base_list.html.twig
Labels: patch

#5638 Fix when a service have a numeric id
  src/DependencyInjection/Compiler/ModelManagerCompilerPass.php
  src/DependencyInjection/Compiler/ObjectAclManipulatorCompilerPass.php
Labels: patch

#5643 fix ChoiceFieldMaskType script, escape field value
  src/Resources/views/Form/form_admin_fields.html.twig
Labels: patch

#5627 Replace `get_class($this)` with `static::class`
  src/Admin/AbstractAdmin.php
  src/Controller/CRUDController.php
Labels: pedantic

#5650 Use Twig namespaced classes
  src/Twig/Extension/SonataAdminExtension.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: pedantic

#5649 Update some docblocks
  src/Admin/AccessRegistryInterface.php
  src/Admin/AdminExtensionInterface.php
  src/Admin/AdminInterface.php
  src/Admin/FieldDescriptionInterface.php
  src/Command/CreateClassCacheCommand.php
  src/Command/ExplainAdminCommand.php
  src/Command/GenerateAdminCommand.php
  src/Command/GenerateObjectAclCommand.php
  src/Command/ListAdminCommand.php
  src/Command/SetupAclCommand.php
  src/Controller/CRUDController.php
  src/Filter/Persister/SessionFilterPersister.php
  src/Model/ModelManagerInterface.php
  src/Security/Handler/SecurityHandlerInterface.php
  src/Twig/Extension/SonataAdminExtension.php
Labels: pedantic
