Repository sonata-project/SonataAdminBundle, pull requests merged in 2019-06, with the labels that each got.

#5566 [#5564] Fix "cannot be used as a trait" in twig 2.11
  src/Resources/views/CRUD/base_edit_form.html.twig
Labels: patch

#5570 Fix "cannot be used as a trait" in twig 2.11
  src/Resources/views/CRUD/base_edit_form.html.twig
Labels: patch

#5590 Use new controller syntax at "sonata:admin:generate" command
  src/Command/GenerateAdminCommand.php
  tests/Command/GenerateAdminCommandTest.php
Labels: patch

#5543 [Pool] Minor improvement at `Pool::getAdminByAdminCode()`
  src/Admin/Pool.php
  tests/Admin/PoolTest.php
Labels: minor

#5592 [Doc] Use "auto" as password encoder instead of "bcrypt"
  docs/cookbook/recipe_sonata_admin_without_user_bundle.rst
Labels: docs

#5593 Don't truncate subjects to 15 characters at navbar
  src/Resources/views/CRUD/base_edit.html.twig
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/CRUD/base_show.html.twig
Labels: minor

#5576 Bump "twig/twig" to "^2.9" in order to replace usages of deprecated features
  composer.json
  src/Resources/views/Block/block_admin_list.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig
  src/Resources/views/CRUD/action_buttons.html.twig
  src/Resources/views/CRUD/base_acl_macro.html.twig
  src/Resources/views/CRUD/base_edit_form_macro.html.twig
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/CRUD/base_list_field.html.twig
  src/Resources/views/CRUD/base_show_field.html.twig
  src/Resources/views/CRUD/display_boolean.html.twig
  src/Resources/views/CRUD/display_date.html.twig
  src/Resources/views/CRUD/display_datetime.html.twig
  src/Resources/views/CRUD/display_time.html.twig
  src/Resources/views/CRUD/list_boolean.html.twig
  src/Resources/views/CRUD/list_choice.html.twig
  src/Resources/views/CRUD/list_url.html.twig
  src/Resources/views/CRUD/show_choice.html.twig
  src/Resources/views/CRUD/show_url.html.twig
  src/Resources/views/CRUD/tree.html.twig
  src/Resources/views/Core/add_block.html.twig
  src/Resources/views/Core/search.html.twig
  src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
  src/Resources/views/Form/filter_admin_fields.html.twig
  src/Resources/views/Form/form_admin_fields.html.twig
  src/Resources/views/Form/silex_form_div_layout.html.twig
  src/Resources/views/Menu/sonata_menu.html.twig
  src/Resources/views/standard_layout.html.twig
Labels: minor

#5585 Restrict mappers from configured role
  docs/reference/architecture.rst
  src/Datagrid/DatagridMapper.php
  src/Datagrid/ListMapper.php
  src/Form/FormMapper.php
  src/Show/ShowMapper.php
  tests/Datagrid/DatagridMapperTest.php
  tests/Datagrid/ListMapperTest.php
  tests/Form/FormMapperTest.php
  tests/Show/ShowMapperTest.php
Labels: feature, minor

#5579 Avoid to use deprecated `ContainerAwareCommand`
  composer.json
  src/Command/CreateClassCacheCommand.php
  src/Command/ExplainAdminCommand.php
  src/Command/GenerateAdminCommand.php
  src/Command/GenerateObjectAclCommand.php
  src/Command/ListAdminCommand.php
  src/Command/QuestionableCommand.php
  src/Command/SetupAclCommand.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/DependencyInjection/Compiler/AdminMakerCompilerPass.php
  src/DependencyInjection/Compiler/ModelManagerCompilerPass.php
  src/DependencyInjection/Compiler/ObjectAclManipulatorCompilerPass.php
  src/Resources/config/commands.xml
  src/SonataAdminBundle.php
  tests/Command/CreateClassCacheCommandTest.php
  tests/Command/ExplainAdminCommandTest.php
  tests/Command/GenerateAdminCommandTest.php
  tests/Command/GenerateObjectAclCommandTest.php
  tests/Command/ListAdminCommandTest.php
  tests/Command/SetupAclCommandTest.php
  tests/DependencyInjection/Compiler/ModelManagerCompilerPassTest.php
  tests/SonataAdminBundleTest.php
Labels: patch

#5595 Truncate navbar title at 100 characters
  src/Resources/views/CRUD/base_edit.html.twig
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/CRUD/base_show.html.twig
  src/Resources/views/standard_layout.html.twig
Labels: patch

#5591 Add alias in core.xml service definition
  src/Resources/config/core.xml
  tests/DependencyInjection/SonataAdminExtensionTest.php
Labels: patch

#5594 Ensure boolean values for "identifier" option passed to `ListMapper::add()`
  src/Datagrid/ListMapper.php
  src/Resources/views/CRUD/base_list_field.html.twig
  src/Resources/views/CRUD/base_list_flat_field.html.twig
  tests/Datagrid/ListMapperTest.php
Labels: patch

#5603 Deprecate some invalid arguments at `Pool::getAdminByAdminCode()`
  src/Admin/Pool.php
  src/Block/AdminSearchBlockService.php
  tests/Admin/PoolTest.php
  tests/Block/AdminSearchBlockServiceTest.php
Labels: minor

#5532 Hotfix of "Child _delete does not exist." error
  src/Admin/AdminHelper.php
  tests/Admin/AdminHelperTest.php
  tests/Fixtures/Entity/Foo.php
Labels: patch

#5541 Adding some space betwen column header label and column header sorting icon
  src/Resources/public/css/layout.css
Labels: patch

#5610 Fix wrong mocked return value for `Admin::getChild()` at `PoolTest`
  tests/Admin/PoolTest.php
Labels: bug
