Repository sonata-project/SonataAdminBundle, pull requests merged in 2019-03, with the labels that each got.

#5489 Match expected message with reality
  tests/Controller/CRUDControllerTest.php
Labels: critical, pedantic

#5486 fix(form-theme): form_row show_label check
  src/Resources/views/Form/form_admin_fields.html.twig
Labels: patch

#4768 CRUD/action_buttons.html.twig object check fix
  src/Resources/views/CRUD/action_buttons.html.twig
Labels: patch, pending author

#5239 fixed display top nav menu when user does not have rights for first or last module
  src/Resources/views/Core/add_block.html.twig
Labels: bug, patch

#5491 [WIP] Use "<time>" html tag when displaying fields of type date and datetime
  src/Resources/views/CRUD/display_date.html.twig
  src/Resources/views/CRUD/display_datetime.html.twig
  src/Resources/views/CRUD/display_time.html.twig
  src/Resources/views/CRUD/list_date.html.twig
  src/Resources/views/CRUD/list_datetime.html.twig
  src/Resources/views/CRUD/list_time.html.twig
  src/Resources/views/CRUD/show_date.html.twig
  src/Resources/views/CRUD/show_datetime.html.twig
  src/Resources/views/CRUD/show_time.html.twig
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: minor

#5481 set type int to _page and _per_page from request
  src/Admin/AbstractAdmin.php
  tests/Admin/AdminTest.php
Labels: patch

#5496 Use correct class in example
  docs/reference/child_admin.rst
Labels: docs

#5430 Fix batch checkbox display when list page is loaded through Ajax
  src/Admin/AbstractAdmin.php
Labels: patch

#5495 small docs fixes
  docs/cookbook/recipe_sortable_listing.rst
  docs/reference/batch_actions.rst
Labels: docs

#5314 redirect to tab
  src/Controller/CRUDController.php
  src/Resources/public/Admin.js
  src/Resources/views/CRUD/base_edit_form.html.twig
  tests/Controller/CRUDControllerTest.php
Labels: minor

#5508 different fixes to be consistent
  docs/cookbook/recipe_delete_field_group.rst
  docs/cookbook/recipe_icheck.rst
  docs/cookbook/recipe_improve_performance_large_datasets.rst
  docs/cookbook/recipe_persisting_filters.rst
  docs/reference/advanced_configuration.rst
  docs/reference/architecture.rst
  docs/reference/batch_actions.rst
  docs/reference/dashboard.rst
  docs/reference/extensions.rst
  docs/reference/field_types.rst
  docs/reference/form_types.rst
  docs/reference/routing.rst
  docs/reference/search.rst
  docs/reference/templates.rst
Labels: docs
