Repository sonata-project/SonataAdminBundle, pull requests merged in 2019-09, with the labels that each got.

#5683 Fix some CS issues at Twig templates
  src/Resources/views/Block/block_rss_dashboard.html.twig
  src/Resources/views/CRUD/Association/edit_many_script.html.twig
  src/Resources/views/CRUD/Association/edit_many_to_many.html.twig
  src/Resources/views/CRUD/Association/edit_many_to_one.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_one.html.twig
  src/Resources/views/CRUD/Association/show_one_to_many.html.twig
  src/Resources/views/CRUD/base_array_macro.html.twig
  src/Resources/views/CRUD/base_edit_form.html.twig
  src/Resources/views/CRUD/base_edit_form_macro.html.twig
  src/Resources/views/CRUD/base_inline_edit_field.html.twig
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/CRUD/base_show.html.twig
  src/Resources/views/CRUD/base_show_macro.html.twig
  src/Resources/views/CRUD/base_standard_edit_field.html.twig
  src/Resources/views/CRUD/edit_boolean.html.twig
  src/Resources/views/CRUD/list_trans.html.twig
  src/Resources/views/CRUD/show_array.html.twig
  src/Resources/views/CRUD/show_choice.html.twig
  src/Resources/views/CRUD/show_html.html.twig
  src/Resources/views/CRUD/show_trans.html.twig
  src/Resources/views/CRUD/tree.html.twig
  src/Resources/views/Core/add_block.html.twig
  src/Resources/views/Core/dashboard.html.twig
  src/Resources/views/Core/tab_menu_template.html.twig
  src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
  src/Resources/views/Form/form_admin_fields.html.twig
  src/Resources/views/Pager/base_links.html.twig
Labels: pedantic

#5628 Fix Twig template Form Type Autocomplete
  src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
Labels: patch

#5689 [revert #5669] Use deprecated "transchoice"
  src/Resources/views/CRUD/batch_confirmation.html.twig
  src/Resources/views/Pager/base_results.html.twig
  src/Resources/views/Pager/simple_pager_results.html.twig
Labels: patch

#5692 CRUDController::validateCsrfToken missing token
  src/Controller/CRUDController.php
Labels: patch

#5695 Make truncable all breadcrumb fragments
  src/Resources/views/standard_layout.html.twig
Labels: patch

#5694 Allow validate CSRF token from query string
  src/Controller/CRUDController.php
Labels: minor

#5697 Don't truncate breadcrumb components when "safe_label" is used
  src/Resources/views/standard_layout.html.twig
Labels: patch

#5690 Allow to use pluralized translations with block stats widgets
  docs/reference/dashboard.rst
  src/Resources/views/Block/block_stats.html.twig
Labels: enhancement
