Repository sonata-project/SonataAdminBundle, pull requests merged in 2019-02, with the labels that each got.

#5460 Call the method directly instead of invoking `__call()` at `BaseFieldDescription::getFieldValue()`
  src/Admin/BaseFieldDescription.php
Labels: pedantic

#5472 Added a link to the next chapter
  docs/getting_started/creating_an_admin.rst
Labels: docs

#5475 [Dashboard] Don't iterate over blocks if wanted condition is already reached
  src/Resources/views/Core/dashboard.html.twig
Labels: minor

#5479 Delete .styleci.yml
  .styleci.yml
Labels: pedantic

#5480 add blank lines after file paths in code examples
  docs/cookbook/recipe_auto_configure_admin_classes.rst
  docs/cookbook/recipe_workflow_integration.rst
  docs/getting_started/the_form_view.rst
Labels: docs
