Repository sonata-project/SonataAdminBundle, pull requests merged in 2019-04, with the labels that each got.

#5511 Fix failing tests
  tests/Controller/HelperControllerTest.php
Labels: critical, pedantic

#5512 Fix redirect to tab when there is no tab explicitly selected
  src/Controller/CRUDController.php
  src/Resources/public/Admin.js
Labels: patch

#5515 Documentation fixes, correct FQDN and FQDN escaping
  docs/reference/security.rst
Labels: docs

#5523 Fix links to un-editable results
  src/Action/SearchAction.php
Labels: patch

#5260 fix bootstrap js tab toggle not work when click add button more than 2 times
  src/Resources/views/CRUD/base_edit_form.html.twig
  src/Resources/views/CRUD/base_show.html.twig
Labels: patch

#5527 Fix namespace of SourceIteratorInterface
  src/Model/ModelManagerInterface.php
Labels: patch
