Repository sonata-project/SonataAdminBundle, pull requests merged in 2019-05, with the labels that each got.

#5536 Add moment locale fallback for de_DE
  src/Twig/Extension/SonataAdminExtension.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: patch

#5545 Adapt to new cs fixer rules
  tests/Action/DashboardActionTest.php
  tests/Admin/AdminHelperTest.php
  tests/Admin/AdminTest.php
  tests/Admin/BaseAdminModelManagerTest.php
  tests/Admin/BaseFieldDescriptionTest.php
  tests/Admin/BreadcrumbsBuilderTest.php
  tests/Admin/FieldDescriptionCollectionTest.php
  tests/Admin/PoolTest.php
  tests/Bridge/Exporter/AdminExporterTest.php
  tests/Command/CreateClassCacheCommandTest.php
  tests/Command/ExplainAdminCommandTest.php
  tests/Command/GenerateAdminCommandTest.php
  tests/Command/ListAdminCommandTest.php
  tests/Command/SetupAclCommandTest.php
  tests/Controller/CRUDControllerTest.php
  tests/Controller/CoreControllerTest.php
  tests/Datagrid/DatagridMapperTest.php
  tests/Datagrid/DatagridTest.php
  tests/Datagrid/ListMapperTest.php
  tests/Datagrid/PagerTest.php
  tests/Datagrid/SimplePagerTest.php
  tests/DependencyInjection/Compiler/AddFilterTypeCompilerPassTest.php
  tests/Event/AdminEventExtensionTest.php
  tests/Filter/FilterFactoryTest.php
  tests/Form/ChoiceList/LegacyModelChoiceListTest.php
  tests/Form/ChoiceList/ModelChoiceLoaderTest.php
  tests/Form/DataTransformer/ArrayToModelTransformerTest.php
  tests/Form/DataTransformer/LegacyModelsToArrayTransformerTest.php
  tests/Form/DataTransformer/ModelToIdPropertyTransformerTest.php
  tests/Form/DataTransformer/ModelToIdTransformerTest.php
  tests/Form/Extension/ChoiceTypeExtensionTest.php
  tests/Form/Extension/Field/Type/FormTypeFieldExtensionTest.php
  tests/Form/FormMapperTest.php
  tests/Form/Widget/FormSonataFilterChoiceWidgetTest.php
  tests/Generator/AdminGeneratorTest.php
  tests/Generator/ControllerGeneratorTest.php
  tests/Guesser/TypeGuesserChainTest.php
  tests/Mapper/BaseGroupedMapperTest.php
  tests/Menu/Matcher/Voter/ActiveVoterTest.php
  tests/Menu/Matcher/Voter/AdminVoterTest.php
  tests/Menu/Matcher/Voter/ChildrenVoterTest.php
  tests/Menu/MenuBuilderTest.php
  tests/Menu/Provider/GroupMenuProviderTest.php
  tests/Model/AuditManagerTest.php
  tests/Route/AdminPoolLoaderTest.php
  tests/Route/DefaultRouteGeneratorTest.php
  tests/Route/PathInfoBuilderTest.php
  tests/Route/QueryStringBuilderTest.php
  tests/Search/SearchHandlerTest.php
  tests/Security/Handler/AclSecurityHandlerTest.php
  tests/Security/Handler/RoleSecurityHandlerTest.php
  tests/Show/ShowMapperTest.php
  tests/SonataAdminBundleTest.php
  tests/Translator/Extractor/JMSTranslatorBundle/AdminExtractorTest.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
  tests/Util/AdminObjectAclDataTest.php
Labels: critical, pedantic

#5267 Add round for scrollTop + height for Windows
  src/Resources/public/Admin.js
Labels: patch

#5553 Fix tab name in base_edit_form
  src/Resources/views/CRUD/base_edit_form.html.twig
Labels: patch

#5560 Leverage `display_datetime.html.twig` from `history_revision_timestamp.html.twig`
  src/Resources/views/CRUD/history_revision_timestamp.html.twig
Labels: minor

#5563 Fix CreateClassCacheCommand deprecation message
  src/Command/CreateClassCacheCommand.php
  src/Resources/config/commands.xml
Labels: minor
