Repository sonata-project/SonataAdminBundle, pull requests merged in 2019-08, with the labels that each got.

#5659 Fix typo in Russian translation
  src/Resources/translations/SonataAdminBundle.ru.xliff
Labels: patch

#5658 Update some docblocks with "mixed" types
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  src/Admin/BreadcrumbsBuilderInterface.php
  src/Admin/UrlGeneratorInterface.php
  src/Datagrid/Pager.php
  src/Event/ConfigureEvent.php
  src/Event/PersistenceEvent.php
  src/Twig/GlobalVariables.php
  src/Util/AdminObjectAclData.php
Labels: pedantic

#5662 fixed namespace to access AbstractAdmin
  docs/cookbook/recipe_sortable_listing.rst
Labels: docs

#5664 Added more specific PHPDoc to interfaces
  src/Admin/AdminInterface.php
  src/Admin/FieldDescriptionInterface.php
  src/Builder/DatagridBuilderInterface.php
  src/Builder/FormContractorInterface.php
  src/Builder/ShowBuilderInterface.php
  src/Datagrid/ProxyQueryInterface.php
  src/Filter/FilterFactoryInterface.php
  src/Guesser/TypeGuesserInterface.php
  src/Model/AuditReaderInterface.php
  src/Model/ModelManagerInterface.php
  src/Security/Handler/AclSecurityHandlerInterface.php
  src/Security/Handler/SecurityHandlerInterface.php
  src/Util/ObjectAclManipulatorInterface.php
Labels: pedantic

#5669 Replace deprecated `transchoice` tags with `trans`
  src/Resources/views/CRUD/batch_confirmation.html.twig
  src/Resources/views/Pager/base_results.html.twig
  src/Resources/views/Pager/simple_pager_results.html.twig
Labels: patch

#5665 Use "twig" service instead of "sonata.templating"
  composer.json
  src/Block/AdminListBlockService.php
  src/Block/AdminSearchBlockService.php
  src/Block/AdminStatsBlockService.php
  src/Resources/config/block.xml
Labels: minor

#5672 Added more specific PHPDoc
  src/Admin/AbstractAdmin.php
  src/Admin/AbstractAdminExtension.php
Labels: pedantic

#5675 Update recipe_dynamic_form_modification.rst
  docs/cookbook/recipe_dynamic_form_modification.rst
Labels: docs

#5676 Replace calls to `call_user_func()` and `call_user_func_array()`
  src/Action/RetrieveAutocompleteItemsAction.php
  src/Admin/BaseFieldDescription.php
  src/Controller/CRUDController.php
  src/Controller/PolyfillControllerTrait.php
  src/Form/DataTransformer/ModelToIdPropertyTransformer.php
  src/Route/RouteCollection.php
  src/Twig/Extension/SonataAdminExtension.php
  tests/Event/AdminEventExtensionTest.php
Labels: pedantic

#5677 Update search.rst
  docs/reference/search.rst
Labels: docs
