Repository sonata-project/SonataAdminBundle, pull requests merged in 2019-12, with the labels that each got.

#5770 Fix creating files in the working directory with AdminMakerTest
  tests/Maker/AdminMakerTest.php
Labels: pedantic

#5768 Fixes incompatible $registry argument in GenerateObjectAclCommand class when using DoctrineBundle:^2.0
  src/Command/GenerateObjectAclCommand.php
  tests/Command/GenerateObjectAclCommandTest.php
Labels: patch

#5776 Allow doctrine/doctrine-bundle 2
  composer.json
Labels: patch

#5774 Use LogicException instead of Runtime exception
  src/Datagrid/DatagridMapper.php
  src/Datagrid/ListMapper.php
  src/Form/FormMapper.php
  src/Mapper/BaseGroupedMapper.php
  src/Show/ShowMapper.php
  tests/Datagrid/DatagridMapperTest.php
  tests/Datagrid/ListMapperTest.php
  tests/Form/FormMapperTest.php
  tests/Mapper/BaseGroupedMapperTest.php
  tests/Show/ShowMapperTest.php
Labels: minor

#5794 Add type declarations in tests
  tests/Action/RetrieveAutocompleteItemsActionTest.php
  tests/Admin/AdminTest.php
  tests/Admin/BaseAdminModelManagerTest.php
  tests/Admin/BreadcrumbsBuilderTest.php
  tests/Admin/PoolTest.php
  tests/Command/GenerateAdminCommandTest.php
  tests/Command/SetupAclCommandTest.php
  tests/Command/ValidatorsTest.php
  tests/Controller/CRUDControllerTest.php
  tests/Controller/CoreControllerTest.php
  tests/Datagrid/DatagridMapperTest.php
  tests/Datagrid/DatagridTest.php
  tests/Datagrid/ListMapperTest.php
  tests/Datagrid/PagerTest.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/SonataAdminExtensionTest.php
  tests/Event/AdminEventExtensionTest.php
  tests/Export/ExporterTest.php
  tests/Filter/FilterTest.php
  tests/Form/DataTransformer/LegacyModelsToArrayTransformerTest.php
  tests/Form/DataTransformer/ModelToIdPropertyTransformerTest.php
  tests/Form/FormMapperTest.php
  tests/Form/Type/ChoiceFieldMaskTypeTest.php
  tests/Form/Type/ModelTypeTest.php
  tests/Mapper/BaseGroupedMapperTest.php
  tests/Menu/Integration/BaseMenuTest.php
  tests/Menu/Integration/TabMenuTest.php
  tests/Menu/Matcher/Voter/AbstractVoterTest.php
  tests/Menu/Matcher/Voter/ActiveVoterTest.php
  tests/Menu/Matcher/Voter/AdminVoterTest.php
  tests/Menu/Matcher/Voter/ChildrenVoterTest.php
  tests/Menu/MenuBuilderTest.php
  tests/Menu/Provider/GroupMenuProviderTest.php
  tests/Model/AuditManagerTest.php
  tests/Route/AdminPoolLoaderTest.php
  tests/Route/DefaultRouteGeneratorTest.php
  tests/Route/QueryStringBuilderTest.php
  tests/Search/SearchHandlerTest.php
  tests/Security/Acl/Permission/AdminPermissionMapTest.php
  tests/Security/Handler/RoleSecurityHandlerTest.php
  tests/Show/ShowMapperTest.php
  tests/Translator/Extractor/JMSTranslatorBundle/AdminExtractorTest.php
  tests/Translator/NativeLabelTranslatorStrategyTest.php
  tests/Twig/Extension/FakeTemplateRegistryExtension.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
  tests/Util/AdminObjectAclDataTest.php
Labels: pedantic

#5790 Implement @methods
  src/Admin/AbstractAdmin.php
  src/Admin/AccessRegistryInterface.php
  src/Admin/AdminInterface.php
  src/Admin/LifecycleHookProviderInterface.php
  src/Templating/TemplateRegistryInterface.php
  tests/Admin/BreadcrumbsBuilderTest.php
Labels: major

#5795 Remove DiExtraBundle
  composer.json
  docs/reference/configuration.rst
  src/Annotation/Admin.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataAdminExtension.php
  tests/DependencyInjection/Compiler/AnnotationCompilerPassTest.php
  tests/DependencyInjection/SonataAdminExtensionTest.php
Labels: major

#5728 Add minimal functional test
  composer.json
  src/Resources/config/block.xml
  tests/Command/ValidatorsTest.php
  tests/Functional/AppKernel.php
  tests/Functional/Controller/DashboardActionTest.php
Labels: pedantic

#5801 Trigger deprecation when using a string name as filter type
  UPGRADE-3.x.md
  src/Filter/FilterFactory.php
  tests/Filter/FilterFactoryTest.php
Labels: minor

#5803 Include the edit modal and related script only when needed
  src/Resources/views/CRUD/Association/edit_many_to_many.html.twig
  src/Resources/views/CRUD/Association/edit_many_to_one.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_many.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_one.html.twig
  src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
Labels: minor

#5797 Remove sensio generator
  .travis.yml
  composer.json
  docs/reference/console.rst
  src/Command/CreateClassCacheCommand.php
  src/Command/GenerateAdminCommand.php
  src/Command/QuestionableCommand.php
  src/Controller/CRUDController.php
  src/DependencyInjection/Compiler/ModelManagerCompilerPass.php
  src/Generator/AdminGenerator.php
  src/Generator/ControllerGenerator.php
  src/Resources/config/commands.xml
  tests/Command/CreateClassCacheCommandTest.php
  tests/Command/GenerateAdminCommandTest.php
  tests/Controller/CRUDControllerTest.php
  tests/DependencyInjection/Compiler/ModelManagerCompilerPassTest.php
  tests/Fixtures/Admin/FieldDescription.php
  tests/Fixtures/Admin/ModelAdmin.php
  tests/Fixtures/Controller/BatchAdminController.php
  tests/Fixtures/Controller/ModelAdminController.php
  tests/Fixtures/StubTranslator.php
  tests/Fixtures/TestExtension.php
  tests/Form/Type/AdminTypeTest.php
  tests/Form/Widget/BaseWidgetTest.php
  tests/Form/Widget/FormSonataFilterChoiceWidgetTest.php
  tests/Form/Widget/FormSonataNativeCollectionWidgetTest.php
  tests/Functional/AppKernel.php
  tests/Generator/AdminGeneratorTest.php
  tests/Generator/ControllerGeneratorTest.php
  tests/Menu/Integration/BaseMenuTest.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: major

#5779 Apply iftrue and iffalse to tab and allow nested conditions
  src/Form/FormMapper.php
  src/Mapper/BaseGroupedMapper.php
  src/Show/ShowMapper.php
  tests/Form/FormMapperTest.php
  tests/Mapper/BaseGroupedMapperTest.php
  tests/Show/ShowMapperTest.php
Labels: minor
