Repository sonata-project/SonataAdminBundle, pull requests merged in 2020-04, with the labels that each got.

#6014 Add some missing return values
  src/Admin/AbstractAdmin.php
  src/Model/ModelManagerInterface.php
  tests/App/Admin/FieldDescription.php
  tests/App/Datagrid/Datagrid.php
  tests/App/Datagrid/Pager.php
  tests/App/Datagrid/ProxyQuery.php
  tests/App/Model/ModelManager.php
  tests/Fixtures/Admin/TagAdmin.php
Labels: patch

#6011 Fix argument type passed to `generateMenuUrl()`
  src/Menu/Provider/GroupMenuProvider.php
  src/Route/DefaultRouteGenerator.php
  tests/Menu/Provider/GroupMenuProviderTest.php
  tests/Route/DefaultRouteGeneratorTest.php
Labels: patch

#6020 Add more specific phpdoc
  src/Admin/AdminInterface.php
  src/Admin/UrlGeneratorInterface.php
  src/Filter/FilterInterface.php
  src/Route/RouteGeneratorInterface.php
Labels: pedantic

#6025 Deprecate getModelIdentifier
  src/Model/ModelManagerInterface.php
Labels: minor

#6032 Add missing polish translation
  src/Resources/translations/SonataAdminBundle.pl.xliff
Labels: patch

#6004 Handle parent association mappings
  src/Form/Type/AdminType.php
  tests/Form/Type/AdminTypeTest.php
Labels: patch

#6030 Prettify array field on show and list actions
  docs/reference/field_types.rst
  src/Resources/views/CRUD/base_array_macro.html.twig
  src/Resources/views/CRUD/list_array.html.twig
  src/Resources/views/CRUD/show_array.html.twig
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: minor

#6019 Default sort on "associated_property"
  docs/reference/action_list.rst
  src/Datagrid/ListMapper.php
  tests/Datagrid/ListMapperTest.php
Labels: minor

#6033 Rename getter
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  tests/Admin/BreadcrumbsBuilderTest.php
Labels: minor

#6038 Replace `$absolute` arguments with `$referenceType`
  src/Admin/AbstractAdmin.php
  src/Admin/UrlGeneratorInterface.php
  src/Route/DefaultRouteGenerator.php
  src/Route/RouteGeneratorInterface.php
  src/Twig/GlobalVariables.php
Labels: pedantic

#6047 Apply latest cs fixes
  tests/Controller/CRUDControllerTest.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
  tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php
Labels: critical, pedantic

#6044 Avoid collisions with cache keys at `AbstractAdmin::isGranted()`
  src/Admin/AbstractAdmin.php
  tests/Admin/AdminTest.php
Labels: patch

#6023 Some API update messages
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  src/Admin/BaseFieldDescription.php
  src/Admin/FieldDescriptionInterface.php
  src/Admin/UrlGeneratorInterface.php
  src/Datagrid/ListMapper.php
  src/Datagrid/Pager.php
  src/Filter/Filter.php
  src/Form/FormMapper.php
  src/Menu/Matcher/Voter/AdminVoter.php
  src/Model/ModelManagerInterface.php
  src/Show/ShowMapper.php
  src/Twig/Extension/SonataAdminExtension.php
  tests/Admin/AdminTest.php
  tests/Admin/BaseFieldDescriptionTest.php
  tests/App/Model/ModelManager.php
  tests/Controller/CRUDControllerTest.php
  tests/Fixtures/Admin/PostAdmin.php
  tests/Fixtures/Bundle/DemoAdminBundle.php
  tests/Form/ChoiceList/LegacyModelChoiceListTest.php
  tests/Form/ChoiceList/ModelChoiceLoaderTest.php
  tests/Form/DataTransformer/ArrayToModelTransformerTest.php
  tests/Form/DataTransformer/ModelToIdPropertyTransformerTest.php
  tests/Form/DataTransformer/ModelToIdTransformerTest.php
  tests/Form/Extension/Field/Type/FormTypeFieldExtensionTest.php
  tests/Form/FormMapperTest.php
  tests/Form/Widget/BaseWidgetTest.php
  tests/Security/Handler/NoopSecurityHandlerTest.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
  tests/Util/AdminObjectAclDataTest.php
  tests/Util/ObjectAclManipulatorTest.php
Labels: minor

#5138 adding deprecation notices to SimplePager::getResults
  UPGRADE-3.x.md
  tests/Datagrid/SimplePagerTest.php
Labels: minor

#6055 Fix nesting a Twig block definition under a non-capturing node
  src/Resources/views/CRUD/base_list_field.html.twig
  src/Resources/views/CRUD/list_boolean.html.twig
  src/Resources/views/CRUD/list_choice.html.twig
Labels: patch

#6058 Use proper syntax for phpdoc
  src/Filter/FilterInterface.php
Labels: patch

#6017 `LockInterface` extends from `ModelManagerInterface`
  UPGRADE-4.0.md
  src/Model/LockInterface.php
  tests/Admin/Extension/LockExtensionTest.php
Labels: major
