Repository sonata-project/SonataAdminBundle, pull requests merged in 2020-06, with the labels that each got.

#6128 Fix checkbox/radio button layout when iCheck is disabled
  src/Resources/public/css/styles.css
  src/Resources/views/standard_layout.html.twig
Labels: patch

#6131 Improve doc
  docs/cookbook/recipe_sortable_listing.rst
  docs/reference/action_list.rst
Labels: docs

#6136 Force to use hasser before getter
  src/Admin/AbstractAdmin.php
  src/Admin/BaseFieldDescription.php
  src/Admin/FieldDescriptionInterface.php
  src/Admin/ParentAdminInterface.php
  src/Admin/Pool.php
  src/Form/Extension/Field/Type/FormTypeFieldExtension.php
  src/Model/AuditManager.php
  src/Model/AuditManagerInterface.php
  src/Twig/Extension/SonataAdminExtension.php
  tests/Admin/PoolTest.php
Labels: minor

#6132 Replace truncate filter with u.truncate
  UPGRADE-3.x.md
  composer.json
  docs/cookbook/recipe_customizing_a_mosaic_list.rst
  src/Resources/views/CRUD/base_edit.html.twig
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/CRUD/base_show.html.twig
  src/Resources/views/CRUD/list_html.html.twig
  src/Resources/views/CRUD/list_outer_rows_mosaic.html.twig
  src/Resources/views/CRUD/show_html.html.twig
  src/Resources/views/standard_layout.html.twig
  src/Twig/Extension/StringExtension.php
  src/Twig/Extension/UnicodeString.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: minor

#6143 Prevent infinite recursion when mapping form fields with a help message
  src/Form/FormMapper.php
  tests/App/Admin/FooAdmin.php
Labels: patch

#6150 Simplify setting help in field description (minor)
  src/Form/FormMapper.php
Labels: pedantic

#6148 Stop building show/list/form when accessing fieldDescription
  src/Action/RetrieveAutocompleteItemsAction.php
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  tests/Admin/AdminTest.php
  tests/Fixtures/Admin/AvoidInfiniteLoopAdmin.php
Labels: patch

#6145 Fix BC after drop twig/extensions
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataAdminExtension.php
  src/Resources/config/twig_string.xml
  src/Twig/Extension/DeprecatedTextExtension.php
  src/Twig/Extension/StringExtension.php
  tests/DependencyInjection/SonataAdminExtensionTest.php
Labels: patch

#6138 Add missing translations
  src/Resources/translations/SonataAdminBundle.ar.xliff
  src/Resources/translations/SonataAdminBundle.bg.xliff
  src/Resources/translations/SonataAdminBundle.ca.xliff
  src/Resources/translations/SonataAdminBundle.cs.xliff
  src/Resources/translations/SonataAdminBundle.de.xliff
  src/Resources/translations/SonataAdminBundle.es.xliff
  src/Resources/translations/SonataAdminBundle.eu.xliff
  src/Resources/translations/SonataAdminBundle.fa.xliff
  src/Resources/translations/SonataAdminBundle.hr.xliff
  src/Resources/translations/SonataAdminBundle.hu.xliff
  src/Resources/translations/SonataAdminBundle.it.xliff
  src/Resources/translations/SonataAdminBundle.ja.xliff
  src/Resources/translations/SonataAdminBundle.lb.xliff
  src/Resources/translations/SonataAdminBundle.lt.xliff
  src/Resources/translations/SonataAdminBundle.lv.xliff
  src/Resources/translations/SonataAdminBundle.no.xliff
  src/Resources/translations/SonataAdminBundle.pl.xliff
  src/Resources/translations/SonataAdminBundle.pt.xliff
  src/Resources/translations/SonataAdminBundle.pt_BR.xliff
  src/Resources/translations/SonataAdminBundle.ro.xliff
  src/Resources/translations/SonataAdminBundle.ru.xliff
  src/Resources/translations/SonataAdminBundle.sk.xliff
  src/Resources/translations/SonataAdminBundle.sl.xliff
  src/Resources/translations/SonataAdminBundle.sv_SE.xliff
  src/Resources/translations/SonataAdminBundle.tr.xliff
  src/Resources/translations/SonataAdminBundle.uk.xliff
  src/Resources/translations/SonataAdminBundle.zh_CN.xliff
Labels: patch

#6154 Added phpstan to v3
  .github/workflows/qa.yaml
  composer.json
  phpstan-baseline.neon
  phpstan.neon.dist
Labels: pedantic

#6159 Allow null param for StringExtension construct
  src/Twig/Extension/StringExtension.php
Labels: patch

#6134 Added StringOperatorType
  src/Form/Type/Operator/StringOperatorType.php
  src/Resources/translations/SonataAdminBundle.ar.xliff
  src/Resources/translations/SonataAdminBundle.bg.xliff
  src/Resources/translations/SonataAdminBundle.ca.xliff
  src/Resources/translations/SonataAdminBundle.cs.xliff
  src/Resources/translations/SonataAdminBundle.de.xliff
  src/Resources/translations/SonataAdminBundle.en.xliff
  src/Resources/translations/SonataAdminBundle.es.xliff
  src/Resources/translations/SonataAdminBundle.eu.xliff
  src/Resources/translations/SonataAdminBundle.fa.xliff
  src/Resources/translations/SonataAdminBundle.fr.xliff
  src/Resources/translations/SonataAdminBundle.hr.xliff
  src/Resources/translations/SonataAdminBundle.hu.xliff
  src/Resources/translations/SonataAdminBundle.it.xliff
  src/Resources/translations/SonataAdminBundle.ja.xliff
  src/Resources/translations/SonataAdminBundle.lb.xliff
  src/Resources/translations/SonataAdminBundle.lt.xliff
  src/Resources/translations/SonataAdminBundle.lv.xliff
  src/Resources/translations/SonataAdminBundle.nl.xliff
  src/Resources/translations/SonataAdminBundle.no.xliff
  src/Resources/translations/SonataAdminBundle.pl.xliff
  src/Resources/translations/SonataAdminBundle.pt.xliff
  src/Resources/translations/SonataAdminBundle.pt_BR.xliff
  src/Resources/translations/SonataAdminBundle.ro.xliff
  src/Resources/translations/SonataAdminBundle.ru.xliff
  src/Resources/translations/SonataAdminBundle.sk.xliff
  src/Resources/translations/SonataAdminBundle.sl.xliff
  src/Resources/translations/SonataAdminBundle.sv_SE.xliff
  src/Resources/translations/SonataAdminBundle.tr.xliff
  src/Resources/translations/SonataAdminBundle.uk.xliff
  src/Resources/translations/SonataAdminBundle.zh_CN.xliff
  src/Resources/translations/SonataAdminBundle.zh_HK.xliff
  tests/Form/Type/Operator/StringOperatorTypeTest.php
Labels: minor
