Repository sonata-project/SonataAdminBundle, pull requests merged in 2020-05, with the labels that each got.

#6071 fix: add datetime in editable date form types for SetObjectFieldValue…
  src/Action/SetObjectFieldValueAction.php
  tests/Action/Bafoo.php
  tests/Action/SetObjectFieldValueActionTest.php
Labels: patch

#6072 Remove deprecation in test
  tests/Functional/Controller/DashboardActionTest.php
Labels: pedantic

#6074 Improve tests
  tests/Form/Type/AdminTypeTest.php
Labels: pedantic

#6050 Add LogicException for getter with hasser
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  src/Admin/BreadcrumbsBuilder.php
  src/Controller/CRUDController.php
  src/Route/DefaultRouteGenerator.php
  src/Route/QueryStringBuilder.php
  tests/Admin/AdminTest.php
  tests/Controller/CRUDControllerTest.php
  tests/Route/QueryStringBuilderTest.php
Labels: minor

#6070 Allow to use empty create/edit form
  src/Controller/CRUDController.php
  src/Resources/views/CRUD/base_edit_form.html.twig
  src/Resources/views/CRUD/base_show.html.twig
  tests/App/Admin/EmptyAdmin.php
  tests/App/config/services.yml
  tests/Controller/CRUDControllerTest.php
  tests/Functional/Controller/CRUDControllerTest.php
Labels: minor

#5965 Allow reuse render extra parameters
  src/Controller/CRUDController.php
Labels: minor

#6077 Fix GenerateObjectAclCommand error for symfony 3.4
  src/DependencyInjection/Compiler/ObjectAclManipulatorCompilerPass.php
  tests/DependencyInjection/Compiler/ObjectAclManipulatorCompilerPassTest.php
Labels: patch

#6085 Trigger deprecation when no value is found in list and show. Throw exception in next major.
  UPGRADE-3.x.md
  src/Admin/BaseFieldDescription.php
  src/Model/ModelManagerInterface.php
  src/Twig/Extension/SonataAdminExtension.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: minor

#6089 Bump doctrine/inflector to 1.4
  composer.json
  src/Admin/AdminHelper.php
  src/Admin/BaseFieldDescription.php
  src/Controller/CRUDController.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
Labels: minor

#6094 Fix deprecation message
  src/Admin/AbstractAdmin.php
Labels: pedantic

#5969 [Collection] initialize counter to -1 for starting items from 0
  src/Resources/public/Admin.js
Labels: patch

#6095 Improve deprecation message for legacy_twig_text_extension
  src/DependencyInjection/Configuration.php
Labels: patch

#5893 Remove calls to the deprecated trans method
  src/Resources/views/CRUD/Association/edit_many_to_many.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig
Labels: patch

#6118 Improve documentation of CallbackFilter
  docs/reference/action_list.rst
Labels: docs

#6103 Fix inline view with CKeditor field
  src/Resources/views/CRUD/Association/edit_many_to_many.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig
Labels: patch

#6114 Make consistent variables between `renderViewElement()` and `renderViewElementCompare()`
  src/Resources/views/CRUD/base_show_compare.html.twig
  src/Resources/views/CRUD/base_show_field.html.twig
  src/Twig/Extension/SonataAdminExtension.php
  tests/Fixtures/Resources/views/CRUD/custom_show_field.html.twig
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: patch

#6123 Expose field type constant and update documentation
  UPGRADE-3.x.md
  docs/reference/action_list.rst
  docs/reference/action_show.rst
  docs/reference/field_types.rst
  src/DependencyInjection/AbstractSonataAdminExtension.php
  src/Resources/views/CRUD/base_list_field.html.twig
  src/Resources/views/CRUD/display_time.html.twig
  src/Templating/TemplateRegistry.php
Labels: docs, enhancement, minor

#6113 Fix label catalogue default value for group
  docs/reference/configuration.rst
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/DependencyInjection/Configuration.php
Labels: patch
