Repository sonata-project/SonataAdminBundle, pull requests merged in 2020-02, with the labels that each got.

#5772 Warning: Illegal offset type in isset or empty
  src/Resources/views/CRUD/list_choice.html.twig
Labels: patch

#5866 refactor CRUDControllerTest to use real container instance
  tests/Controller/CRUDControllerTest.php
Labels: pedantic

#5875 Add support for symfony form help
  src/Resources/views/Form/form_admin_fields.html.twig
Labels: feature, minor

#5874 Fix wording of EqualOperatorType
  src/Form/Type/Operator/EqualOperatorType.php
Labels: minor

#5878 Deprecate sonata_help in form types
  UPGRADE-3.x.md
  docs/reference/form_help_message.rst
  src/Form/Extension/Field/Type/FormTypeFieldExtension.php
  src/Resources/views/Form/form_admin_fields.html.twig
  tests/Form/Extension/Field/Type/FormTypeFieldExtensionTest.php
Labels: minor

#5894 Use "sonata.admin.manager" tag for services implementing `ModelManagerInterface`'
  UPGRADE-3.x.md
  src/DependencyInjection/Compiler/ModelManagerCompilerPass.php
  src/DependencyInjection/SonataAdminExtension.php
  tests/App/AppKernel.php
  tests/App/config/services.yml
  tests/DependencyInjection/Compiler/ModelManagerCompilerPassTest.php
  tests/Fixtures/DoctrineBundle/Connection.php
Labels: minor

#5897 Replace TODO comments with NEXT_MAJOR
  src/Admin/AbstractAdmin.php
  src/Admin/AbstractAdminExtension.php
  src/Admin/AccessRegistryInterface.php
  src/Admin/AdminExtensionInterface.php
  src/Admin/AdminInterface.php
  src/Resources/views/Form/silex_form_div_layout.html.twig
Labels: pedantic

#5898 Remove deprecated code and NEXT_MAJOR related to templates
  src/Action/GetShortObjectDescriptionAction.php
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  src/Admin/Pool.php
  src/Controller/CRUDController.php
  src/Resources/config/core.xml
  src/Templating/TemplateRegistry.php
  src/Twig/Extension/SonataAdminExtension.php
  src/Twig/Extension/TemplateRegistryExtension.php
  tests/Action/DashboardActionTest.php
  tests/Action/GetShortObjectDescriptionActionTest.php
  tests/Action/SetObjectFieldValueActionTest.php
  tests/Admin/AdminTest.php
  tests/Admin/PoolTest.php
  tests/Controller/CRUDControllerTest.php
  tests/Templating/TemplateRegistryTest.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
  tests/Twig/Extension/TemplateRegistryExtensionTest.php
Labels: major

#5899 Address PHPUnit's warnings
  tests/Admin/AdminTest.php
  tests/Controller/CRUDControllerTest.php
  tests/Datagrid/ListMapperTest.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
  tests/Filter/FilterTest.php
  tests/Form/Type/ChoiceFieldMaskTypeTest.php
  tests/Form/Widget/FilterChoiceWidgetTest.php
  tests/Form/Widget/FormChoiceWidgetTest.php
  tests/Form/Widget/FormSonataFilterChoiceWidgetTest.php
  tests/Form/Widget/FormSonataNativeCollectionWidgetTest.php
  tests/Menu/Integration/TabMenuTest.php
Labels: pedantic

#5901 Remove BC code for Symfony 3
  src/Controller/CRUDController.php
  tests/Controller/CRUDControllerTest.php
Labels: pedantic

#5808 Add ifEnd exception
  src/Mapper/BaseGroupedMapper.php
  tests/Mapper/BaseGroupedMapperTest.php
Labels: minor

#5904 Iterate services with `getDefinitions()` instead of `getServiceIds()`
  src/DependencyInjection/Compiler/ModelManagerCompilerPass.php
  tests/DependencyInjection/Compiler/ModelManagerCompilerPassTest.php
Labels: patch

#5914 Only trigger deprecations of sonata_help when it is actually using it
  src/Resources/views/Form/form_admin_fields.html.twig
Labels: patch

#5918 Fix Regular expression in test
  tests/Datagrid/ListMapperTest.php
Labels: pedantic

#5921 Fix phpstan
  .github/workflows/qa.yml
Labels: pedantic

#5924 Fix deprecation passing more than one attribute to isGranted
  src/Security/Handler/RoleSecurityHandler.php
  tests/Security/Handler/RoleSecurityHandlerTest.php
Labels: patch
