Repository sonata-project/SonataAdminBundle, pull requests merged in 2020-08, with the labels that each got.

#6244 Add void return type declaration to test classes
  src/Model/ModelManagerInterface.php
  tests/App/Admin/EmptyAdmin.php
  tests/App/Admin/FieldDescription.php
  tests/App/Admin/FooAdmin.php
  tests/App/Admin/TranslatedAdmin.php
  tests/App/AppKernel.php
  tests/App/Datagrid/Datagrid.php
  tests/App/Datagrid/Pager.php
  tests/App/Datagrid/ProxyQuery.php
  tests/App/Model/ModelManager.php
  tests/Form/Type/Operator/StringOperatorTypeTest.php
  tests/Resources/XliffValidatorTestCase.php
  tests/Security/Handler/AclSecurityHandlerTest.php
Labels: pedantic

#6215 Deprecate help option in FieldDescription
  .phpstan/phpstan-baseline.neon
  UPGRADE-3.x.md
  docs/cookbook/recipe_image_previews.rst
  docs/reference/form_help_message.rst
  src/Admin/BaseFieldDescription.php
  src/Admin/FieldDescriptionInterface.php
  src/Form/FormMapper.php
  src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig
  src/Resources/views/CRUD/base_standard_edit_field.html.twig
  src/Resources/views/Form/form_admin_fields.html.twig
  tests/Admin/BaseFieldDescriptionTest.php
  tests/App/AppKernel.php
  tests/Functional/Controller/CRUDControllerTest.php
Labels: minor

#6238 Deprecate unused form templates
  UPGRADE-3.x.md
  src/Resources/views/CRUD/base_filter_field.html.twig
  src/Resources/views/CRUD/base_inline_edit_field.html.twig
  src/Resources/views/CRUD/base_standard_edit_field.html.twig
  src/Resources/views/CRUD/edit_array.html.twig
  src/Resources/views/CRUD/edit_boolean.html.twig
  src/Resources/views/CRUD/edit_file.html.twig
  src/Resources/views/CRUD/edit_integer.html.twig
  src/Resources/views/CRUD/edit_sonata_type_immutable_array.html.twig
  src/Resources/views/CRUD/edit_string.html.twig
  src/Resources/views/CRUD/edit_text.html.twig
Labels: minor

#6248 Return TypeGuess instead of Guess on TypeGuesserInterface::guessType
  src/Guesser/TypeGuesserChain.php
  src/Guesser/TypeGuesserInterface.php
Labels: pedantic

#6245 Infer parameter type declarations
  src/Admin/AbstractAdmin.php
  src/Admin/BaseFieldDescription.php
  src/Controller/CRUDController.php
  src/Twig/Extension/DeprecatedTextExtension.php
Labels: pedantic

#6212 Add Support for BlockBundle 4
  .phpstan/phpstan-baseline.neon
  UPGRADE-3.x.md
  composer.json
  src/Block/AdminListBlockService.php
  src/Block/AdminSearchBlockService.php
  src/Block/AdminStatsBlockService.php
Labels: minor

#6256 Allow Twig 3
  .phpstan/phpstan-baseline.neon
  composer.json
  src/SonataAdminBundle.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: minor

#6252 Added support for label_translation_parameters
  src/Resources/views/CRUD/base_list.html.twig
Labels: minor

#6264 Fix deprecation with SonataDoctrineBundle location
  composer.json
  tests/App/AppKernel.php
Labels: pedantic

#6254 Simplify routes config by following Symfony standards
  src/Resources/config/routing/sonata_admin.xml
Labels: pedantic

#6262 bump PHPStan to level 4
  .phpstan/phpstan-baseline.neon
  .phpstan/phpstan.neon.dist
  src/Action/GetShortObjectDescriptionAction.php
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  src/Admin/FieldDescriptionRegistryInterface.php
  src/Controller/CRUDController.php
  src/Datagrid/Pager.php
  src/Form/ChoiceList/ModelChoiceLoader.php
  src/Form/Extension/Field/Type/FormTypeFieldExtension.php
  src/Maker/AdminMaker.php
  src/Menu/Provider/GroupMenuProvider.php
  src/Twig/Extension/SonataAdminExtension.php
  tests/Action/GetShortObjectDescriptionActionTest.php
  tests/Admin/AdminTest.php
  tests/Controller/HelperControllerTest.php
Labels: pedantic

#6259 Narrow Filter API
  src/Filter/Filter.php
  src/Filter/FilterFactory.php
  src/Filter/FilterFactoryInterface.php
  src/Filter/FilterInterface.php
  src/Filter/Persister/FilterPersisterInterface.php
  src/Filter/Persister/SessionFilterPersister.php
  tests/Filter/FilterFactoryTest.php
  tests/Filter/FilterTest.php
  tests/Fixtures/Filter/FooFilter.php
Labels: major

#6257 Narrow Datagrid API
  phpstan-baseline.neon
  src/Datagrid/Datagrid.php
  src/Datagrid/DatagridInterface.php
  src/Datagrid/DatagridMapper.php
  src/Datagrid/ListMapper.php
  src/Datagrid/Pager.php
  src/Datagrid/PagerInterface.php
  src/Datagrid/ProxyQueryInterface.php
  src/Datagrid/SimplePager.php
  tests/App/Datagrid/Datagrid.php
  tests/App/Datagrid/Pager.php
  tests/App/Datagrid/ProxyQuery.php
  tests/Datagrid/DatagridTest.php
  tests/Search/SearchHandlerTest.php
Labels: major

#6255 Improve description of RouteCollectionInterface::actionify()
  src/Route/RouteCollectionInterface.php
Labels: pedantic

#6278 Remove oppressive language
  docs/reference/routing.rst
Labels: docs

#6283 explicitly require json extension
  composer.json
Labels: pedantic

#6281 Add @method to PagerInterface
  .phpstan/phpstan-baseline.neon
  src/Datagrid/PagerInterface.php
Labels: pedantic

#6127 Add doctrine/common 3 support
  composer.json
  src/Command/GenerateObjectAclCommand.php
  tests/Command/GenerateObjectAclCommandTest.php
Labels: minor

#6290 Fix ProxyQueryInterface return typehint
  src/Datagrid/ProxyQueryInterface.php
  tests/App/Datagrid/ProxyQuery.php
Labels: pedantic

#6292 Fix proxy query return typehint
  src/Datagrid/ProxyQueryInterface.php
  tests/App/Datagrid/ProxyQuery.php
Labels: pedantic

#6289 Remove old upgrade files
  UPGRADE-2.1.md
  UPGRADE-2.2.md
  UPGRADE-2.3.md
  UPGRADE-3.0.md
Labels: pedantic

#6277 bump PHPStan to level 5
  .phpstan/phpstan-baseline.neon
  .phpstan/phpstan.neon.dist
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  src/Admin/BaseFieldDescription.php
  src/Admin/BreadcrumbsBuilder.php
  src/Security/Handler/AclSecurityHandler.php
  src/Security/Handler/AclSecurityHandlerInterface.php
  src/Twig/Extension/StringExtension.php
  src/Util/AdminObjectAclData.php
  src/Util/AdminObjectAclManipulator.php
  tests/Admin/BreadcrumbsBuilderTest.php
  tests/Form/Widget/FormChoiceWidgetTest.php
Labels: pedantic

#6293 Add getPagerType to AdminInterface
  src/Admin/AdminInterface.php
Labels: pedantic

#6291 Deprecate getSingleScalarResult method
  UPGRADE-3.x.md
  src/Datagrid/ProxyQueryInterface.php
  tests/App/Datagrid/ProxyQuery.php
Labels: minor

#6312 Deprecate ModelManagerInterface collection-related methods
  UPGRADE-3.x.md
  src/Form/DataTransformer/ModelToIdPropertyTransformer.php
  src/Form/DataTransformer/ModelsToArrayTransformer.php
  src/Form/EventListener/MergeCollectionListener.php
  src/Model/ModelManagerInterface.php
  tests/App/Model/ModelManager.php
Labels: minor

#6271 Prevent error "Notice: Undefined index: idx" if there are no list items are selected.
  src/Controller/CRUDController.php
Labels: Needs: Tests, patch

#6322 Fix psalm build
  src/Form/DataTransformer/ModelToIdPropertyTransformer.php
  src/Form/DataTransformer/ModelsToArrayTransformer.php
Labels: pedantic

#6261 Narrow Model API
  src/Admin/AbstractAdmin.php
  src/Form/ChoiceList/ModelChoiceLoader.php
  src/Form/DataTransformer/ModelToIdPropertyTransformer.php
  src/Model/AuditManager.php
  src/Model/AuditManagerInterface.php
  src/Model/AuditReaderInterface.php
  src/Model/DatagridManagerInterface.php
  src/Model/LockInterface.php
  src/Model/ModelManagerInterface.php
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/Pager/base_links.html.twig
  tests/Admin/BaseAdminModelManagerTest.php
  tests/Admin/Extension/LockExtensionTest.php
  tests/App/Model/ModelManager.php
  tests/Controller/CRUDControllerTest.php
  tests/Form/DataTransformer/ModelToIdTransformerTest.php
  tests/Form/Type/ModelListTypeTest.php
Labels: major

#6321 Avoid to mutate original request on `CRUDController::batchAction()`
  src/Controller/CRUDController.php
  tests/Controller/CRUDControllerTest.php
Labels: patch

#6325 Fix allowing valid action names in `CRUDController::batchAction()`
  src/Controller/CRUDController.php
  tests/Controller/CRUDControllerTest.php
  tests/Fixtures/Controller/BatchAdminController.php
Labels: patch

#6330 Fix build
  tests/Security/Handler/AclSecurityHandlerTest.php
Labels: pedantic

#6336 Update docs
  docs/reference/form_types.rst
Labels: docs

#6349 Add generics to ModelManagerInterface
  src/Model/ModelManagerInterface.php
Labels: minor
