Repository sonata-project/SonataAdminBundle, pull requests merged in 2020-07, with the labels that each got.

#6161 PHPStan Level 2
  .github/workflows/qa.yaml
  .phpstan/phpstan-baseline.neon
  .phpstan/phpstan.neon.dist
  .phpstan/stubs/Exporter.file
  .phpstan/stubs/MetadataInterface.file
  .phpstan/stubs/TextExtension.file
  phpstan-baseline.neon
  phpstan.neon.dist
  src/Action/SetObjectFieldValueAction.php
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  src/Admin/FieldDescriptionInterface.php
  src/Command/ExplainAdminCommand.php
  src/Command/QuestionableCommand.php
  src/Controller/CRUDController.php
  src/Datagrid/DatagridMapper.php
  src/Datagrid/ListMapper.php
  src/Datagrid/PagerInterface.php
  src/DependencyInjection/Configuration.php
  src/EventListener/AssetsInstallCommandListener.php
  src/Form/DataTransformer/ModelsToArrayTransformer.php
  src/Form/FormMapper.php
  src/Maker/AdminMaker.php
  src/Security/Handler/AclSecurityHandler.php
  src/Show/ShowMapper.php
  src/Util/AdminAclManipulator.php
  src/Util/AdminObjectAclData.php
  tests/Admin/AdminTest.php
  tests/Command/ExplainAdminCommandTest.php
  tests/Controller/CRUDControllerTest.php
  tests/Security/Handler/AclSecurityHandlerTest.php
  tests/Util/AdminObjectAclDataTest.php
Labels: pedantic

#6040 Add AdminExtractor
  src/DependencyInjection/SonataAdminExtension.php
  src/Resources/config/core.xml
  src/Translator/Extractor/AdminExtractor.php
  src/Translator/Extractor/JMSTranslatorBundle/AdminExtractor.php
  tests/DependencyInjection/SonataAdminExtensionTest.php
  tests/Translator/Extractor/AdminExtractorTest.php
  tests/Translator/Extractor/JMSTranslatorBundle/AdminExtractorTest.php
Labels: minor

#6183 Fix form one-to-many tabs translations
  src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig
Labels: patch

#5799 Update RetrieveAutocompleteItemsAction.php
  src/Action/RetrieveAutocompleteItemsAction.php
Labels: patch

#6187 Process deprecation of FieldDescriptionInterface::getTargetEntity()
  src/Action/RetrieveAutocompleteItemsAction.php
  src/Action/SetObjectFieldValueAction.php
  src/Admin/AbstractAdmin.php
  tests/Action/RetrieveAutocompleteItemsActionTest.php
  tests/Action/SetObjectFieldValueActionTest.php
  tests/App/Admin/FieldDescription.php
  tests/Controller/HelperControllerTest.php
  tests/Fixtures/Admin/FieldDescription.php
Labels: patch

#6184 Avoid duplicate informations in documentation
  docs/reference/action_list.rst
  docs/reference/field_types.rst
Labels: docs

#6192 Improve tests fixtures
  tests/App/Admin/FooAdmin.php
  tests/App/Builder/DatagridBuilder.php
  tests/App/Builder/FormContractor.php
  tests/App/Datagrid/Datagrid.php
  tests/App/Datagrid/Pager.php
  tests/App/Model/Foo.php
  tests/App/Model/FooRepository.php
  tests/App/Model/ModelManager.php
  tests/Fixtures/Admin/FieldDescription.php
  tests/Fixtures/Admin/PostAdmin.php
  tests/Fixtures/Bundle/DemoAdminBundle.php
  tests/Fixtures/Controller/AbstractFooAdminController.php
  tests/Fixtures/Controller/BarAdminController.php
  tests/Fixtures/Controller/FooAdminController.php
  tests/Fixtures/Entity/Form/FooEntity.php
  tests/Fixtures/TestExtension.php
Labels: pedantic

#6193 Add default value for array properties
  src/Action/DashboardAction.php
  src/Admin/BaseFieldDescription.php
  src/Admin/Pool.php
  src/Datagrid/Datagrid.php
  src/Form/Extension/Field/Type/FormTypeFieldExtension.php
  src/Object/Metadata.php
  src/Security/Handler/AclSecurityHandler.php
  src/Security/Handler/RoleSecurityHandler.php
  src/Util/AdminObjectAclData.php
Labels: bug

#6195 Fix design of validation message error for collection
  src/Resources/views/CRUD/Association/edit_many_to_many.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig
Labels: patch

#6202 Remove custom view doc
  docs/cookbook/recipe_custom_view.rst
  docs/index.rst
Labels: docs

#6203 Prepare 3.72
  CHANGELOG.md
  UPGRADE-3.x.md
  src/Admin/AdminHelper.php
  src/Form/Type/AdminType.php
  src/Resources/config/core.xml
  src/Translator/Extractor/JMSTranslatorBundle/AdminExtractor.php
  tests/Admin/AdminHelperTest.php
Labels: pedantic

#6205 Fix phpdoc
  src/Builder/FormContractorInterface.php
Labels: pedantic

#6112 Menu label translation
  docs/reference/advanced_configuration.rst
  src/Resources/views/Menu/sonata_menu.html.twig
Labels: minor

#6208 Use FieldDescriptionInterface::getTargetModel if exists
  src/Action/RetrieveAutocompleteItemsAction.php
  src/Action/SetObjectFieldValueAction.php
  src/Admin/AbstractAdmin.php
Labels: patch

#6206 Added support for help_translation_parameters and label_translation_parameters
  src/Resources/views/Form/form_admin_fields.html.twig
Labels: patch

#6216 Added missing argument for sonata.admin.block.search_result
  src/Resources/config/block.xml
  tests/Block/AdminSearchBlockServiceTest.php
Labels: patch

#6213 Improve Next_major comment
  src/Admin/AbstractAdmin.php
Labels: pedantic

#6223 Edit many script error without subclass gives an exception
  src/Resources/views/CRUD/Association/edit_many_script.html.twig
Labels: patch

#6201 Fix links in documentation
  docs/cookbook/recipe_file_uploads.rst
  docs/cookbook/recipe_knp_menu.rst
  docs/cookbook/recipe_lock_protection.rst
  docs/cookbook/recipe_select2.rst
  docs/cookbook/recipe_sonata_admin_without_user_bundle.rst
  docs/cookbook/recipe_sortable_sonata_type_model.rst
  docs/cookbook/recipe_workflow_integration.rst
  docs/getting_started/creating_an_admin.rst
  docs/getting_started/installation.rst
  docs/getting_started/the_form_view.rst
  docs/index.rst
  docs/reference/action_list.rst
  docs/reference/advanced_configuration.rst
  docs/reference/architecture.rst
  docs/reference/conditional_validation.rst
  docs/reference/field_types.rst
  docs/reference/form_types.rst
  docs/reference/security.rst
  docs/reference/troubleshooting.rst
Labels: docs

#6167 Show and edit date in the same timezone
  src/Action/SetObjectFieldValueAction.php
  src/Resources/views/CRUD/base_list_field.html.twig
  tests/Action/Bafoo.php
  tests/Action/SetObjectFieldValueActionTest.php
Labels: patch

#6144 Can't use datetime field type as editable
  src/Action/SetObjectFieldValueAction.php
  src/Resources/views/CRUD/base_list_field.html.twig
  tests/Action/SetObjectFieldValueActionTest.php
Labels: minor

#6200 Add support for arrays containing additional database values in list views
  docs/.doctor-rst.yaml
  docs/reference/action_list.rst
  src/Twig/Extension/SonataAdminExtension.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: minor

#6234 Deprecate getParentFieldDescription from ModelManagerInterface
  UPGRADE-3.x.md
  src/Model/ModelManagerInterface.php
Labels: minor

#6235 Replace 3.x to avoid test failure
  docs/reference/action_list.rst
  src/Model/ModelManagerInterface.php
  src/Twig/Extension/SonataAdminExtension.php
Labels: pedantic

#6230 Update required dependancies in install doc after SonataCoreBundle became optionnal #6173
  docs/getting_started/installation.rst
Labels: docs, pedantic

#6224 Set subject on admin instance when extracting translatable strings
  src/Translator/Extractor/AdminExtractor.php
  tests/Translator/Extractor/AdminExtractorTest.php
Labels: patch

#6236 Improve child admin documentation wrt URL generation
  docs/reference/child_admin.rst
Labels: docs, pedantic

#6237 Add functional test to AdminExtractor
  tests/App/Admin/TranslatedAdmin.php
  tests/App/AppKernel.php
  tests/App/Model/ModelManager.php
  tests/App/Model/Translated.php
  tests/App/config/services.yml
  tests/Functional/Translator/Extractor/AdminExtractorTest.php
Labels: pedantic
