Repository sonata-project/SonataAdminBundle, pull requests merged in 2020-10, with the labels that each got.

#6441 Fix: Add return to fulfill return typehint
  docs/reference/action_list.rst
Labels: docs, hacktoberfest

#6442 Use extra variable and add spacing for readability
  docs/reference/action_list.rst
Labels: docs

#6443 Fix: Wrong documentation
  docs/reference/action_list.rst
Labels: bug, docs

#6448 Enhancement: Move PHPStan config files to the root folder
  phpstan-baseline.neon
  phpstan.neon.dist
Labels: pedantic

#6028 Refactoring ExtensionCompilerPass
  src/DependencyInjection/Compiler/ExtensionCompilerPass.php
Labels: pedantic

#6267 Narrow Form and Mapper API
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  src/Form/ChoiceList/ModelChoiceLoader.php
  src/Form/DataTransformer/ArrayToModelTransformer.php
  src/Form/DataTransformer/ModelToIdPropertyTransformer.php
  src/Form/DataTransformer/ModelToIdTransformer.php
  src/Form/DataTransformer/ModelsToArrayTransformer.php
  src/Form/EventListener/MergeCollectionListener.php
  src/Form/Extension/ChoiceTypeExtension.php
  src/Form/Extension/Field/Type/FormTypeFieldExtension.php
  src/Form/Extension/Field/Type/MopaCompatibilityTypeFieldExtension.php
  src/Form/FormMapper.php
  src/Form/Type/AclMatrixType.php
  src/Form/Type/AdminType.php
  src/Form/Type/ChoiceFieldMaskType.php
  src/Form/Type/CollectionType.php
  src/Form/Type/Filter/ChoiceType.php
  src/Form/Type/Filter/DateRangeType.php
  src/Form/Type/Filter/DateTimeRangeType.php
  src/Form/Type/Filter/DateTimeType.php
  src/Form/Type/Filter/DateType.php
  src/Form/Type/Filter/DefaultType.php
  src/Form/Type/Filter/NumberType.php
  src/Form/Type/ModelAutocompleteType.php
  src/Form/Type/ModelHiddenType.php
  src/Form/Type/ModelListType.php
  src/Form/Type/ModelReferenceType.php
  src/Form/Type/ModelType.php
  src/Form/Type/Operator/ContainsOperatorType.php
  src/Form/Type/Operator/DateOperatorType.php
  src/Form/Type/Operator/DateRangeOperatorType.php
  src/Form/Type/Operator/EqualOperatorType.php
  src/Form/Type/Operator/NumberOperatorType.php
  src/Form/Type/Operator/StringOperatorType.php
  src/Mapper/BaseGroupedMapper.php
  tests/Form/ChoiceList/ModelChoiceLoaderTest.php
  tests/Form/DataTransformer/ModelToIdPropertyTransformerTest.php
  tests/Form/DataTransformer/ModelToIdTransformerTest.php
  tests/Form/Extension/ChoiceTypeExtensionTest.php
  tests/Form/Extension/Field/Type/FormTypeFieldExtensionTest.php
  tests/Form/Type/ModelTypeTest.php
Labels: hacktoberfest, major

#6456 Add next major comment about typehint
  src/Mapper/BaseMapper.php
Labels: pedantic

#6315 Replace multiple DB transactions with a single one
  src/Form/DataTransformer/ModelToIdPropertyTransformer.php
  src/Form/DataTransformer/ModelsToArrayTransformer.php
  src/Util/TraversableToCollection.php
  tests/Form/DataTransformer/ModelToIdPropertyTransformerTest.php
  tests/Form/DataTransformer/ModelsToArrayTransformerTest.php
  tests/Util/TraversableToCollectionTest.php
Labels: minor

#6475 Deprecate Pool::getContainer method
  UPGRADE-3.x.md
  docs/cookbook/recipe_image_previews.rst
  src/Admin/AbstractAdmin.php
  src/Admin/Pool.php
  src/Mapper/BaseGroupedMapper.php
  tests/Admin/PoolTest.php
  tests/Mapper/BaseGroupedMapperTest.php
Labels: minor

#6420 Add deprecation when injecting registry in command
  phpstan-baseline.neon
  src/Command/GenerateObjectAclCommand.php
  src/Resources/config/commands.php
  tests/Command/DeprecatedGenerateObjectAclCommandTest.php
  tests/Command/GenerateObjectAclCommandTest.php
Labels: minor

#6462 Narrow allowed types for ids passed to `find()` and `addIdentifiersToQuery()` in `ModelManagerInterface`
  src/Model/ModelManagerInterface.php
Labels: pedantic

#6496 Add phpdoc type hints
  src/Show/ShowMapper.php
  src/Translator/Extractor/AdminExtractor.php
  src/Twig/Extension/SonataAdminExtension.php
  src/Twig/Extension/TemplateRegistryExtension.php
  src/Twig/GlobalVariables.php
Labels: pedantic

#6480 Deprecate acl_user_manager without implementing AdminAclUserManagerInterface
  UPGRADE-3.x.md
  docs/reference/security.rst
  src/Controller/CRUDController.php
  src/DependencyInjection/Compiler/CheckAclUserManagerCompilerPass.php
  src/DependencyInjection/SonataAdminExtension.php
  src/Util/AdminAclUserManagerInterface.php
  tests/Controller/CRUDControllerTest.php
  tests/DependencyInjection/Compiler/CheckAclUserManagerCompilerPassTest.php
Labels: minor

#6498 Fix \Knp\Menu\MenuItem @Label issue
  src/Resources/views/Core/tab_menu_template.html.twig
  src/Resources/views/Menu/sonata_menu.html.twig
  src/Resources/views/standard_layout.html.twig
  tests/App/Admin/FooAdmin.php
Labels: patch

#6497 Set defaults filters without request
  src/Admin/AbstractAdmin.php
  tests/Admin/AdminTest.php
Labels: minor

#6320 Fix return value from `CRUDController::getRestMethod()` respecting `Request::getHttpMethodParameterOverride()`
  UPGRADE-3.x.md
  src/Controller/CRUDController.php
  tests/Controller/CRUDControllerTest.php
Labels: minor

#6507 Handle item without admin key
  src/Admin/Pool.php
  tests/Admin/PoolTest.php
Labels: patch

#6407 Add typehint to command
  src/Command/GenerateObjectAclCommand.php
  src/Command/QuestionableCommand.php
  src/Command/Validators.php
  src/Resources/config/commands.php
Labels: major

#6500 Add link to go to first page if there is result with a lower offset
  src/Datagrid/Pager.php
  src/Resources/translations/SonataAdminBundle.ar.xliff
  src/Resources/translations/SonataAdminBundle.bg.xliff
  src/Resources/translations/SonataAdminBundle.ca.xliff
  src/Resources/translations/SonataAdminBundle.cs.xliff
  src/Resources/translations/SonataAdminBundle.de.xliff
  src/Resources/translations/SonataAdminBundle.en.xliff
  src/Resources/translations/SonataAdminBundle.es.xliff
  src/Resources/translations/SonataAdminBundle.eu.xliff
  src/Resources/translations/SonataAdminBundle.fa.xliff
  src/Resources/translations/SonataAdminBundle.fr.xliff
  src/Resources/translations/SonataAdminBundle.hr.xliff
  src/Resources/translations/SonataAdminBundle.hu.xliff
  src/Resources/translations/SonataAdminBundle.it.xliff
  src/Resources/translations/SonataAdminBundle.ja.xliff
  src/Resources/translations/SonataAdminBundle.lb.xliff
  src/Resources/translations/SonataAdminBundle.lt.xliff
  src/Resources/translations/SonataAdminBundle.lv.xliff
  src/Resources/translations/SonataAdminBundle.nl.xliff
  src/Resources/translations/SonataAdminBundle.no.xliff
  src/Resources/translations/SonataAdminBundle.pl.xliff
  src/Resources/translations/SonataAdminBundle.pt.xliff
  src/Resources/translations/SonataAdminBundle.pt_BR.xliff
  src/Resources/translations/SonataAdminBundle.ro.xliff
  src/Resources/translations/SonataAdminBundle.ru.xliff
  src/Resources/translations/SonataAdminBundle.sk.xliff
  src/Resources/translations/SonataAdminBundle.sl.xliff
  src/Resources/translations/SonataAdminBundle.sv_SE.xliff
  src/Resources/translations/SonataAdminBundle.tr.xliff
  src/Resources/translations/SonataAdminBundle.uk.xliff
  src/Resources/translations/SonataAdminBundle.zh_CN.xliff
  src/Resources/translations/SonataAdminBundle.zh_HK.xliff
  src/Resources/views/CRUD/base_list.html.twig
Labels: minor

#6486 Improve error message in case of multiple admins for same entity
  src/Admin/AbstractAdmin.php
  src/Admin/Pool.php
  tests/Admin/PoolTest.php
Labels: minor

#6510 Deprecate `Validators::validateEntityName()`
  UPGRADE-3.x.md
  src/Command/Validators.php
  tests/Command/ValidatorsTest.php
Labels: minor

#6509 Avoid to pass empty array as argument 3 for implementations of `ModelManagerInterface::addIdentifiersToQuery()`
  src/Form/DataTransformer/ModelsToArrayTransformer.php
  tests/Form/DataTransformer/ModelsToArrayTransformerTest.php
Labels: patch

#6487 [Translator] Add param & return type hints to all files in the Translator dir
  src/Translator/BCLabelTranslatorStrategy.php
  src/Translator/Extractor/AdminExtractor.php
  src/Translator/FormLabelTranslatorStrategy.php
  src/Translator/LabelTranslatorStrategyInterface.php
  src/Translator/NativeLabelTranslatorStrategy.php
  src/Translator/NoopLabelTranslatorStrategy.php
  src/Translator/UnderscoreLabelTranslatorStrategy.php
  tests/Admin/AdminTest.php
Labels: major

#6489 [Twig] Add param & return type hints to all files in the Twig dir
  src/Twig/Extension/SonataAdminExtension.php
  src/Twig/Extension/TemplateRegistryExtension.php
  src/Twig/GlobalVariables.php
Labels: major

#6511 Remove some NEXT_MAJOR comments
  src/Controller/CRUDController.php
  src/Datagrid/ProxyQueryInterface.php
  src/DependencyInjection/Compiler/CheckAclUserManagerCompilerPass.php
  src/DependencyInjection/Compiler/ExtensionCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataAdminExtension.php
  src/Form/DataTransformerResolver.php
  tests/App/Datagrid/ProxyQuery.php
  tests/Controller/CRUDControllerTest.php
  tests/DependencyInjection/Compiler/CheckAclUserManagerCompilerPassTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/Filter/FilterFactoryTest.php
Labels: major

#6476 Add compatibility with Symfony 5
  composer.json
  phpstan-baseline.neon
  src/Controller/CRUDController.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/Event/AdminEventExtension.php
  src/Menu/MenuBuilder.php
  src/Resources/config/core.php
  src/Resources/config/security.php
  src/Route/RoutesCacheWarmUp.php
  tests/Admin/Extension/LockExtensionTest.php
  tests/App/AppKernel.php
  tests/Controller/CRUDControllerTest.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
  tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php
  tests/Event/AdminEventExtensionTest.php
  tests/Form/Widget/FormSonataFilterChoiceWidgetTest.php
  tests/Menu/MenuBuilderTest.php
Labels: major

#6515 Deprecate FilterInterface::filter method
  src/Filter/FilterInterface.php
  tests/Fixtures/Filter/FooFilter.php
Labels: minor

#6525 Restore missing ellipsis in truncated words
  src/Resources/views/CRUD/base_edit.html.twig
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/CRUD/base_show.html.twig
  src/Resources/views/standard_layout.html.twig
Labels: patch

#6438 Access to CollectionType options in AdminType
  composer.json
  phpstan-baseline.neon
  src/Builder/FormContractorInterface.php
  src/Form/FormMapper.php
  src/Form/Type/AdminType.php
  tests/Form/FormMapperTest.php
  tests/Form/Type/AdminTypeTest.php
Labels: patch

#6530 Add scroll to filter dropdown
  src/Resources/public/css/styles.css
  src/Resources/views/CRUD/base_list.html.twig
Labels: patch

#6532 Fix DI config for AdminHelper
  src/Resources/config/core.php
Labels: major

#6542 Ignore PHPStan errors in Pager::next() and Pager::rewind()
  phpstan-baseline.neon
Labels: pedantic

#6533 [Util] Add type hints to files in Util directory
  src/Util/AdminAclManipulator.php
  src/Util/AdminAclManipulatorInterface.php
  src/Util/AdminObjectAclData.php
  src/Util/AdminObjectAclManipulator.php
  src/Util/FormBuilderIterator.php
  src/Util/FormViewIterator.php
  src/Util/ObjectAclManipulator.php
  src/Util/ObjectAclManipulatorInterface.php
Labels: major

#6545 Add phpstan plugin
  composer.json
Labels: pedantic

#6555 Pedantic changes in `AddDependencyCallsCompilerPass::fixTemplates()`
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
Labels: pedantic

#6463 Add DataSourceInterface
  UPGRADE-3.x.md
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/Exporter/DataSourceInterface.php
  src/Model/ModelManagerInterface.php
  tests/Admin/AdminTest.php
  tests/App/Exporter/DataSource.php
  tests/App/config/services.yml
Labels: minor
