Repository sonata-project/SonataAdminBundle, pull requests merged in 2020-09, with the labels that each got.

#6311 Restrict param type of AdminInterface identifiers methods
  src/Action/AppendFormFieldElementAction.php
  src/Action/GetShortObjectDescriptionAction.php
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  src/Admin/UrlGeneratorInterface.php
  src/Resources/views/CRUD/Association/edit_many_to_one.html.twig
  tests/Action/GetShortObjectDescriptionActionTest.php
  tests/Admin/AdminTest.php
  tests/App/Datagrid/Pager.php
  tests/Controller/HelperControllerTest.php
Labels: minor

#6363 Allow symfony security-csrf and asset 5.1
  composer.json
Labels: minor

#6284 Move internal configuration to PHP
  composer.json
  src/DependencyInjection/SonataAdminExtension.php
  src/Export/Exporter.php
  src/Resources/config/actions.php
  src/Resources/config/actions.xml
  src/Resources/config/block.php
  src/Resources/config/block.xml
  src/Resources/config/commands.php
  src/Resources/config/commands.xml
  src/Resources/config/core.php
  src/Resources/config/core.xml
  src/Resources/config/event_listener.php
  src/Resources/config/event_listener.xml
  src/Resources/config/exporter.php
  src/Resources/config/exporter.xml
  src/Resources/config/form_types.php
  src/Resources/config/form_types.xml
  src/Resources/config/makers.php
  src/Resources/config/makers.xml
  src/Resources/config/menu.php
  src/Resources/config/menu.xml
  src/Resources/config/route.php
  src/Resources/config/route.xml
  src/Resources/config/security.php
  src/Resources/config/security.xml
  src/Resources/config/twig.php
  src/Resources/config/twig.xml
  src/Resources/config/twig_string.php
  src/Resources/config/twig_string.xml
  src/Resources/config/validator.php
  src/Resources/config/validator.xml
Labels: pedantic

#6369 Allow symfony config, dependency-injection and routing 5.1
  composer.json
  src/DependencyInjection/Configuration.php
  src/Resources/config/commands.php
  src/Resources/config/core.php
  src/Resources/config/menu.php
  src/Resources/config/twig_string.php
  src/Util/BCDeprecationParameters.php
Labels: minor

#6364 Prevent addFormFieldDescription if field role no granted
  src/Form/FormMapper.php
  tests/Form/FormMapperTest.php
Labels: patch

#6348 Add AbstractAdmin::configureExportFields extension point
  docs/reference/action_export.rst
  src/Admin/AbstractAdmin.php
Labels: feature, minor

#6362 Add support for symfony/form 5.1
  composer.json
  src/Form/Extension/ChoiceTypeExtension.php
  src/Form/Extension/Field/Type/FormTypeFieldExtension.php
  src/Form/Extension/Field/Type/MopaCompatibilityTypeFieldExtension.php
Labels: major

#6304 Remove some NEXT_MAJOR comment
  src/Action/GetShortObjectDescriptionAction.php
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  src/Admin/UrlGeneratorInterface.php
  tests/Action/GetShortObjectDescriptionActionTest.php
  tests/Admin/AdminTest.php
Labels: major

#5937 Data Transformers in list fields editable
  docs/reference/action_list.rst
  src/Action/SetObjectFieldValueAction.php
  src/Controller/HelperController.php
  src/Form/DataTransformer/BooleanToStringTransformer.php
  src/Form/DataTransformerResolver.php
  src/Form/DataTransformerResolverInterface.php
  src/Resources/config/actions.php
  src/Resources/config/core.php
  src/Resources/config/form_types.php
  tests/Action/Bar.php
  tests/Action/Baz.php
  tests/Action/Foo.php
  tests/Action/SetObjectFieldValueActionTest.php
  tests/Controller/HelperControllerTest.php
  tests/Form/DataTransformer/BooleanToStringTransformerTest.php
  tests/Form/DataTransformerResolverTest.php
Labels: minor

#6386 Deprecate ORM related functions on ProxyQueryInterface
  UPGRADE-3.x.md
  src/Datagrid/ProxyQueryInterface.php
  tests/App/Datagrid/ProxyQuery.php
Labels: minor

#6381 Add ModelManagerInterface::supportsQuery
  src/Form/ChoiceList/ModelChoiceLoader.php
  src/Model/ModelManagerInterface.php
  tests/App/Model/ModelManager.php
  tests/Form/ChoiceList/ModelChoiceLoaderTest.php
Labels: minor

#6400 Add some phpdoc about exceptions
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
Labels: pedantic

#6405 Add missing typehint for actions
  src/Action/SetObjectFieldValueAction.php
Labels: major

#6412 Prevent deprecation notice in constructor of MergeCollectionListener
  src/Form/Type/ModelType.php
Labels: patch

#6413 Deprecate using shortcut notation for user_model in favor of FQCN
  UPGRADE-3.x.md
  src/Command/GenerateObjectAclCommand.php
  src/Resources/config/commands.php
  tests/Command/GenerateObjectAclCommandTest.php
Labels: minor

#6401 Fix inline table collection translation domain
  src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig
Labels: patch

#6414 Fix calls to deprecated methods
  src/Resources/config/twig.php
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/Pager/base_links.html.twig
  src/Twig/Extension/PaginationExtension.php
  tests/App/Admin/FooAdmin.php
  tests/App/Model/ModelManager.php
  tests/Twig/Extension/PaginationExtensionTest.php
Labels: patch

#6422 Improve mock usage
  tests/Action/AppendFormFieldElementActionTest.php
  tests/Action/RetrieveAutocompleteItemsActionTest.php
  tests/Action/RetrieveFormFieldElementActionTest.php
  tests/Admin/AdminTest.php
  tests/Admin/BreadcrumbsBuilderTest.php
  tests/Controller/HelperControllerTest.php
  tests/Filter/Persister/SessionFilterPersisterTest.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
  tests/Util/ObjectAclManipulatorTest.php
Labels: pedantic

#6424 Allow null as value to `AdminInterface::toString()` until next major
  src/Admin/AdminInterface.php
Labels: pedantic

#6429 Prevent deprecation notice when AdminInterface.isCurrentChild is implemented
  src/Admin/AbstractAdmin.php
  tests/Admin/AdminTest.php
Labels: patch

#6428 Replace mocks of ContainerInterface by Container
  tests/Action/SetObjectFieldValueActionTest.php
  tests/Admin/BreadcrumbsBuilderTest.php
  tests/Controller/HelperControllerTest.php
  tests/Filter/FilterFactoryTest.php
  tests/Form/Extension/ChoiceTypeExtensionTest.php
  tests/Mapper/BaseGroupedMapperTest.php
  tests/Model/AuditManagerTest.php
  tests/Route/AdminPoolLoaderTest.php
  tests/Translator/Extractor/JMSTranslatorBundle/AdminExtractorTest.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
  tests/Twig/Extension/TemplateRegistryExtensionTest.php
  tests/Twig/GlobalVariablesTest.php
Labels: pedantic

#6350 Keep support for a null groupItem label
  src/DependencyInjection/Configuration.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
  tests/DependencyInjection/ConfigurationTest.php
Labels: patch
