Repository sonata-project/SonataAdminBundle, pull requests merged in 2020-01, with the labels that each got.

#5796 actualize docs
  docs/reference/child_admin.rst
Labels: docs

#5773 Multiple editable field should be real multiple
  docs/reference/action_list.rst
  src/Resources/views/CRUD/base_list_field.html.twig
  tests/Action/SetObjectFieldValueActionTest.php
  tests/Action/StatusMultiple.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: minor

#5817 Require secure versions of symfony/http-foundation
  composer.json
Labels: pedantic

#5818 Add some smoke testing
  composer.json
  src/Builder/FormContractorInterface.php
  tests/App/Admin/FieldDescription.php
  tests/App/Admin/FooAdmin.php
  tests/App/AppKernel.php
  tests/App/Builder/DatagridBuilder.php
  tests/App/Builder/FormContractor.php
  tests/App/Builder/ListBuilder.php
  tests/App/Builder/ShowBuilder.php
  tests/App/Datagrid/Datagrid.php
  tests/App/Datagrid/Pager.php
  tests/App/Datagrid/ProxyQuery.php
  tests/App/Model/Foo.php
  tests/App/Model/FooRepository.php
  tests/App/Model/ModelManager.php
  tests/App/config/routes.yml
  tests/App/config/services.yml
  tests/Functional/Controller/CRUDControllerTest.php
  tests/Functional/Controller/DashboardActionTest.php
Labels: pedantic

#5327 Toggle edit button after operations add/list/remove
  src/Resources/views/CRUD/Association/edit_many_script.html.twig
Labels: minor

#5804 Add OperatorType
  src/Form/Type/Filter/ChoiceType.php
  src/Form/Type/Filter/DateRangeType.php
  src/Form/Type/Filter/DateTimeRangeType.php
  src/Form/Type/Filter/DateTimeType.php
  src/Form/Type/Filter/DateType.php
  src/Form/Type/Filter/NumberType.php
  src/Form/Type/Operator/ContainsOperatorType.php
  src/Form/Type/Operator/DateOperatorType.php
  src/Form/Type/Operator/DateRangeOperatorType.php
  src/Form/Type/Operator/EqualOperatorType.php
  src/Form/Type/Operator/NumberOperatorType.php
  tests/Form/Widget/FormSonataFilterChoiceWidgetTest.php
Labels: minor

#5800 Fix help messages not showing up in one to many inline tables.
  src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig
Labels: patch

#5821 minimumResultsForSearch and maximumSelectionSize select2 options are configurable
  src/Resources/public/Admin.js
Labels: minor

#5810 [docs] list date/datetime timezone option
  docs/reference/action_list.rst
Labels: docs

#5827 5826 - Use constant for Request methods and Response http status codes
  src/Action/RetrieveAutocompleteItemsAction.php
  src/Action/SetObjectFieldValueAction.php
  src/Controller/CRUDController.php
  tests/Action/AppendFormFieldElementActionTest.php
  tests/Action/RetrieveAutocompleteItemsActionTest.php
  tests/Action/RetrieveFormFieldElementActionTest.php
  tests/Action/SetObjectFieldValueActionTest.php
  tests/Block/AdminSearchBlockServiceTest.php
  tests/Controller/CRUDControllerTest.php
  tests/Controller/HelperControllerTest.php
  tests/Functional/Controller/CRUDControllerTest.php
  tests/Functional/Controller/DashboardActionTest.php
  tests/Route/RouteCollectionTest.php
Labels: pedantic

#5830 3.57.0
  CHANGELOG.md
  src/Filter/FilterFactory.php
  src/Form/Type/Filter/ChoiceType.php
  src/Form/Type/Filter/DateRangeType.php
  src/Form/Type/Filter/DateTimeRangeType.php
  src/Form/Type/Filter/DateTimeType.php
  src/Form/Type/Filter/DateType.php
  src/Form/Type/Filter/NumberType.php
Labels: minor

#5841 Revert to trully unique uniqid
  src/Admin/AbstractAdmin.php
  tests/Admin/AdminTest.php
Labels: patch

#5839 Remove duplicated default templates
  src/DependencyInjection/SonataAdminExtension.php
  tests/DependencyInjection/SonataAdminExtensionTest.php
Labels: pedantic

#5849 Make filter alias optional
  src/DependencyInjection/Compiler/AddFilterTypeCompilerPass.php
  tests/DependencyInjection/Compiler/AddFilterTypeCompilerPassTest.php
Labels: patch

#5853 Add stale workflow
  .github/workflows/stale.yml
Labels: pedantic
