Repository sonata-project/SonataAdminBundle, pull requests merged in 2020-12, with the labels that each got.

#6638 Create PropertyAccessor through builder
  src/Form/Type/AdminType.php
Labels: pedantic

#6631 Add data source in configuration and documentation
  docs/cookbook/recipe_overwrite_admin_configuration.rst
  docs/reference/advanced_configuration.rst
  docs/reference/architecture.rst
  docs/reference/configuration.rst
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/DependencyInjection/Configuration.php
  tests/DependencyInjection/ConfigurationTest.php
Labels: docs, minor

#6559 Removed alias from ModelManagerInterface::createQuery
  UPGRADE-3.x.md
  src/Model/ModelManagerInterface.php
Labels: minor

#6633 [3.x] Add validator related deprecation notices
  UPGRADE-3.x.md
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/DependencyInjection/Configuration.php
  tests/Admin/AdminTest.php
Labels: minor

#6648 Deprecate mapping setters from FieldDescriptionInterface
  UPGRADE-3.x.md
  src/Admin/BaseFieldDescription.php
  src/Admin/FieldDescriptionInterface.php
  src/Builder/BuilderInterface.php
  tests/Admin/BaseFieldDescriptionTest.php
  tests/Fixtures/Admin/FieldDescription.php
Labels: minor

#6640 Introduce SonataConfiguration class
  UPGRADE-3.x.md
  src/Admin/Pool.php
  src/DependencyInjection/Compiler/GlobalVariablesCompilerPass.php
  src/DependencyInjection/SonataAdminExtension.php
  src/Resources/config/core.php
  src/Resources/config/twig.php
  src/Resources/views/Block/block_admin_list.html.twig
  src/Resources/views/CRUD/base_acl.html.twig
  src/Resources/views/CRUD/base_acl_macro.html.twig
  src/Resources/views/CRUD/base_edit_form.html.twig
  src/Resources/views/CRUD/list_outer_rows_mosaic.html.twig
  src/Resources/views/Core/add_block.html.twig
  src/Resources/views/Core/dashboard.html.twig
  src/Resources/views/Core/search.html.twig
  src/Resources/views/Menu/sonata_menu.html.twig
  src/Resources/views/standard_layout.html.twig
  src/SonataConfiguration.php
  src/Twig/Extension/GroupExtension.php
  src/Twig/GlobalVariables.php
  tests/Admin/PoolTest.php
  tests/SonataConfigurationTest.php
  tests/Twig/Extension/GroupExtensionTest.php
  tests/Twig/GlobalVariablesTest.php
Labels: minor

#6656 Add psalm generics to the object returned by the form
  src/Controller/CRUDController.php
Labels: minor

#6657 Add phpdoc to abstract methods
  src/Admin/BaseFieldDescription.php
Labels: major, pedantic

#6651 Add support for global admin extensions via config
  docs/reference/configuration.rst
  docs/reference/extensions.rst
  psalm-baseline.xml
  src/DependencyInjection/Compiler/ExtensionCompilerPass.php
  src/DependencyInjection/Configuration.php
  tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php
Labels: Needs: Documentation, feature, minor

#6660 Fix trigger_error messages
  src/Admin/Pool.php
  tests/Admin/PoolTest.php
Labels: pedantic

#6662 Fix incorrect object passed to the view when rendering the history compare action
  src/Resources/views/CRUD/base_show_field.html.twig
  src/Twig/Extension/SonataAdminExtension.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: patch

#6666 Bump to 3.83
  UPGRADE-3.x.md
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  src/Admin/BaseFieldDescription.php
  src/Admin/FieldDescriptionInterface.php
  src/Admin/Pool.php
  src/Twig/GlobalVariables.php
  tests/Admin/AdminTest.php
  tests/Admin/BaseFieldDescriptionTest.php
  tests/Admin/PoolTest.php
Labels: pedantic

#6665 Mute deprecation
  src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig
Labels: patch

#6654 Deprecate AbstractFilter value property
  UPGRADE-3.x.md
  src/Filter/Filter.php
  tests/Filter/FilterTest.php
  tests/Fixtures/Filter/FooFilter.php
Labels: minor

#6675 Disable sorting for an associated_property callable
  src/Datagrid/ListMapper.php
  tests/Datagrid/ListMapperTest.php
Labels: patch

#6681 Refactor AssetsInstallCommandListener
  src/EventListener/AssetsInstallCommandListener.php
Labels: pedantic

#6674 Test sonata configuration options
  tests/DependencyInjection/SonataAdminExtensionTest.php
Labels: pedantic

#6690 test default sking with sonata configuration
  tests/DependencyInjection/SonataAdminExtensionTest.php
Labels: pedantic

#6696 Fix property name in test
  tests/Util/AdminObjectAclManipulatorTest.php
Labels: pedantic

#6704 Use instance of AdminObjectAclManipulator
  tests/Controller/CRUDControllerTest.php
  tests/Fixtures/Util/DummyDomainObject.php
Labels: pedantic

#6707 Add missing upgrade note from #6537
  UPGRADE-4.0.md
Labels: major, pedantic

#6706 Use instance of SearchHandler in tests
  tests/Action/SearchActionTest.php
  tests/Block/AdminSearchBlockServiceTest.php
Labels: pedantic

#6695 Remove NEXT_MAJOR comments related to Pool
  src/Admin/Pool.php
  src/DependencyInjection/Compiler/GlobalVariablesCompilerPass.php
  src/DependencyInjection/SonataAdminExtension.php
  src/Resources/config/core.php
  src/Resources/views/Core/dashboard.html.twig
  src/Twig/GlobalVariables.php
  tests/Action/DashboardActionTest.php
  tests/Action/SearchActionTest.php
  tests/Admin/PoolTest.php
  tests/Command/ExplainAdminCommandTest.php
  tests/Command/GenerateObjectAclCommandTest.php
  tests/Command/ListAdminCommandTest.php
  tests/Command/SetupAclCommandTest.php
  tests/Controller/CRUDControllerTest.php
  tests/DependencyInjection/SonataAdminExtensionTest.php
  tests/Mapper/BaseGroupedMapperTest.php
  tests/Route/AdminPoolLoaderTest.php
  tests/Translator/Extractor/AdminExtractorTest.php
  tests/Twig/Extension/GroupExtensionTest.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
  tests/Twig/GlobalVariablesTest.php
Labels: major

#6677 Use sonata_config instead of admin_pool
  src/Resources/views/Pager/base_links.html.twig
Labels: patch

#6541 Add some methods, coming from AbstractPager and used in twig to PagerInterface
  src/Datagrid/Pager.php
  src/Datagrid/PagerInterface.php
  src/Datagrid/SimplePager.php
  src/Resources/views/Block/block_stats.html.twig
  tests/App/Datagrid/Pager.php
  tests/Datagrid/PagerTest.php
Labels: minor

#6722 Improves getting of first array element
  src/Resources/views/CRUD/Association/edit_many_to_many.html.twig
Labels: patch

#6702 Check for _per_page existence
  src/Admin/AbstractAdmin.php
Labels: patch

#6697 Remove passing admin_pool to twig templates in next major version
  src/Action/DashboardAction.php
  src/Action/SearchAction.php
  src/Block/AdminListBlockService.php
  src/Block/AdminSearchBlockService.php
  src/Block/AdminStatsBlockService.php
  src/Controller/CRUDController.php
  tests/Action/SearchActionTest.php
  tests/Controller/CRUDControllerTest.php
Labels: pedantic

#6699 Add RouteCollectionInterface
  UPGRADE-3.x.md
  src/Route/RouteCollection.php
  src/Route/RouteCollectionInterface.php
Labels: minor

#6616 Update LockExtension.php
  src/Admin/Extension/LockExtension.php
Labels: patch

#6718 Fix form label in next major
  src/Form/FormMapper.php
Labels: pedantic
