Repository sonata-project/SonataAdminBundle, pull requests merged in 2020-03, with the labels that each got.

#5934 Fix sortOrder default value
  src/Datagrid/Datagrid.php
  tests/Datagrid/DatagridTest.php
Labels: patch

#5941 Manual revert of PR#5712
  src/Controller/CRUDController.php
  tests/Controller/CRUDControllerTest.php
Labels: patch

#5951 Remove deprecations
  tests/App/AppKernel.php
  tests/Menu/MenuBuilderTest.php
Labels: minor

#5952 Fix isGranted deprecation when using array
  src/Security/Handler/AclSecurityHandler.php
Labels: patch

#5935 Handle case without _sort_by value
  src/Resources/views/CRUD/base_list.html.twig
Labels: minor

#5953 Move type checks to argument declarations
  src/Security/Handler/AclSecurityHandler.php
Labels: pedantic

#5948 Use "knplabs/knp-menu-bundle:3.0"
  composer.json
  src/Admin/BreadcrumbsBuilder.php
  src/Menu/Matcher/Voter/ActiveVoter.php
  src/Menu/Matcher/Voter/AdminVoter.php
  src/Menu/Provider/GroupMenuProvider.php
  tests/Admin/BreadcrumbsBuilderTest.php
Labels: major, vendor

#5944 Document creating a custom field type
  docs/reference/field_types.rst
Labels: docs

#5957 Fix some Twig deprecations
  src/Resources/views/Core/dashboard.html.twig
Labels: patch

#5960 Pass a single role to isGranted
  src/Menu/Provider/GroupMenuProvider.php
  tests/Menu/Provider/GroupMenuProviderTest.php
Labels: patch

#5962 Improve content type check for XHR requests at `CRUDController`
  src/Controller/CRUDController.php
Labels: patch

#5967 Simplify code, make it more strict
  docs/cookbook/recipe_sonata_admin_without_user_bundle.rst
Labels: docs

#5966 Fix bug with getLoginUrl()
  docs/cookbook/recipe_sonata_admin_without_user_bundle.rst
Labels: docs

#5968 Do not extend deprecated controller
  docs/cookbook/recipe_sonata_admin_without_user_bundle.rst
Labels: docs

#5963 Fix non-existent parameter
  src/DependencyInjection/AbstractSonataAdminExtension.php
  src/DependencyInjection/SonataAdminExtension.php
  tests/DependencyInjection/AbstractSonataAdminExtensionTest.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
  tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php
  tests/DependencyInjection/SonataAdminExtensionTest.php
  tests/Fixtures/DependencyInjection/DummySonataAdminExtension.php
Labels: patch

#5972 Fix phpDoc
  src/Datagrid/ProxyQueryInterface.php
Labels: pedantic

#5938 Handle ParentAssociationMapping when looking for new instance
  src/Admin/AdminHelper.php
  tests/Admin/AdminHelperTest.php
Labels: patch

#5986 Add missing `UnicodeStringTest`
  tests/Twig/Extension/UnicodeStringTest.php
Labels: pedantic

#5987 Manual merge
  UPGRADE-3.x.md
  composer.json
  docs/reference/field_types.rst
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataAdminExtension.php
  src/Resources/config/twig.xml
  src/Resources/config/twig_string.xml
  src/Resources/views/CRUD/list_html.html.twig
  src/Resources/views/CRUD/show_html.html.twig
  src/Twig/Extension/StringExtension.php
  src/Twig/Extension/UnicodeString.php
  tests/Action/DashboardActionTest.php
  tests/Admin/AdminHelperTest.php
  tests/Admin/PoolTest.php
  tests/App/AppKernel.php
  tests/Command/ExplainAdminCommandTest.php
  tests/Command/GenerateObjectAclCommandTest.php
  tests/Command/ListAdminCommandTest.php
  tests/Command/SetupAclCommandTest.php
  tests/DependencyInjection/SonataAdminExtensionTest.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: RTM

#5993 Use TranslationInterface from Contracts
  src/Twig/Extension/SonataAdminExtension.php
  tests/Action/SetObjectFieldValueActionTest.php
  tests/Controller/CRUDControllerTest.php
  tests/Controller/HelperControllerTest.php
  tests/Menu/Integration/BaseMenuTest.php
  tests/Menu/Integration/TabMenuTest.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: minor

#5994 Replace deprecated configureSideMenu with configureTabMenu
  docs/reference/child_admin.rst
Labels: docs

#5995 Rewrite ModelManagerCompilerPassTest without mocks
  tests/DependencyInjection/Compiler/ModelManagerCompilerPassTest.php
Labels: pedantic

#5998 Fix UnicodeString tests
  tests/Twig/Extension/UnicodeStringTest.php
Labels: pedantic

#6000 Modernize controller references
  docs/reference/dashboard.rst
  tests/Admin/AdminTest.php
  tests/Admin/BreadcrumbsBuilderTest.php
Labels: pedantic

#6006 Add parameters options for list button
  docs/reference/action_list.rst
  src/Resources/views/CRUD/list__action_delete.html.twig
  src/Resources/views/CRUD/list__action_edit.html.twig
  src/Resources/views/CRUD/list__action_history.html.twig
  src/Resources/views/CRUD/list__action_show.html.twig
Labels: minor
