Repository sonata-project/SonataAdminBundle, pull requests merged in 2021-11, with the labels that each got.

#7582 Added more example about ChoiceFieldMaskType
  docs/images/choice_field_mask_type.gif
  docs/reference/form_types.rst
Labels: docs

#7598 Fix Phpdoc
  src/Filter/FilterInterface.php
Labels: patch

#7599 Add missing accent
  src/Resources/translations/SonataAdminBundle.fr.xliff
Labels: patch

#7586 Improve Custom Action Access Management section in documentation
  docs/reference/advanced_configuration.rst
Labels: docs

#7580 Bump phpstan
  composer.json
  phpstan-baseline.neon
  phpstan.neon.dist
  src/Admin/Pool.php
  src/Block/AdminPreviewBlockService.php
  src/Form/DataTransformer/ArrayToModelTransformer.php
  src/Form/DataTransformer/BooleanToStringTransformer.php
  src/Form/DataTransformer/FilterDataTransformer.php
  src/Form/DataTransformer/ModelToIdPropertyTransformer.php
  src/Form/DataTransformer/ModelToIdTransformer.php
  src/Form/DataTransformer/ModelsToArrayTransformer.php
  src/Form/DataTransformerResolver.php
  src/Form/DataTransformerResolverInterface.php
  src/Form/Extension/Field/Type/FormTypeFieldExtension.php
  src/Security/Handler/AclSecurityHandler.php
  src/Twig/Extension/GroupExtension.php
  src/Util/AdminAclManipulator.php
  src/Util/AdminObjectAclManipulator.php
  src/Util/FormBuilderIterator.php
  src/Util/FormViewIterator.php
  tests/Controller/CRUDControllerTest.php
  tests/Form/DataTransformerResolverTest.php
  tests/Form/Extension/Field/Type/FormTypeFieldExtensionTest.php
Labels: minor

#7610 Symfony maker already supports Symfony 6
  .github/workflows/test.yaml
  tests/Maker/AdminMakerTest.php
Labels: pedantic

#7608 Avoid error when overriding part of template
  src/Resources/views/CRUD/base_list.html.twig
Labels: bug

#7617 Re-add lost feature from merge 3.x into 4.x
  src/Admin/AbstractAdmin.php
  src/Resources/views/CRUD/base_list_flat_field.html.twig
  src/Resources/views/CRUD/base_list_flat_inner_row.html.twig
Labels: minor, feature

#7621 Create 5.0 UPGRADE guide
  UPGRADE-3.x.md
  UPGRADE-4.0.md
  UPGRADE-5.0.md
Labels: pedantic

#7618 Add jquery ui doc
  docs/cookbook/recipe_bootlint.rst
  docs/cookbook/recipe_icheck.rst
  docs/cookbook/recipe_jquery_ui.rst
  docs/cookbook/recipe_select2.rst
  docs/index.rst
Labels: docs

#7606 Add next major about batch action delete
  src/Controller/CRUDController.php
Labels: pedantic

#7623 Use `Datagrid` instead of own implementation
  tests/App/Builder/DatagridBuilder.php
  tests/App/Datagrid/Datagrid.php
Labels: pedantic

#7624 Add support for ArrayAccess
  src/Admin/AdminHelper.php
  tests/Admin/AdminHelperTest.php
Labels: minor

#7626 Add support for nullable username
  src/Model/Revision.php
Labels: minor
