Repository sonata-project/SonataAdminBundle, pull requests merged in 2021-07, with the labels that each got.

#7300 Typo "buildBreacrumbs" in UPGRADE-3.x.md
  UPGRADE-3.x.md
Labels: pedantic

#7301 fix issue 7268 by checking Symfony form type inheritance
  src/Builder/AbstractFormContractor.php
  tests/Admin/AdminTest.php
  tests/App/config/services.yml
  tests/Builder/AbstractFormContractorTest.php
Labels: minor

#7302 Try to avoid some covariant issues
  src/Action/RetrieveAutocompleteItemsAction.php
  src/Admin/AdminHelper.php
  src/Admin/BreadcrumbsBuilder.php
  src/Block/AdminPreviewBlockService.php
  src/Bridge/Exporter/AdminExporter.php
  src/Controller/CRUDController.php
  src/Route/RoutesCache.php
  src/Search/SearchHandler.php
  src/Twig/Extension/BreadcrumbsExtension.php
  src/Util/ObjectAclManipulator.php
Labels: pedantic

#7306 Easier way to override button
  src/Resources/views/CRUD/base_edit_form.html.twig
Labels: minor

#7315 Improve configureBatchActions phpdoc
  src/Admin/AbstractAdmin.php
Labels: pedantic

#7299 Support custom role with RoleSecurityHandler
  src/Security/Handler/RoleSecurityHandler.php
  tests/Security/Handler/RoleSecurityHandlerTest.php
Labels: minor

#7321 Add doc about select2 minimum results
  docs/cookbook/recipe_select2.rst
Labels: docs

#7319 Remove property validation from explain admin
  src/Command/ExplainAdminCommand.php
  src/Command/GenerateObjectAclCommand.php
  src/Command/ListAdminCommand.php
  src/Command/SetupAclCommand.php
  src/Resources/config/commands.php
  src/Twig/Extension/BreadcrumbsExtension.php
  src/Twig/Extension/GroupExtension.php
  src/Twig/Extension/SonataAdminExtension.php
  tests/Command/ExplainAdminCommandTest.php
  tests/Fixtures/Command/explain_admin.txt
  tests/Fixtures/Command/explain_admin_empty_validator.txt
Labels: major

#7320 Stop using response_item_callback param 3 as reference
  docs/reference/form_types.rst
  src/Action/RetrieveAutocompleteItemsAction.php
  tests/Action/RetrieveAutocompleteItemsActionTest.php
Labels: patch

#7330 Fix for not showing placeholder when using Select2 with ChoiceType
  assets/js/admin.js
  src/Resources/public/app.js
  src/Resources/views/Form/form_admin_fields.html.twig
Labels: patch

#7290 Deprecate ajax call to search action
  src/Action/SearchAction.php
  src/Resources/config/actions.php
  tests/Action/SearchActionTest.php
Labels: minor

#7332 Add defined check for translation_domain property
  src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig
  src/Resources/views/CRUD/base_edit_form.html.twig
  src/Resources/views/CRUD/base_edit_form_macro.html.twig
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/CRUD/base_show.html.twig
  src/Resources/views/CRUD/base_show_macro.html.twig
  src/Resources/views/CRUD/dashboard__action.html.twig
  src/Resources/views/CRUD/dashboard__action_create.html.twig
Labels: patch

#7335 fix(x-editable): choice value update crash with 0 value
  src/Action/SetObjectFieldValueAction.php
Labels: patch

#7336 Fix phpdoc
  src/Command/QuestionableCommand.php
Labels: pedantic

#7325 Add list_action_button_content and logo_content options
  docs/reference/action_list.rst
  docs/reference/configuration.rst
  src/DependencyInjection/Configuration.php
  src/Resources/views/CRUD/list__action_delete.html.twig
  src/Resources/views/CRUD/list__action_edit.html.twig
  src/Resources/views/CRUD/list__action_history.html.twig
  src/Resources/views/CRUD/list__action_show.html.twig
  src/Resources/views/standard_layout.html.twig
  src/SonataConfiguration.php
Labels: minor

#7339 Fix some phpstan strict rules errors
  src/Admin/AbstractAdmin.php
  src/Command/GenerateObjectAclCommand.php
  src/Controller/CRUDController.php
  src/Datagrid/SimplePager.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/Form/DataTransformerResolver.php
  src/Form/Extension/ChoiceTypeExtension.php
  src/Form/Extension/Field/Type/FormTypeFieldExtension.php
  src/Form/Type/AdminType.php
  src/Form/Type/ModelAutocompleteType.php
  src/Form/Type/ModelType.php
  src/Mapper/BaseGroupedMapper.php
  src/Menu/Matcher/Voter/ActiveVoter.php
  tests/Form/AbstractLayoutTestCase.php
  tests/Form/DataTransformer/ModelToIdPropertyTransformerTest.php
  tests/Mapper/BaseGroupedMapperTest.php
  tests/Menu/Provider/GroupMenuProviderTest.php
  tests/Search/SearchHandlerTest.php
Labels: pedantic

#7343 Fix static analysis
  src/FieldDescription/FieldDescriptionInterface.php
  tests/Menu/Provider/GroupMenuProviderTest.php
Labels: pedantic

#7342 Fix checking existence of placeholder
  assets/js/admin.js
  src/Resources/public/app.js
Labels: patch

#7345 Make getPreviousFilter non nullable to be consistent
  src/Filter/Filter.php
  src/Search/ChainableFilterInterface.php
Labels: major

#7340 Add strict rules
  composer.json
  phpstan-baseline.neon
  src/Admin/AbstractAdmin.php
  src/BCLayer/BCDeprecationParameters.php
  src/BCLayer/BCUserInterface.php
  src/Command/GenerateObjectAclCommand.php
  src/Controller/CRUDController.php
  src/DependencyInjection/Configuration.php
  src/Filter/Persister/SessionFilterPersister.php
  src/Form/DataTransformer/BooleanToStringTransformer.php
  src/Menu/Matcher/Voter/AdminVoter.php
  src/Menu/Provider/GroupMenuProvider.php
  src/Route/AdminPoolLoader.php
  src/Security/Handler/AclSecurityHandler.php
  tests/Admin/AdminTest.php
  tests/Command/GenerateObjectAclCommandTest.php
  tests/Controller/CRUDControllerTest.php
  tests/Datagrid/DatagridTest.php
  tests/Route/RouteCollectionTest.php
Labels: pedantic

#7350 fix select2 placeholder html
  src/Resources/views/Form/form_admin_fields.html.twig
Labels: bug

#7351 Add `default` parameter to getPersistentParameter
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  tests/Admin/AdminTest.php
Labels: major
