Repository sonata-project/SonataAdminBundle, pull requests merged in 2021-02, with the labels that each got.

#6834 Explicitly require some packages
  composer.json
Labels: pedantic

#6838 Remove default field_name value
  src/Datagrid/DatagridMapper.php
  tests/Datagrid/DatagridMapperTest.php
Labels: major

#6841 fix phpstan error
  src/SonataConfiguration.php
Labels: pedantic

#6844 Deprecate old datagridMapper signature
  UPGRADE-3.x.md
  docs/getting_started/the_list_view.rst
  docs/reference/architecture.rst
  src/Admin/AbstractAdmin.php
  src/Datagrid/DatagridMapper.php
  tests/Datagrid/DatagridMapperTest.php
Labels: minor

#6842 make AdminHelper @internal
  src/Admin/AdminHelper.php
Labels: major

#6828 Clean up the way `required` => false is set
  src/Filter/Filter.php
  src/Form/Type/Filter/ChoiceType.php
  src/Form/Type/Filter/DateRangeType.php
  src/Form/Type/Filter/DateTimeRangeType.php
  src/Form/Type/Filter/DateTimeType.php
  src/Form/Type/Filter/DateType.php
  src/Form/Type/Filter/DefaultType.php
  src/Form/Type/Filter/NumberType.php
  tests/Datagrid/DatagridMapperTest.php
  tests/Filter/FilterTest.php
Labels: major

#6849 Fix psalm and deprecations
  src/Admin/Pool.php
  src/Maker/AdminMaker.php
  src/Twig/GlobalVariables.php
Labels: pedantic

#6850 Declare getNewInstance as final in favor of alterNewInstance
  UPGRADE-3.x.md
  src/Admin/AbstractAdmin.php
Labels: minor

#6852 Update recipe_sonata_admin_without_user_bundle.rst
  docs/cookbook/recipe_sonata_admin_without_user_bundle.rst
Labels: docs

#6856 [#6569] Parse JSON responses on `Admin.setup_xeditable()`
  src/Resources/public/Admin.js
Labels: patch

#6863 Restrict visibility of pre/post methods
  src/Admin/AbstractAdmin.php
  src/Admin/LifecycleHookProviderInterface.php
Labels: major

#6873 Add a configurePersistentParameters method
  docs/reference/routing.rst
  src/Admin/AbstractAdmin.php
  src/Admin/AdminExtensionInterface.php
Labels: minor

#6872 Add final to methods of AbstractAdmin
  src/Admin/AbstractAdmin.php
  tests/Action/GetShortObjectDescriptionActionTest.php
  tests/Action/RetrieveAutocompleteItemsActionTest.php
  tests/Admin/AdminTest.php
  tests/Admin/Extension/LockExtensionTest.php
  tests/Block/AdminSearchBlockServiceTest.php
  tests/Twig/Extension/RenderElementExtensionTest.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: major

#6883 Add AbstractAdmin::createNewInstance method
  UPGRADE-3.x.md
  src/Admin/AbstractAdmin.php
  src/Model/ModelManagerInterface.php
  src/Util/Instantiator.php
  tests/Admin/AdminTest.php
  tests/App/Admin/FooAdmin.php
  tests/App/Admin/TranslatedAdmin.php
  tests/App/Model/ModelManager.php
Labels: minor

#6877 Fix submit filters
  src/Admin/AbstractAdmin.php
  src/Util/ParametersManipulator.php
  tests/Util/ParametersManipulatorTest.php
Labels: minor

#6411 Prevent false deprecation error for n to m associations
  src/Controller/CRUDController.php
  tests/Controller/CRUDControllerTest.php
Labels: patch

#6887 Fix FilterInterface::apply phpdoc
  src/Filter/FilterInterface.php
Labels: pedantic

#6888 Remove some tautologies at `AbstractAdmin`
  src/Admin/AbstractAdmin.php
Labels: pedantic

#6577 Use `DateType::HTML5_FORMAT` constants as values for "format" and "date_format" form options
  src/Form/Type/Filter/DateRangeType.php
  src/Form/Type/Filter/DateTimeRangeType.php
  src/Form/Type/Filter/DateTimeType.php
  src/Form/Type/Filter/DateType.php
  tests/Form/Type/Filter/DateTimeRangeTypeTest.php
Labels: pedantic

#6889 Display errors from XHR requests at `edit_many_script.html.twig`
  src/Resources/views/CRUD/Association/edit_many_script.html.twig
Labels: patch
