Repository sonata-project/SonataAdminBundle, pull requests merged in 2021-09, with the labels that each got.

#7472 Fix error message
  src/FieldDescription/BaseFieldDescription.php
  tests/FieldDescription/BaseFieldDescriptionTest.php
Labels: pedantic

#7483 Allow configured action buttons
  src/Admin/AbstractAdmin.php
Labels: patch

#7496 doc: Overriding translation domain in 4.0.0
  docs/reference/translation.rst
Labels: docs

#7506 Restrict form options types
  src/Form/Type/ModelAutocompleteType.php
  src/Form/Type/ModelHiddenType.php
  src/Form/Type/ModelListType.php
  src/Form/Type/ModelReferenceType.php
  src/Form/Type/ModelType.php
  tests/Form/Type/ModelListTypeTest.php
Labels: patch

#7509 Display add block and user block if non empty
  src/Resources/views/standard_layout.html.twig
Labels: patch

#7515 Update homepage
  composer.json
Labels: pedantic
