Repository sonata-project/SonataAdminBundle, pull requests merged in 2021-08, with the labels that each got.

#7355 Fix psalm issues
  composer.json
  phpstan-baseline.neon
  src/Admin/AdminExtensionInterface.php
  src/Datagrid/DatagridMapper.php
  src/Datagrid/ListMapper.php
  src/Mapper/BaseGroupedMapper.php
  src/Mapper/BaseMapper.php
  src/Security/Handler/AclSecurityHandler.php
  src/Security/Handler/AclSecurityHandlerInterface.php
Labels: pedantic

#7356 Add psr/log version 2
  composer.json
  phpstan-baseline.neon
Labels: minor

#7360 Fix RetrieveAutocompleteItemsAction for multiple properties
  phpstan-baseline.neon
  src/Action/RetrieveAutocompleteItemsAction.php
  tests/Action/RetrieveAutocompleteItemsActionTest.php
Labels: patch

#7363 Fix sonata.admin.exporter usage
  src/Controller/CRUDController.php
  tests/Controller/CRUDControllerTest.php
Labels: patch

#7362 Deprecate the use of ParamConverter in favor of argument resolver
  UPGRADE-3.x.md
  docs/cookbook/recipe_decouple_crud_controller.rst
  src/ArgumentResolver/AdminValueResolver.php
  src/DependencyInjection/SonataAdminExtension.php
  src/Request/ParamConverter/AdminParamConverter.php
  src/Resources/config/core.php
  src/Resources/config/param_converter.php
  tests/App/Admin/AdminAsParameterAdmin.php
  tests/App/AppKernel.php
  tests/App/Controller/AdminAsParameterController.php
  tests/App/Controller/InvokableController.php
  tests/App/config/services.yml
  tests/ArgumentResolver/AdminValueResolverTest.php
  tests/DependencyInjection/SonataAdminExtensionTest.php
  tests/Functional/Controller/AdminAsParameterControllerTest.php
  tests/Request/ParamConverter/AdminParamConverterTest.php
Labels: minor

#7364 Implement FormMapper from BlockBundle
  composer.json
  src/Form/FormMapper.php
Labels: minor

#7374 Avoid error when extendings CRUDController
  src/Controller/CRUDController.php
Labels: pedantic

#7381 Update alias for master
  composer.json
Labels: pedantic

#7387 Do not throw error on invalidArgument
  src/ArgumentResolver/AdminValueResolver.php
  src/Request/AdminFetcherInterface.php
  tests/ArgumentResolver/AdminValueResolverTest.php
Labels: patch

#7388 3.x into 4.x
  src/ArgumentResolver/AdminValueResolver.php
  src/Request/AdminFetcherInterface.php
  tests/ArgumentResolver/AdminValueResolverTest.php
Labels: patch

#7393 Update yarn.lock dependencies
  src/Resources/public/admin-lte-skins/skin-blue-light.min.css
  src/Resources/public/admin-lte-skins/skin-blue.min.css
  src/Resources/public/admin-lte-skins/skin-green-light.min.css
  src/Resources/public/admin-lte-skins/skin-green.min.css
  src/Resources/public/admin-lte-skins/skin-purple-light.min.css
  src/Resources/public/admin-lte-skins/skin-purple.min.css
  src/Resources/public/admin-lte-skins/skin-red-light.min.css
  src/Resources/public/admin-lte-skins/skin-red.min.css
  src/Resources/public/admin-lte-skins/skin-yellow-light.min.css
  src/Resources/public/admin-lte-skins/skin-yellow.min.css
  src/Resources/public/app.css
  src/Resources/public/fonts/fa-brands-400.eot
  src/Resources/public/fonts/fa-brands-400.ttf
  src/Resources/public/fonts/fa-brands-400.woff
  src/Resources/public/fonts/fa-brands-400.woff2
  src/Resources/public/fonts/fa-regular-400.eot
  src/Resources/public/fonts/fa-regular-400.ttf
  src/Resources/public/fonts/fa-regular-400.woff
  src/Resources/public/fonts/fa-regular-400.woff2
  src/Resources/public/fonts/fa-solid-900.eot
  src/Resources/public/fonts/fa-solid-900.ttf
  src/Resources/public/fonts/fa-solid-900.woff
  src/Resources/public/fonts/fa-solid-900.woff2
  src/Resources/public/images/fa-brands-400.svg
  src/Resources/public/images/fa-regular-400.svg
  src/Resources/public/images/fa-solid-900.svg
  yarn.lock
Labels: patch

#7445 Fix variable name
  src/Resources/views/CRUD/base_show_compare.html.twig
Labels: patch

#7376 Revert: Show matching filters in search results
  src/Block/AdminSearchBlockService.php
  src/Resources/public/css/layout.css
  src/Resources/views/Block/block_search_result.html.twig
Labels: bug, patch

#7452 Fix collection type with nested field
  src/Admin/AbstractAdmin.php
  src/Admin/AdminHelper.php
  src/Admin/AdminInterface.php
  src/Form/FormMapper.php
  src/Show/ShowMapper.php
  tests/Admin/AdminHelperTest.php
Labels: minor

#7457 3.x into 4.x
  .github/FUNDING.yml
  .github/workflows/test.yaml
  CONTRIBUTING.md
  Makefile
  src/Resources/views/Block/block_search_result.html.twig
Labels: pedantic

#7450 Improve signature of method using securityInformation
  src/Security/Handler/AclSecurityHandler.php
  src/Security/Handler/AclSecurityHandlerInterface.php
  src/Util/AdminAclManipulator.php
  src/Util/AdminAclManipulatorInterface.php
  src/Util/ObjectAclManipulator.php
  tests/Util/ObjectAclManipulatorTest.php
Labels: major
