Repository sonata-project/SonataAdminBundle, pull requests merged in 2021-10, with the labels that each got.

#7519 Deprecate BuilderInterface
  src/Builder/BuilderInterface.php
  src/Builder/FormContractorInterface.php
Labels: minor

#7567 Remove wrong @final annotation
  src/Admin/AbstractAdmin.php
Labels: patch

#7564 Allow to hide select button in ajax mode
  src/Admin/AbstractAdmin.php
  src/Resources/views/CRUD/Association/edit_many_to_one.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_one.html.twig
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/CRUD/base_list_flat_field.html.twig
  src/Resources/views/CRUD/base_list_flat_inner_row.html.twig
  src/Resources/views/CRUD/base_list_inner_row.html.twig
  src/Resources/views/CRUD/list_outer_rows_mosaic.html.twig
  src/Resources/views/Form/form_admin_fields.html.twig
Labels: minor

#7565 Minor cosmetic changes to Italian translation
  src/Resources/translations/SonataAdminBundle.it.xliff
Labels: patch

#7563 Allow to remove an admin extension dynamically
  docs/reference/extensions.rst
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  tests/Admin/AdminTest.php
Labels: minor, Needs: Documentation

#7568 Allow newer versions of psr container and log
  composer.json
Labels: minor

#7571 Fix changelog
  CHANGELOG.md
Labels: pedantic

#7572 Fix uses
  docs/reference/extensions.rst
Labels: docs

#7576 3.x into 4.x
  CHANGELOG.md
  src/Resources/views/CRUD/Association/edit_many_to_one.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_one.html.twig
Labels: patch
