Repository sonata-project/SonataAdminBundle, pull requests merged in 2021-01, with the labels that each got.

#6716 Remove public access for getFieldValue
  UPGRADE-3.x.md
  src/Admin/BaseFieldDescription.php
  src/Admin/FieldDescriptionInterface.php
Labels: minor

#6724 Support fieldName with dots
  src/Admin/BaseFieldDescription.php
  tests/Admin/BaseFieldDescriptionTest.php
  tests/Fixtures/Admin/FieldDescription.php
  tests/Fixtures/Entity/FooBoolean.php
Labels: minor

#6576 Add generics to AdminExtensionInterface
  composer.json
  src/Admin/AbstractAdminExtension.php
  src/Admin/AdminExtensionInterface.php
  src/Admin/Extension/LockExtension.php
  src/Event/AdminEventExtension.php
Labels: minor

#6744 Improve deprecation message
  src/Twig/Extension/SonataAdminExtension.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: pedantic

#6747 Allow persistence bundle to avoid deprecation
  src/Datagrid/Pager.php
Labels: pedantic

#6746 Add removeTab method
  src/Form/FormMapper.php
  src/Mapper/BaseGroupedMapper.php
  src/Show/ShowMapper.php
  tests/Form/FormMapperTest.php
  tests/Show/ShowMapperTest.php
Labels: minor

#6733 Inject a ServiceLocator to Pool instead of container
  composer.json
  src/Admin/Pool.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/Resources/config/core.php
Labels: major

#6752 Move TemplateRegistryInterface::TYPE_* constants
  UPGRADE-3.x.md
  docs/reference/action_list.rst
  docs/reference/action_show.rst
  docs/reference/field_types.rst
  src/Action/SetObjectFieldValueAction.php
  src/Admin/FieldDescriptionInterface.php
  src/DependencyInjection/AbstractSonataAdminExtension.php
  src/Form/DataTransformerResolver.php
  src/Resources/views/CRUD/base_list_field.html.twig
  src/Templating/TemplateRegistryInterface.php
  tests/App/Admin/FooAdmin.php
  tests/App/Admin/TranslatedAdmin.php
Labels: minor

#6754 Add tests for CRUDController::configureAdmin
  tests/Controller/CRUDControllerTest.php
Labels: pedantic

#6764 Add missing phpdoc type declarations
  src/DependencyInjection/Admin/AbstractTaggedAdmin.php
Labels: patch

#6775 Remove RuntimeException (mostly in NEXT_MAJOR comment)
  src/Admin/AbstractAdmin.php
Labels: pedantic

#6784 Fix default "show" template for type "float" from SonataIntlBundle
  src/DependencyInjection/AbstractSonataAdminExtension.php
Labels: patch

#6789 Added callback with possibility to modify each individual item in res…
  docs/reference/form_types.rst
  src/Action/RetrieveAutocompleteItemsAction.php
  src/Form/Type/ModelAutocompleteType.php
  src/Resources/public/Admin.js
  src/Resources/views/Form/form_admin_fields.html.twig
  tests/Action/RetrieveAutocompleteItemsActionTest.php
  tests/Form/Type/ModelAutocompleteTypeTest.php
Labels: Needs: Documentation, minor

#6778 fix nested admin (one-to-one-to-many relation) that opens inline (fixes #6777)
  phpstan-baseline.neon
  src/Admin/AdminHelper.php
  tests/Admin/AdminHelperTest.php
Labels: Needs: Changelog note, patch

#6794 Deprecate Pool::setTemplateRegistry
  UPGRADE-3.x.md
  src/Admin/Pool.php
  src/Resources/config/core.php
  tests/Action/DashboardActionTest.php
Labels: minor

#6799 Use instances instead of mocks
  tests/Admin/AdminHelperTest.php
Labels: pedantic

#6804 Remove some Next major comment
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  src/Admin/BaseFieldDescription.php
  src/Admin/FieldDescriptionInterface.php
  src/Controller/CRUDController.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/Filter/Filter.php
  src/Resources/views/CRUD/base_list.html.twig
  tests/Admin/AdminTest.php
  tests/Admin/BaseFieldDescriptionTest.php
  tests/Controller/CRUDControllerTest.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
  tests/Filter/FilterTest.php
Labels: major

#6810 Improve phpdoc
  src/Admin/AdminInterface.php
Labels: pedantic

#6815 Fix psalm issues
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/DependencyInjection/Compiler/AdminMakerCompilerPass.php
  src/DependencyInjection/Compiler/AdminSearchCompilerPass.php
  src/DependencyInjection/Compiler/CheckAclUserManagerCompilerPass.php
  src/DependencyInjection/Compiler/ObjectAclManipulatorCompilerPass.php
Labels: pedantic

#6809 Do not throw exception in next major in attachAdminClass if there is no class to attach
  src/Admin/AbstractAdmin.php
Labels: pedantic

#6819 Add final modifier to classes marked as @final
  src/Datagrid/DatagridMapper.php
  src/Datagrid/ListMapper.php
  src/Form/FormMapper.php
  src/Search/SearchHandler.php
  src/Show/ShowMapper.php
  src/Util/AdminObjectAclData.php
  src/Util/AdminObjectAclManipulator.php
Labels: major

#6824 Do not add '-' when there is nothing on the right side
  src/Resources/views/CRUD/base_list.html.twig
Labels: patch

#6827 Remove param from ProxyQueryInterface::execute
  src/Datagrid/ProxyQueryInterface.php
  src/Datagrid/SimplePager.php
  tests/App/Datagrid/ProxyQuery.php
  tests/Datagrid/SimplePagerTest.php
Labels: minor
