Repository sonata-project/SonataAdminBundle, pull requests merged in 2021-12, with the labels that each got.

#7629 Fix build
  composer.json
  src/Action/SetObjectFieldValueAction.php
  src/Menu/Matcher/Voter/AdminVoter.php
  tests/App/AppKernel.php
Labels: pedantic

#7636 Downgrade translation-contracts
  composer.json
  tests/Form/Type/ChoiceFieldMaskTypeTest.php
Labels: patch

#7640 Update form_types.rst
  docs/reference/form_types.rst
Labels: docs

#7649 Fix psalm
  tests/Admin/PoolTest.php
Labels: pedantic

#7647 bug #7646 - rebased fix from #3082
  src/Route/DefaultRouteGenerator.php
  tests/Route/DefaultRouteGeneratorTest.php
Labels: patch

#7654 Update form_types.rst
  docs/reference/form_types.rst
Labels: docs

#7643 configureShowFields method's category should be category.name
  docs/getting_started/the_show_view.rst
Labels: docs

#7517 Restrict form_types values
  docs/reference/configuration.rst
  src/DependencyInjection/Configuration.php
  src/SonataConfiguration.php
Labels: pedantic

#7659 Deprecate passing an array of role to isGranted
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  src/Resources/config/security.php
  src/Security/Handler/AclSecurityHandler.php
  src/Security/Handler/RoleSecurityHandler.php
  src/Security/Handler/SecurityHandlerInterface.php
  tests/Admin/AdminTest.php
  tests/Security/Handler/AclSecurityHandlerTest.php
  tests/Security/Handler/RoleSecurityHandlerTest.php
Labels: minor

#7661 Updated configuration key that delays the ajax requests.
  src/Form/Type/ModelAutocompleteType.php
  src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
Labels: minor

#7641 Fix batch confirmation translations
  src/Resources/translations/SonataAdminBundle.de.xliff
  src/Resources/translations/SonataAdminBundle.it.xliff
  src/Resources/translations/SonataAdminBundle.nl.xliff
  src/Resources/translations/SonataAdminBundle.no.xliff
Labels: patch

#7666 Fix support for full name route
  src/Route/DefaultRouteGenerator.php
  tests/Route/DefaultRouteGeneratorTest.php
Labels: patch

#7669 Fix twig
  src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
Labels: patch

#7658 Introduce showInDashboard instead of showIn
  docs/reference/security.rst
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  src/Admin/Pool.php
  tests/Admin/AdminTest.php
  tests/Admin/PoolTest.php
  tests/Twig/Extension/GroupExtensionTest.php
Labels: minor

#7672 Fix tests
  tests/Twig/GroupRuntimeTest.php
Labels: pedantic

#7653 Add "XLSX" translations
  src/Admin/AbstractAdmin.php
  src/Resources/translations/SonataAdminBundle.ar.xliff
  src/Resources/translations/SonataAdminBundle.bg.xliff
  src/Resources/translations/SonataAdminBundle.bs.xliff
  src/Resources/translations/SonataAdminBundle.ca.xliff
  src/Resources/translations/SonataAdminBundle.cs.xliff
  src/Resources/translations/SonataAdminBundle.de.xliff
  src/Resources/translations/SonataAdminBundle.en.xliff
  src/Resources/translations/SonataAdminBundle.es.xliff
  src/Resources/translations/SonataAdminBundle.eu.xliff
  src/Resources/translations/SonataAdminBundle.fa.xliff
  src/Resources/translations/SonataAdminBundle.fr.xliff
  src/Resources/translations/SonataAdminBundle.hr.xliff
  src/Resources/translations/SonataAdminBundle.hu.xliff
  src/Resources/translations/SonataAdminBundle.it.xliff
  src/Resources/translations/SonataAdminBundle.ja.xliff
  src/Resources/translations/SonataAdminBundle.lb.xliff
  src/Resources/translations/SonataAdminBundle.lt.xliff
  src/Resources/translations/SonataAdminBundle.lv.xliff
  src/Resources/translations/SonataAdminBundle.nl.xliff
  src/Resources/translations/SonataAdminBundle.no.xliff
  src/Resources/translations/SonataAdminBundle.pl.xliff
  src/Resources/translations/SonataAdminBundle.pt.xliff
  src/Resources/translations/SonataAdminBundle.pt_BR.xliff
  src/Resources/translations/SonataAdminBundle.ro.xliff
  src/Resources/translations/SonataAdminBundle.ru.xliff
  src/Resources/translations/SonataAdminBundle.sk.xliff
  src/Resources/translations/SonataAdminBundle.sl.xliff
  src/Resources/translations/SonataAdminBundle.sr_Cyrl.xliff
  src/Resources/translations/SonataAdminBundle.sr_Latn.xliff
  src/Resources/translations/SonataAdminBundle.sv_SE.xliff
  src/Resources/translations/SonataAdminBundle.tr.xliff
  src/Resources/translations/SonataAdminBundle.uk.xliff
  src/Resources/translations/SonataAdminBundle.zh_CN.xliff
  src/Resources/translations/SonataAdminBundle.zh_HK.xliff
  tests/Admin/AdminTest.php
Labels: minor

#7675 Fix psalm
  tests/Admin/PoolTest.php
Labels: pedantic

#7676 Fix some phpstan9 errors
  src/Admin/AdminInterface.php
  src/Datagrid/ProxyQueryInterface.php
  src/Form/Extension/Field/Type/FormTypeFieldExtension.php
  src/Manipulator/ObjectManipulator.php
  src/Route/AdminPoolLoader.php
  src/Route/RoutesCache.php
  src/Security/Handler/AclSecurityHandler.php
  src/Util/ObjectAclManipulator.php
  src/Util/ParametersManipulator.php
  src/Util/TraversableToCollection.php
  tests/Builder/AbstractFormContractorTest.php
  tests/Controller/CRUDControllerTest.php
  tests/Datagrid/ListMapperTest.php
  tests/DependencyInjection/Compiler/AddAuditReadersCompilerPassTest.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
  tests/DependencyInjection/Compiler/AddFilterTypeCompilerPassTest.php
  tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php
  tests/DependencyInjection/Compiler/ModelManagerCompilerPassTest.php
  tests/DependencyInjection/Compiler/ObjectAclManipulatorCompilerPassTest.php
  tests/DependencyInjection/SonataAdminExtensionTest.php
  tests/FieldDescription/BaseFieldDescriptionTest.php
  tests/Form/AbstractLayoutTestCase.php
  tests/Form/Widget/FormSonataFilterChoiceWidgetTest.php
  tests/Security/Acl/Permission/AdminPermissionMapTest.php
  tests/Show/ShowMapperTest.php
  tests/Twig/Extension/RenderElementExtensionTest.php
  tests/Twig/RenderElementRuntimeTest.php
  tests/Util/AdminObjectAclManipulatorTest.php
  tests/Util/TraversableToCollectionTest.php
Labels: pedantic

#7673 Respect order of values provider in ModelsToArrayTransformer
  phpstan-baseline.neon
  src/Form/DataTransformer/ModelToIdPropertyTransformer.php
  src/Form/DataTransformer/ModelsToArrayTransformer.php
  tests/Form/DataTransformer/ModelToIdPropertyTransformerTest.php
  tests/Form/DataTransformer/ModelsToArrayTransformerTest.php
Labels: patch

#7682 Fix psalm
  phpstan-baseline.neon
  src/Util/FormViewIterator.php
Labels: pedantic
