Repository sonata-project/SonataAdminBundle, pull requests merged in 2021-06, with the labels that each got.

#7232 Update action_export.rst
  docs/reference/action_export.rst
Labels: docs

#7233 Update action_export.rst
  docs/reference/action_export.rst
Labels: docs

#7234 Fix psalm issue
  src/Admin/AbstractAdmin.php
Labels: pedantic

#7239 Fix display of history_revision_timestamp
  src/Resources/views/CRUD/history_revision_timestamp.html.twig
Labels: patch

#7241 Remove deprecations with Symfony 5.3
  src/Filter/Persister/SessionFilterPersister.php
  src/Menu/Matcher/Voter/AdminVoter.php
  src/Resources/config/core.php
  tests/Filter/Persister/SessionFilterPersisterTest.php
Labels: major

#7238 RFC: Remove CRUDController::getRequest method
  src/Controller/CRUDController.php
  tests/Controller/CRUDControllerTest.php
Labels: major

#7249 Multiple not working for AutocompleteType on master branche
  src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
Labels: patch

#7262 Replace usages of `$` with `jQuery` in `Admin.js`
  src/Resources/public/Admin.js
Labels: patch

#7263 Add final annotation for crud methods
  src/Controller/CRUDController.php
Labels: minor

#7266 Add final annotation for AbstractAdmin method final in master
  src/Admin/AbstractAdmin.php
  tests/Admin/AdminTest.php
  tests/Fixtures/Admin/PostCategoryAdmin.php
  tests/Fixtures/Admin/TagAdmin.php
Labels: minor

#7253 Fix path to CSS resources
  src/Resources/public/app.css
  src/Resources/public/entrypoints.json
  src/Resources/public/manifest.json
  webpack.config.js
Labels: patch

#7271 Respect false as translation domain
  src/Resources/views/Block/block_admin_preview.html.twig
  src/Resources/views/CRUD/base_edit_form_macro.html.twig
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/CRUD/base_list_field.html.twig
  src/Resources/views/CRUD/base_show.html.twig
  src/Resources/views/CRUD/base_show_field.html.twig
  src/Resources/views/CRUD/base_show_macro.html.twig
Labels: patch

#7267 Deprecate passing `collection` to `FormMapper::add()`
  UPGRADE-3.x.md
  src/Form/FormMapper.php
Labels: minor

#7276 3.x into Master
  UPGRADE-3.x.md
  src/Form/FormMapper.php
  src/Resources/views/Block/block_admin_preview.html.twig
  src/Resources/views/CRUD/base_edit_form_macro.html.twig
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/CRUD/base_list_field.html.twig
  src/Resources/views/CRUD/base_show.html.twig
  src/Resources/views/CRUD/base_show_field.html.twig
  src/Resources/views/Pager/base_results.html.twig
Labels: pedantic

#7279 Add generic to Mapper and Event
  phpstan-baseline.neon
  src/Admin/AbstractAdmin.php
  src/Admin/AbstractAdminExtension.php
  src/Datagrid/DatagridMapper.php
  src/Datagrid/ListMapper.php
  src/Event/ConfigureEvent.php
  src/Event/PersistenceEvent.php
  src/Form/FormMapper.php
  src/Mapper/BaseGroupedMapper.php
  src/Mapper/MapperInterface.php
  src/Show/ShowMapper.php
Labels: minor

#7277 Respect false translationd domain
  src/Resources/views/Block/block_admin_preview.html.twig
  src/Resources/views/Block/block_search_result.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig
  src/Resources/views/CRUD/base_edit_form.html.twig
  src/Resources/views/CRUD/base_edit_form_macro.html.twig
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/CRUD/base_show.html.twig
  src/Resources/views/CRUD/base_show_macro.html.twig
  src/Resources/views/CRUD/dashboard__action.html.twig
  src/Resources/views/CRUD/dashboard__action_create.html.twig
  src/Resources/views/Form/form_admin_fields.html.twig
Labels: patch

#7282 Make setParent consistent with addChild
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  tests/Admin/AdminTest.php
  tests/Fixtures/Admin/CommentAdmin.php
Labels: minor

#7254 Simulate a reset of filters if no values are different from the default ones
  src/Resources/public/Admin.js
Labels: patch

#7275 Use a SearchableFilterInterface instead of a global_search option.
  docs/reference/action_list.rst
  docs/reference/search.rst
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataAdminExtension.php
  src/Resources/config/core.php
  src/Search/SearchHandler.php
  src/Search/SearchableFilterInterface.php
  tests/Search/SearchHandlerTest.php
Labels: minor

#7292 Improve mocks
  tests/Admin/AdminTest.php
  tests/Admin/BaseAdminModelManagerTest.php
  tests/Block/AdminListBlockServiceTest.php
  tests/Block/AdminSearchBlockServiceTest.php
  tests/Datagrid/DatagridMapperTest.php
  tests/Event/ConfigureEventTest.php
  tests/Event/ConfigureQueryEventTest.php
  tests/Event/PersistenceEventTest.php
  tests/FieldDescription/BaseFieldDescriptionTest.php
  tests/Form/ChoiceList/ModelChoiceLoaderTest.php
  tests/Form/DataTransformer/ArrayToModelTransformerTest.php
  tests/Form/DataTransformer/ModelToIdTransformerTest.php
  tests/Form/Extension/Field/Type/FormTypeFieldExtensionTest.php
  tests/Form/Type/AclMatrixTypeTest.php
  tests/Form/Type/ModelAutocompleteTypeTest.php
  tests/Form/Type/ModelHiddenTypeTest.php
  tests/Form/Type/ModelTypeTest.php
  tests/Form/Widget/FormSonataFilterChoiceWidgetTest.php
  tests/Form/Widget/FormSonataNativeCollectionWidgetTest.php
  tests/Mapper/BaseGroupedMapperTest.php
  tests/Menu/Integration/BaseMenuTest.php
  tests/Menu/Matcher/Voter/ActiveVoterTest.php
  tests/Menu/Matcher/Voter/AdminVoterTest.php
  tests/Menu/MenuBuilderTest.php
  tests/Route/AdminPoolLoaderTest.php
  tests/Route/DefaultRouteGeneratorTest.php
  tests/Route/PathInfoBuilderTest.php
  tests/Security/Handler/NoopSecurityHandlerTest.php
  tests/Security/Handler/RoleSecurityHandlerTest.php
  tests/Show/ShowMapperTest.php
  tests/Twig/Extension/RenderElementExtensionTest.php
  tests/Twig/Extension/XEditableExtensionTest.php
  tests/Util/AdminObjectAclDataTest.php
Labels: pedantic

#7287 Improve reorder methods.
  src/Datagrid/Datagrid.php
  src/FieldDescription/FieldDescriptionCollection.php
  tests/Datagrid/DatagridTest.php
  tests/FieldDescription/FieldDescriptionCollectionTest.php
Labels: patch
