Repository sonata-project/SonataAdminBundle, pull requests merged in 2021-05, with the labels that each got.

#7132 backport source sans pro from master
  src/Resources/public/css/styles.css
  src/Resources/public/fonts/source-sans-pro-all-300-italic.woff
  src/Resources/public/fonts/source-sans-pro-all-300-normal.woff
  src/Resources/public/fonts/source-sans-pro-all-400-italic.woff
  src/Resources/public/fonts/source-sans-pro-all-400-normal.woff
  src/Resources/public/fonts/source-sans-pro-all-600-italic.woff
  src/Resources/public/fonts/source-sans-pro-all-600-normal.woff
  src/Resources/public/fonts/source-sans-pro-all-700-normal.woff
  src/Resources/public/fonts/source-sans-pro-cyrillic-300-italic.woff2
  src/Resources/public/fonts/source-sans-pro-cyrillic-300-normal.woff2
  src/Resources/public/fonts/source-sans-pro-cyrillic-400-italic.woff2
  src/Resources/public/fonts/source-sans-pro-cyrillic-400-normal.woff2
  src/Resources/public/fonts/source-sans-pro-cyrillic-600-italic.woff2
  src/Resources/public/fonts/source-sans-pro-cyrillic-600-normal.woff2
  src/Resources/public/fonts/source-sans-pro-cyrillic-700-normal.woff2
  src/Resources/public/fonts/source-sans-pro-cyrillic-ext-300-italic.woff2
  src/Resources/public/fonts/source-sans-pro-cyrillic-ext-300-normal.woff2
  src/Resources/public/fonts/source-sans-pro-cyrillic-ext-400-italic.woff2
  src/Resources/public/fonts/source-sans-pro-cyrillic-ext-400-normal.woff2
  src/Resources/public/fonts/source-sans-pro-cyrillic-ext-600-italic.woff2
  src/Resources/public/fonts/source-sans-pro-cyrillic-ext-600-normal.woff2
  src/Resources/public/fonts/source-sans-pro-cyrillic-ext-700-normal.woff2
  src/Resources/public/fonts/source-sans-pro-greek-300-italic.woff2
  src/Resources/public/fonts/source-sans-pro-greek-300-normal.woff2
  src/Resources/public/fonts/source-sans-pro-greek-400-italic.woff2
  src/Resources/public/fonts/source-sans-pro-greek-400-normal.woff2
  src/Resources/public/fonts/source-sans-pro-greek-600-italic.woff2
  src/Resources/public/fonts/source-sans-pro-greek-600-normal.woff2
  src/Resources/public/fonts/source-sans-pro-greek-700-normal.woff2
  src/Resources/public/fonts/source-sans-pro-greek-ext-300-italic.woff2
  src/Resources/public/fonts/source-sans-pro-greek-ext-300-normal.woff2
  src/Resources/public/fonts/source-sans-pro-greek-ext-400-italic.woff2
  src/Resources/public/fonts/source-sans-pro-greek-ext-400-normal.woff2
  src/Resources/public/fonts/source-sans-pro-greek-ext-600-italic.woff2
  src/Resources/public/fonts/source-sans-pro-greek-ext-600-normal.woff2
  src/Resources/public/fonts/source-sans-pro-greek-ext-700-normal.woff2
  src/Resources/public/fonts/source-sans-pro-latin-300-italic.woff2
  src/Resources/public/fonts/source-sans-pro-latin-300-normal.woff2
  src/Resources/public/fonts/source-sans-pro-latin-400-italic.woff2
  src/Resources/public/fonts/source-sans-pro-latin-400-normal.woff2
  src/Resources/public/fonts/source-sans-pro-latin-600-italic.woff2
  src/Resources/public/fonts/source-sans-pro-latin-600-normal.woff2
  src/Resources/public/fonts/source-sans-pro-latin-700-normal.woff2
  src/Resources/public/fonts/source-sans-pro-latin-ext-300-italic.woff2
  src/Resources/public/fonts/source-sans-pro-latin-ext-300-normal.woff2
  src/Resources/public/fonts/source-sans-pro-latin-ext-400-italic.woff2
  src/Resources/public/fonts/source-sans-pro-latin-ext-400-normal.woff2
  src/Resources/public/fonts/source-sans-pro-latin-ext-600-italic.woff2
  src/Resources/public/fonts/source-sans-pro-latin-ext-600-normal.woff2
  src/Resources/public/fonts/source-sans-pro-latin-ext-700-normal.woff2
  src/Resources/public/fonts/source-sans-pro-vietnamese-300-italic.woff2
  src/Resources/public/fonts/source-sans-pro-vietnamese-300-normal.woff2
  src/Resources/public/fonts/source-sans-pro-vietnamese-400-italic.woff2
  src/Resources/public/fonts/source-sans-pro-vietnamese-400-normal.woff2
  src/Resources/public/fonts/source-sans-pro-vietnamese-600-italic.woff2
  src/Resources/public/fonts/source-sans-pro-vietnamese-600-normal.woff2
  src/Resources/public/fonts/source-sans-pro-vietnamese-700-normal.woff2
Labels: patch

#7141 Improve jQuery code
  assets/js/Admin.js
  assets/js/app.js
  assets/js/base.js
  assets/js/jquery.confirmExit.js
  assets/js/sidebar.js
  assets/js/treeview.js
  src/Resources/public/app.js
Labels: pedantic

#7146 3.x into Master
  CHANGELOG.md
  src/Admin/AbstractAdmin.php
  src/Admin/AbstractAdminExtension.php
  src/Admin/AdminExtensionInterface.php
Labels: pedantic

#7147 Drop support for phpcr
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
Labels: major

#7149 Remove Countable from execute return type
  src/Datagrid/ProxyQueryInterface.php
  src/Model/ModelManagerInterface.php
Labels: patch

#6950 Add ParamConverter for Admins
  composer.json
  docs/cookbook/recipe_decouple_crud_controller.rst
  docs/index.rst
  src/DependencyInjection/SonataAdminExtension.php
  src/Request/AdminFetcher.php
  src/Request/AdminFetcherInterface.php
  src/Request/ParamConverter/AdminParamConverter.php
  src/Resources/config/core.php
  src/Resources/config/param_converter.php
  tests/App/Admin/TestingParamConverterAdmin.php
  tests/App/AppKernel.php
  tests/App/Controller/InvokableController.php
  tests/App/Controller/ParamConverterController.php
  tests/App/config/services.yml
  tests/DependencyInjection/SonataAdminExtensionTest.php
  tests/Functional/Controller/ParamConverterControllerTest.php
  tests/Request/AdminFetcherTest.php
  tests/Request/ParamConverter/AdminParamConverterTest.php
Labels: minor

#7153 Remove psalm bug fix for empty array
  composer.json
  src/FieldDescription/FieldDescriptionInterface.php
Labels: pedantic

#7162 Fix fonts route
  src/Resources/public/css/styles.css
Labels: patch

#7167 Moment variable is now global
  assets/js/app.js
  src/Resources/public/app.js
Labels: pedantic

#7169 enhance list documentation for virtual fields
  docs/reference/action_list.rst
Labels: docs

#7171 Fix lint
  src/Admin/AdminExtensionInterface.php
  src/DependencyInjection/Admin/TaggedAdminInterface.php
Labels: pedantic

#7172 3.x into Master
  composer.json
  docs/reference/action_list.rst
  src/FieldDescription/FieldDescriptionInterface.php
Labels: pedantic

#7077 Add default_admin_services node
  docs/cookbook/recipe_overwrite_admin_configuration.rst
  docs/reference/configuration.rst
  docs/reference/templates.rst
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataAdminExtension.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/SonataAdminExtensionTest.php
Labels: minor

#7181 Fix countResult of SimplePager
  src/Datagrid/SimplePager.php
  tests/Datagrid/SimplePagerTest.php
Labels: patch

#7164 Fix "show_empty_boxes" option in the documentation
  docs/reference/configuration.rst
Labels: docs

#7196 Fixed select2 ModelAutocompleteType
  src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
Labels: patch

#7191 Use adminFetcher in Actions
  src/Action/AppendFormFieldElementAction.php
  src/Action/GetShortObjectDescriptionAction.php
  src/Action/RetrieveAutocompleteItemsAction.php
  src/Action/RetrieveFormFieldElementAction.php
  src/Action/SetObjectFieldValueAction.php
  src/Resources/config/actions.php
  src/Resources/views/CRUD/Association/edit_many_script.html.twig
  src/Resources/views/CRUD/Association/edit_many_to_one.html.twig
  src/Resources/views/CRUD/Association/edit_one_script.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_one.html.twig
  src/Resources/views/CRUD/base_list_field.html.twig
  src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
  src/Resources/views/Form/form_admin_fields.html.twig
  tests/Action/AppendFormFieldElementActionTest.php
  tests/Action/GetShortObjectDescriptionActionTest.php
  tests/Action/RetrieveAutocompleteItemsActionTest.php
  tests/Action/RetrieveFormFieldElementActionTest.php
  tests/Action/SetObjectFieldValueActionTest.php
  tests/Controller/HelperControllerTest.php
Labels: minor

#7198 Fix arrow function scope issue
  assets/js/admin.js
  src/Resources/public/app.js
Labels: patch

#7202 Missing comma & bracket
  src/Resources/views/CRUD/Association/edit_many_script.html.twig
Labels: patch

#7203 Fix missing comma and bracket
  src/Resources/views/CRUD/Association/edit_many_script.html.twig
Labels: patch

#7205 Add missing generic phpdoc
  src/Admin/AdminInterface.php
Labels: major

#7206 Allow sortable option as string
  src/FieldDescription/FieldDescriptionInterface.php
Labels: patch

#7208 Fix keep-open menu option
  assets/scss/styles.scss
  src/Resources/public/app.css
Labels: major

#7212 Avoid github security alert
  composer.json
Labels: pedantic

#7213 3.X into Master
  composer.json
Labels: pedantic

#7214 Allow null mappingType
  src/FieldDescription/BaseFieldDescription.php
  src/FieldDescription/FieldDescriptionInterface.php
Labels: patch

#7216 Fix psalm issues
  src/Admin/AbstractAdmin.php
  src/Admin/AbstractAdminExtension.php
  src/Admin/AdminExtensionInterface.php
  src/Admin/AdminInterface.php
  src/Command/CreateClassCacheCommand.php
  src/Datagrid/DatagridMapper.php
  src/Datagrid/ListMapper.php
  src/DependencyInjection/Admin/AbstractTaggedAdmin.php
  src/DependencyInjection/Admin/TaggedAdminInterface.php
  src/Form/FormMapper.php
  src/Show/ShowMapper.php
Labels: pedantic

#7211 Do not lose _route_params
  src/Resources/views/CRUD/Association/edit_many_script.html.twig
  src/Resources/views/CRUD/Association/edit_many_to_one.html.twig
  src/Resources/views/CRUD/Association/edit_one_script.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_one.html.twig
  src/Resources/views/CRUD/base_list_field.html.twig
  src/Resources/views/Form/form_admin_fields.html.twig
Labels: patch

#7224 Fix for no focus on Select2 or CKEditor in modal dialog
  src/Resources/views/CRUD/Association/edit_modal.html.twig
  src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
  src/Resources/views/Form/form_admin_fields.html.twig
Labels: patch

#7223 Fix for ModelAutocompleteType does not display the previously selected value when editing an entity
  src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
Labels: patch

#7227 Improve exception message
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
Labels: pedantic

#7219 Fix order arrow scss/css
  assets/scss/layout.scss
  src/Resources/public/app.css
Labels: patch

#7220 Restrict visibility of some AbstractAdmin property and rename uniqid to uniqId
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  src/Admin/Extension/LockExtension.php
  tests/Admin/AdminTest.php
  tests/Admin/Extension/LockExtensionTest.php
  tests/Controller/CRUDControllerTest.php
  tests/Request/AdminFetcherTest.php
  tests/Route/DefaultRouteGeneratorTest.php
Labels: major
