Repository sonata-project/SonataAdminBundle, pull requests merged in 2021-04, with the labels that each got.

#7002 Allow silence deprecation in persistence bundles
  src/Admin/AbstractAdmin.php
Labels: patch

#7001 Deprecate class-based aliases
  UPGRADE-3.x.md
  src/DependencyInjection/Compiler/ObjectAclManipulatorCompilerPass.php
  src/Resources/config/commands.php
  src/Resources/config/core.php
  src/Resources/config/event_listener.php
  tests/DependencyInjection/Compiler/ObjectAclManipulatorCompilerPassTest.php
  tests/DependencyInjection/SonataAdminExtensionTest.php
Labels: minor

#7006 Fix phpstan
  src/Admin/AbstractAdmin.php
Labels: pedantic

#7003 Make compiler passes internal
  UPGRADE-3.x.md
  src/DependencyInjection/Compiler/AddAuditReadersCompilerPass.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/DependencyInjection/Compiler/AddFilterTypeCompilerPass.php
  src/DependencyInjection/Compiler/AdminMakerCompilerPass.php
  src/DependencyInjection/Compiler/AdminSearchCompilerPass.php
  src/DependencyInjection/Compiler/ExtensionCompilerPass.php
  src/DependencyInjection/Compiler/GlobalVariablesCompilerPass.php
  src/DependencyInjection/Compiler/ModelManagerCompilerPass.php
  src/DependencyInjection/Compiler/ObjectAclManipulatorCompilerPass.php
  src/DependencyInjection/Compiler/TwigStringExtensionCompilerPass.php
Labels: Needs: Upgrade note

#7010 Deprecate more service aliases
  UPGRADE-3.x.md
  src/Resources/config/core.php
Labels: minor

#7008 Changing the names of variables in the skeleton
  src/Resources/skeleton/Admin.tpl.php
Labels: patch

#7007 Add tests to filter types and fix options
  src/Form/Type/Filter/DateRangeType.php
  src/Form/Type/Filter/DateTimeRangeType.php
  src/Form/Type/Filter/DateType.php
  tests/Form/Type/Filter/BaseTypeTest.php
  tests/Form/Type/Filter/ChoiceTypeTest.php
  tests/Form/Type/Filter/DateRangeTypeTest.php
  tests/Form/Type/Filter/DateTimeRangeTypeTest.php
  tests/Form/Type/Filter/DateTimeTypeTest.php
  tests/Form/Type/Filter/DateTypeTest.php
  tests/Form/Type/Filter/DefaultTypeTest.php
  tests/Form/Type/Filter/NumberTypeTest.php
Labels: patch

#7024 Remove deprecations with symfony/http-kernel ^5.1
  src/Route/RouteCollection.php
  tests/Route/RouteCollectionTest.php
Labels: major

#7023 Upgrade to SF 5.2, drop older doctrine versions
  composer.json
Labels: major

#7028 Use form builder instance instead of mock
  tests/Datagrid/DatagridTest.php
Labels: pedantic

#7005 Show matching filters in search results
  src/Block/AdminSearchBlockService.php
  src/Resources/public/css/layout.css
  src/Resources/views/Block/block_search_result.html.twig
Labels: minor

#7047 Fix typo in asset paths, and wrong css location
  docs/reference/configuration.rst
  src/DependencyInjection/Configuration.php
  src/Resources/public/dist/components-font-awesome/css/font-awesome.min.css
  src/Resources/public/dist/manifest.json
  webpack.config.js
Labels: pedantic

#7050 Add skins to admin-lte
  src/DependencyInjection/SonataAdminExtension.php
  src/Resources/public/dist/admin-lte/css/skins/skin-black-light.min.css
  src/Resources/public/dist/admin-lte/css/skins/skin-black.min.css
  src/Resources/public/dist/admin-lte/css/skins/skin-blue-light.min.css
  src/Resources/public/dist/admin-lte/css/skins/skin-blue.min.css
  src/Resources/public/dist/admin-lte/css/skins/skin-green-light.min.css
  src/Resources/public/dist/admin-lte/css/skins/skin-green.min.css
  src/Resources/public/dist/admin-lte/css/skins/skin-purple-light.min.css
  src/Resources/public/dist/admin-lte/css/skins/skin-purple.min.css
  src/Resources/public/dist/admin-lte/css/skins/skin-red-light.min.css
  src/Resources/public/dist/admin-lte/css/skins/skin-red.min.css
  src/Resources/public/dist/admin-lte/css/skins/skin-yellow-light.min.css
  src/Resources/public/dist/admin-lte/css/skins/skin-yellow.min.css
  src/Resources/public/dist/manifest.json
  tests/DependencyInjection/SonataAdminExtensionTest.php
  webpack.config.js
Labels: pedantic

#7044 Use `FilterInterface::getOption()` from views
  src/Resources/views/CRUD/base_list.html.twig
Labels: patch

#7038 Leverage `FieldDescriptionInterface::getOption()` in views
  src/Resources/views/CRUD/Association/edit_many_script.html.twig
  src/Resources/views/CRUD/Association/edit_many_to_one.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_many.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_many_sortable_script_table.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_many_sortable_script_tabs.html.twig
  src/Resources/views/CRUD/Association/edit_one_to_one.html.twig
  src/Resources/views/CRUD/Association/list_many_to_many.html.twig
  src/Resources/views/CRUD/Association/list_many_to_one.html.twig
  src/Resources/views/CRUD/Association/list_one_to_many.html.twig
  src/Resources/views/CRUD/Association/list_one_to_one.html.twig
  src/Resources/views/CRUD/Association/show_many_to_many.html.twig
  src/Resources/views/CRUD/Association/show_many_to_one.html.twig
  src/Resources/views/CRUD/Association/show_one_to_many.html.twig
  src/Resources/views/CRUD/Association/show_one_to_one.html.twig
  src/Resources/views/CRUD/_email_link.html.twig
  src/Resources/views/CRUD/base_filter_field.html.twig
  src/Resources/views/CRUD/base_inline_edit_field.html.twig
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/CRUD/base_list_field.html.twig
  src/Resources/views/CRUD/base_list_flat_field.html.twig
  src/Resources/views/CRUD/base_show_field.html.twig
  src/Resources/views/CRUD/base_standard_edit_field.html.twig
  src/Resources/views/CRUD/display_boolean.html.twig
  src/Resources/views/CRUD/display_currency.html.twig
  src/Resources/views/CRUD/display_date.html.twig
  src/Resources/views/CRUD/display_time.html.twig
  src/Resources/views/CRUD/edit_boolean.html.twig
  src/Resources/views/CRUD/list__action.html.twig
  src/Resources/views/CRUD/list_array.html.twig
  src/Resources/views/CRUD/list_boolean.html.twig
  src/Resources/views/CRUD/list_choice.html.twig
  src/Resources/views/CRUD/list_html.html.twig
  src/Resources/views/CRUD/list_trans.html.twig
  src/Resources/views/CRUD/list_url.html.twig
  src/Resources/views/CRUD/show_array.html.twig
  src/Resources/views/CRUD/show_choice.html.twig
  src/Resources/views/CRUD/show_html.html.twig
  src/Resources/views/CRUD/show_trans.html.twig
  src/Resources/views/CRUD/show_url.html.twig
  src/Resources/views/Form/form_admin_fields.html.twig
  tests/Twig/Extension/RenderElementExtensionTest.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: minor

#7060 Copy missing select2 imgs
  src/Resources/public/dist/manifest.json
  src/Resources/public/dist/select2/select2-spinner.gif
  src/Resources/public/dist/select2/select2.png
  src/Resources/public/dist/select2/select2x2.png
  webpack.config.js
Labels: pedantic

#7061 Use AdminInterface::generateObjectUrl instead of generateUrl
  src/Resources/views/CRUD/list_outer_rows_mosaic.html.twig
Labels: pedantic

#7069 [Docs] Minor tweaks in RST syntax
  docs/reference/field_types.rst
  docs/reference/security.rst
Labels: docs

#7066 Move template param of the ModelManager to the class
  src/Admin/AdminInterface.php
  src/DependencyInjection/Admin/AbstractTaggedAdmin.php
  src/DependencyInjection/Admin/TaggedAdminInterface.php
  src/Form/DataTransformer/ArrayToModelTransformer.php
  src/Form/DataTransformer/ModelToIdPropertyTransformer.php
  src/Form/DataTransformer/ModelToIdTransformer.php
  src/Form/DataTransformer/ModelsToArrayTransformer.php
  src/Model/ModelManagerInterface.php
Labels: minor

#7071 Remove duplicated twig code
  src/Resources/views/CRUD/display_choice.html.twig
  src/Resources/views/CRUD/display_datetime.html.twig
  src/Resources/views/CRUD/display_html.html.twig
  src/Resources/views/CRUD/display_trans.html.twig
  src/Resources/views/CRUD/display_url.html.twig
  src/Resources/views/CRUD/list_choice.html.twig
  src/Resources/views/CRUD/list_html.html.twig
  src/Resources/views/CRUD/list_trans.html.twig
  src/Resources/views/CRUD/list_url.html.twig
  src/Resources/views/CRUD/show_choice.html.twig
  src/Resources/views/CRUD/show_html.html.twig
  src/Resources/views/CRUD/show_trans.html.twig
  src/Resources/views/CRUD/show_url.html.twig
  tests/Twig/Extension/RenderElementExtensionTest.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: pedantic

#7020 Add tests for label and help blocks
  src/Resources/views/Form/form_admin_fields.html.twig
  tests/Fixtures/StubTranslator.php
  tests/Form/AbstractLayoutTestCase.php
  tests/Form/AdminLayoutTest.php
Labels: pedantic

#7075 Remove unused arguments
  src/Resources/config/twig.php
Labels: pedantic

#7074 Prepare to remove usages of service_container in version 4
  src/Resources/config/twig.php
  src/Twig/Extension/TemplateRegistryExtension.php
Labels: minor

#7021 Use translation domain of admin as default for form_help
  src/Form/Extension/Field/Type/FormTypeFieldExtension.php
  src/Resources/views/Form/form_admin_fields.html.twig
  tests/Form/AdminLayoutTest.php
Labels: patch

#7080 Allow `AbstractAdmin::getListMode()` to return the default value if the request hasn't a session
  src/Admin/AbstractAdmin.php
  tests/Admin/AdminTest.php
Labels: patch

#7078 Extract strings to constants
  docs/cookbook/recipe_sortable_listing.rst
  docs/reference/action_list.rst
  src/Action/RetrieveAutocompleteItemsAction.php
  src/Admin/AbstractAdmin.php
  src/Block/AdminStatsBlockService.php
  src/Datagrid/Datagrid.php
  src/Datagrid/DatagridInterface.php
  src/Form/Type/ModelAutocompleteType.php
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/Pager/base_results.html.twig
  tests/Action/RetrieveAutocompleteItemsActionTest.php
  tests/Admin/AdminTest.php
  tests/Controller/HelperControllerTest.php
  tests/Datagrid/DatagridTest.php
  tests/Filter/Persister/SessionFilterPersisterTest.php
  tests/Form/Type/ModelAutocompleteTypeTest.php
  tests/Twig/Extension/PaginationExtensionTest.php
  tests/Util/ParametersManipulatorTest.php
Labels: minor

#7073 Move css to root assets folder
  assets/scss/app.scss
  assets/scss/flashmessage.scss
  assets/scss/layout.scss
  assets/scss/styles.scss
  assets/scss/tree.scss
  docs/reference/configuration.rst
  package.json
  src/DependencyInjection/Configuration.php
  src/Resources/public/css/colors.css
  src/Resources/public/dist/app.css
  src/Resources/public/dist/entrypoints.json
  src/Resources/public/dist/manifest.json
  webpack.config.js
  yarn.lock
Labels: major

#7093 Fix matching filter links in search results
  src/Resources/public/css/layout.css
  src/Resources/views/Block/block_search_result.html.twig
Labels: patch

#7088 Add render_breadcrumbs and render_breadcrumbs_for_title twig functions
  UPGRADE-3.x.md
  src/Action/DashboardAction.php
  src/Action/SearchAction.php
  src/Controller/CRUDController.php
  src/Resources/config/actions.php
  src/Resources/config/twig.php
  src/Resources/views/Breadcrumb/breadcrumb.html.twig
  src/Resources/views/Breadcrumb/breadcrumb_title.html.twig
  src/Resources/views/standard_layout.html.twig
  src/Twig/Extension/BreadcrumbsExtension.php
  tests/Action/SearchActionTest.php
  tests/Twig/Extension/BreadcrumbsExtensionTest.php
Labels: minor

#7102 Extract magic numbers
  src/Admin/AbstractAdmin.php
Labels: pedantic

#7089 Enable auto prefixer with standard configuration
  assets/scss/styles.scss
  assets/scss/tree.scss
  package.json
  postcss.config.js
  src/Resources/public/dist/app.css
  src/Resources/public/dist/moment/locale/mr.js
  src/Resources/public/dist/moment/locale/sk.js
  src/Resources/public/dist/moment/locale/tzl.js
  src/Resources/public/dist/select2/select2.full.min.js
  webpack.config.js
  yarn.lock
Labels: pedantic

#7110 Allow to use display_* templates without field_description
  src/Resources/views/CRUD/_email_link.html.twig
  src/Resources/views/CRUD/display_boolean.html.twig
  src/Resources/views/CRUD/display_choice.html.twig
  src/Resources/views/CRUD/display_currency.html.twig
  src/Resources/views/CRUD/display_date.html.twig
  src/Resources/views/CRUD/display_datetime.html.twig
  src/Resources/views/CRUD/display_email.html.twig
  src/Resources/views/CRUD/display_html.html.twig
  src/Resources/views/CRUD/display_time.html.twig
  src/Resources/views/CRUD/display_trans.html.twig
  src/Resources/views/CRUD/display_url.html.twig
  src/Resources/views/CRUD/history_revision_timestamp.html.twig
  src/Resources/views/CRUD/list_boolean.html.twig
  src/Resources/views/CRUD/list_choice.html.twig
  src/Resources/views/CRUD/list_currency.html.twig
  src/Resources/views/CRUD/list_date.html.twig
  src/Resources/views/CRUD/list_datetime.html.twig
  src/Resources/views/CRUD/list_email.html.twig
  src/Resources/views/CRUD/list_html.html.twig
  src/Resources/views/CRUD/list_percent.html.twig
  src/Resources/views/CRUD/list_time.html.twig
  src/Resources/views/CRUD/list_trans.html.twig
  src/Resources/views/CRUD/list_url.html.twig
  src/Resources/views/CRUD/show_boolean.html.twig
  src/Resources/views/CRUD/show_choice.html.twig
  src/Resources/views/CRUD/show_currency.html.twig
  src/Resources/views/CRUD/show_date.html.twig
  src/Resources/views/CRUD/show_datetime.html.twig
  src/Resources/views/CRUD/show_email.html.twig
  src/Resources/views/CRUD/show_html.html.twig
  src/Resources/views/CRUD/show_percent.html.twig
  src/Resources/views/CRUD/show_time.html.twig
  src/Resources/views/CRUD/show_trans.html.twig
  src/Resources/views/CRUD/show_url.html.twig
Labels: minor

#7022 Add FilterData
  UPGRADE-4.0.md
  docs/reference/action_list.rst
  phpstan-baseline.neon
  psalm.xml
  src/Filter/FilterInterface.php
  src/Filter/Model/FilterData.php
  src/Form/DataTransformer/FilterDataTransformer.php
  src/Form/Type/Filter/ChoiceType.php
  src/Form/Type/Filter/DateRangeType.php
  src/Form/Type/Filter/DateTimeRangeType.php
  src/Form/Type/Filter/DateTimeType.php
  src/Form/Type/Filter/DateType.php
  src/Form/Type/Filter/DefaultType.php
  src/Form/Type/Filter/FilterDataType.php
  src/Form/Type/Filter/NumberType.php
  tests/Datagrid/DatagridTest.php
  tests/Filter/Model/FilterDataTest.php
  tests/Fixtures/Filter/BarFilter.php
  tests/Fixtures/Filter/FooFilter.php
  tests/Form/DataTransformer/FilterDataTransformerTest.php
  tests/Form/Type/Filter/DateTimeRangeTypeTest.php
Labels: major

#7094 Use phpstan-type instead of psalm
  composer.json
  src/Admin/AbstractAdmin.php
  src/Admin/Pool.php
  src/FieldDescription/BaseFieldDescription.php
  src/FieldDescription/FieldDescriptionFactoryInterface.php
  src/FieldDescription/FieldDescriptionInterface.php
  src/Model/ModelManagerInterface.php
  src/SonataConfiguration.php
Labels: pedantic

#7112 Restrict return type of execute method
  src/Datagrid/ProxyQueryInterface.php
  src/Datagrid/SimplePager.php
  src/Form/ChoiceList/ModelChoiceLoader.php
  src/Form/DataTransformer/ModelsToArrayTransformer.php
  src/Model/ModelManagerInterface.php
  src/Util/TraversableToCollection.php
  tests/Datagrid/SimplePagerTest.php
Labels: minor

#7092 Restrict datagridBuilder type to class-string and add Template
  src/Builder/DatagridBuilderInterface.php
  src/Builder/FormContractorInterface.php
  src/Datagrid/DatagridMapper.php
  src/Model/LockInterface.php
  src/Model/ModelManagerInterface.php
Labels: minor

#7118 [RFC] Add FilterData
  src/Filter/Model/FilterData.php
  tests/Filter/Model/FilterDataTest.php
Labels: minor

#7115 Use setListModes instead of showMosaicButton
  src/DependencyInjection/Admin/AbstractTaggedAdmin.php
  src/DependencyInjection/Admin/TaggedAdminInterface.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  tests/Admin/AdminTest.php
Labels: minor

#7065 Fix bug "Field "FIELD" has already been rendered" in /CRUD/Associatio…
  src/Resources/views/CRUD/Association/edit_many_to_many.html.twig
Labels: patch

#7120 Fix tests
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
Labels: pedantic

#7121 Stop trying to foreach on ArrayAccess
  src/Form/DataTransformer/ModelToIdPropertyTransformer.php
Labels: patch

#7125 Fix OneToOne template
  src/Resources/views/CRUD/Association/edit_one_to_one.html.twig
Labels: patch

#7128 Fix displays of the link to go to page 1
  src/Resources/translations/SonataAdminBundle.bs.xliff
  src/Resources/translations/SonataAdminBundle.fr.xliff
  src/Resources/translations/SonataAdminBundle.hr.xliff
  src/Resources/translations/SonataAdminBundle.hu.xliff
  src/Resources/translations/SonataAdminBundle.it.xliff
  src/Resources/translations/SonataAdminBundle.ja.xliff
  src/Resources/translations/SonataAdminBundle.lb.xliff
  src/Resources/translations/SonataAdminBundle.lt.xliff
  src/Resources/translations/SonataAdminBundle.lv.xliff
  src/Resources/translations/SonataAdminBundle.nl.xliff
  src/Resources/translations/SonataAdminBundle.no.xliff
  src/Resources/translations/SonataAdminBundle.pl.xliff
  src/Resources/translations/SonataAdminBundle.pt.xliff
  src/Resources/translations/SonataAdminBundle.pt_BR.xliff
  src/Resources/translations/SonataAdminBundle.ro.xliff
  src/Resources/translations/SonataAdminBundle.ru.xliff
  src/Resources/translations/SonataAdminBundle.sk.xliff
  src/Resources/translations/SonataAdminBundle.sl.xliff
  src/Resources/translations/SonataAdminBundle.sr_Cyrl.xliff
  src/Resources/translations/SonataAdminBundle.sr_Latn.xliff
  src/Resources/translations/SonataAdminBundle.sv_SE.xliff
  src/Resources/translations/SonataAdminBundle.tr.xliff
  src/Resources/translations/SonataAdminBundle.uk.xliff
  src/Resources/translations/SonataAdminBundle.zh_CN.xliff
  src/Resources/translations/SonataAdminBundle.zh_HK.xliff
  src/Resources/views/CRUD/base_list.html.twig
Labels: patch

#7106 Move Sonata javascript to assets directory
  .eslintrc.js
  .eslintrc.json
  assets/js/Admin.js
  assets/js/app.js
  assets/js/base.js
  assets/js/jquery.confirmExit.js
  assets/js/sidebar.js
  assets/js/treeview.js
  src/DependencyInjection/Configuration.php
  src/Resources/public/Admin.js
  src/Resources/public/base.js
  src/Resources/public/dist/app.js
  src/Resources/public/jquery.confirmExit.js
  src/Resources/public/treeview.js
  webpack.config.js
Labels: major

#7130 Do not try to find a route for `show` and `edit`
  src/Resources/views/CRUD/display_url.html.twig
  tests/Twig/Extension/SonataAdminExtensionTest.php
Labels: patch

#7135 Bug - Removed do-not-use alias for exporter service
  src/Controller/CRUDController.php
Labels: patch

#7136 Fix some fa icons and add compatibility layer to admin-lte
  assets/js/Admin.js
  assets/scss/admin-lte-fas.scss
  assets/scss/app.scss
  src/Block/AdminStatsBlockService.php
  src/Resources/public/app.css
  src/Resources/public/app.js
  src/Resources/views/Block/block_admin_preview.html.twig
  src/Resources/views/Block/block_stats.html.twig
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/CRUD/batch_confirmation.html.twig
  src/Resources/views/Menu/sonata_menu.html.twig
  src/Resources/views/standard_layout.html.twig
  tests/Block/AdminStatsBlockServiceTest.php
Labels: major
