Repository sonata-project/SonataAdminBundle, pull requests merged in 2022-09, with the labels that each got.

#7926 Add default actions translation for list view
  src/Resources/translations/SonataAdminBundle.ar.xliff
  src/Resources/translations/SonataAdminBundle.bg.xliff
  src/Resources/translations/SonataAdminBundle.bs.xliff
  src/Resources/translations/SonataAdminBundle.ca.xliff
  src/Resources/translations/SonataAdminBundle.cs.xliff
  src/Resources/translations/SonataAdminBundle.de.xliff
  src/Resources/translations/SonataAdminBundle.en.xliff
  src/Resources/translations/SonataAdminBundle.es.xliff
  src/Resources/translations/SonataAdminBundle.eu.xliff
  src/Resources/translations/SonataAdminBundle.fa.xliff
  src/Resources/translations/SonataAdminBundle.fr.xliff
  src/Resources/translations/SonataAdminBundle.hr.xliff
  src/Resources/translations/SonataAdminBundle.hu.xliff
  src/Resources/translations/SonataAdminBundle.it.xliff
  src/Resources/translations/SonataAdminBundle.ja.xliff
  src/Resources/translations/SonataAdminBundle.lb.xliff
  src/Resources/translations/SonataAdminBundle.lt.xliff
  src/Resources/translations/SonataAdminBundle.lv.xliff
  src/Resources/translations/SonataAdminBundle.nl.xliff
  src/Resources/translations/SonataAdminBundle.no.xliff
  src/Resources/translations/SonataAdminBundle.pl.xliff
  src/Resources/translations/SonataAdminBundle.pt.xliff
  src/Resources/translations/SonataAdminBundle.pt_BR.xliff
  src/Resources/translations/SonataAdminBundle.ro.xliff
  src/Resources/translations/SonataAdminBundle.ru.xliff
  src/Resources/translations/SonataAdminBundle.sk.xliff
  src/Resources/translations/SonataAdminBundle.sl.xliff
  src/Resources/translations/SonataAdminBundle.sr_Cyrl.xliff
  src/Resources/translations/SonataAdminBundle.sr_Latn.xliff
  src/Resources/translations/SonataAdminBundle.sv_SE.xliff
  src/Resources/translations/SonataAdminBundle.tr.xliff
  src/Resources/translations/SonataAdminBundle.uk.xliff
  src/Resources/translations/SonataAdminBundle.zh_CN.xliff
  src/Resources/translations/SonataAdminBundle.zh_HK.xliff
Labels: patch

#7924 Replace pixassociates/sortable-behavior-bundle to runroom-packages/sortable-behavior-bundle
  docs/cookbook/recipe_sortable_listing.rst
Labels: docs

#7927 Deprecate BCLabelTranslatorStrategy
  UPGRADE-4.x.md
  src/Resources/config/core.php
  src/Translator/BCLabelTranslatorStrategy.php
  tests/Translator/BCLabelTranslatorStrategyTest.php
Labels: minor

#7932 Remove sonataIntl dependency
  composer.json
Labels: pedantic

#7933 Update UPGRADE-3.x.md
  UPGRADE-3.x.md
Labels: pedantic

#7922 Improve error handling in Ajax
  UPGRADE-4.x.md
  composer.json
  src/Controller/CRUDController.php
  src/Form/FormErrorIteratorToConstraintViolationList.php
  tests/Controller/CRUDControllerTest.php
  tests/Form/FormErrorIteratorToConstraintViolationListTest.php
  tests/Maker/AdminMakerTest.php
  tests/Twig/Extension/RenderElementExtensionTest.php
  tests/Twig/RenderElementRuntimeTest.php
Labels: minor
