Repository sonata-project/SonataAdminBundle, pull requests merged in 2022-04, with the labels that each got.

#7786 Fix phpstan
  phpstan-baseline.neon
Labels: pedantic

#7790 Improve phpdoc
  src/Model/ModelManagerInterface.php
Labels: pedantic

#7791 CallbackFilter returns a boolean
  docs/reference/action_list.rst
Labels: docs

#7796 Test with bleeding edge
  phpstan.neon.dist
Labels: pedantic

#7792 fix SonataBlockBundle deprecations
  composer.json
  src/Block/AdminListBlockService.php
  src/Block/AdminPreviewBlockService.php
  src/Block/AdminSearchBlockService.php
  src/Block/AdminStatsBlockService.php
  tests/App/AppKernel.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
  tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php
Labels: minor

#7798 Fix PHP 8.1 compatibility in 3.x
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/symfony-lint.yaml
  docs/requirements.txt
  src/Action/GetShortObjectDescriptionAction.php
  src/Admin/AbstractAdmin.php
  src/Admin/AdminExtensionInterface.php
  src/Admin/AdminInterface.php
  src/Builder/FormContractorInterface.php
  src/Controller/CRUDController.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/DependencyInjection/Compiler/AddFilterTypeCompilerPass.php
  src/DependencyInjection/SonataAdminExtension.php
  src/FieldDescription/FieldDescriptionCollection.php
  src/FieldDescription/FieldDescriptionRegistryInterface.php
  src/Form/Type/ModelAutocompleteType.php
  src/Form/Type/ModelType.php
  src/Mapper/MapperInterface.php
  src/Menu/Provider/GroupMenuProvider.php
  src/Templating/MutableTemplateRegistry.php
  src/Templating/MutableTemplateRegistryAwareInterface.php
  src/Templating/MutableTemplateRegistryInterface.php
  src/Templating/TemplateRegistryAwareInterface.php
  src/Twig/Extension/CanonicalizeExtension.php
  src/Twig/Extension/RenderElementExtension.php
  src/Twig/Extension/SecurityExtension.php
  src/Twig/Extension/SonataAdminExtension.php
  src/Twig/Extension/XEditableExtension.php
  tests/Controller/CRUDControllerTest.php
  tests/DependencyInjection/Compiler/AddFilterTypeCompilerPassTest.php
  tests/Form/Type/ModelTypeTest.php
  tests/Menu/Integration/TabMenuTest.php
  tests/Security/Handler/RoleSecurityHandlerTest.php
  tests/Templating/MutableTemplateRegistryTest.php
  tests/Twig/Extension/RenderElementExtensionTest.php
Labels: patch

#7802 Fix build
  rector.php
  tests/Form/Type/ModelTypeTest.php
  tests/Route/DefaultRouteGeneratorTest.php
  tests/Route/RoutesCacheWarmUpTest.php
Labels: pedantic

#7804 4.11.1
  CHANGELOG.md
Labels: pedantic
