Repository sonata-project/SonataAdminBundle, pull requests merged in 2022-07, with the labels that each got.

#7880 Update SonataAdmin examples
  docs/index.rst
Labels: docs

#7867 Allow to configure routeName and routePattern dynamically
  docs/reference/routing.rst
  src/Admin/AbstractAdmin.php
  tests/App/Admin/AdminAsParameterAdmin.php
  tests/App/Admin/EmptyAdmin.php
  tests/App/Admin/FooAdminWithCustomController.php
  tests/Fixtures/Admin/CommentWithCustomRouteAdmin.php
  tests/Fixtures/Admin/PostWithCustomRouteAdmin.php
Labels: minor

#7886 Add support for exporter 3
  composer.json
Labels: minor

#7889 Update doc
  docs/reference/action_export.rst
Labels: docs

#7890 Do not try to check access for created object
  src/Controller/CRUDController.php
  tests/Controller/CRUDControllerTest.php
Labels: patch

#7887 Add support for doctrine-extensions 2
  composer.json
Labels: minor

#7892 Fix comment
  src/DependencyInjection/SonataAdminExtension.php
Labels: pedantic

#7885 Fix menu in long-running process (RoadRunner, ReactPHP, Amphp)
  src/FieldDescription/TypeGuesserChain.php
  src/Resources/config/menu.php
  tests/App/EventListener/ConfigureMenu.php
  tests/Functional/Controller/MenuTest.php
Labels: patch
