Repository sonata-project/SonataAdminBundle, pull requests merged in 2022-02, with the labels that each got.

#7720 Remove demo link
  docs/index.rst
Labels: docs

#7721 Fix psalm tests
  psalm-baseline.xml
  src/Admin/AdminExtensionInterface.php
  src/Admin/AdminHelper.php
  src/Admin/UrlGeneratorInterface.php
  src/Controller/CRUDController.php
  src/Datagrid/DatagridInterface.php
  src/Filter/FilterInterface.php
  src/Filter/Model/FilterData.php
  src/Form/DataTransformer/ArrayToModelTransformer.php
  src/Form/DataTransformer/FilterDataTransformer.php
  src/Form/DataTransformer/ModelToIdPropertyTransformer.php
  src/Form/DataTransformer/ModelsToArrayTransformer.php
  src/Route/RouteGeneratorInterface.php
  src/Twig/RenderElementRuntime.php
  src/Util/ObjectAclManipulator.php
  tests/Fixtures/Entity/FooToStringNull.php
  tests/Form/AbstractLayoutTestCase.php
  tests/Form/DataTransformer/FilterDataTransformerTest.php
Labels: pedantic

#7731 Remove useless psalm-suppress
  src/Controller/CRUDController.php
Labels: pedantic

#7733 Fix builds
  src/BCLayer/BCUserInterface.php
Labels: pedantic

#7736 Update frontend
  .github/workflows/frontend.yaml
  .gitignore
  .stylelintrc.js
  CONTRIBUTING.md
  assets/js/admin.js
  assets/scss/layout.scss
  assets/scss/styles.scss
  assets/scss/tree.scss
  package-lock.json
  package.json
  postcss.config.js
  src/Resources/public/app.css
  src/Resources/public/app.js
  webpack.config.js
  yarn.lock
Labels: pedantic

#7739 Add prettier
  .eslintrc.js
  .github/workflows/frontend.yaml
  .github/workflows/stale.yaml
  .prettierignore
  .stylelintrc.js
  CONTRIBUTING.md
  assets/js/admin.js
  assets/js/treeview.js
  assets/scss/app.scss
  assets/scss/layout.scss
  assets/scss/styles.scss
  assets/scss/tree.scss
  package-lock.json
  package.json
  prettier.config.js
  webpack.config.js
Labels: pedantic

#7744 Stop using deprecated SourceIteratorInterface
  .github/workflows/test.yaml
  composer.json
  src/Admin/AbstractAdmin.php
  src/Admin/AdminInterface.php
  src/Exporter/DataSourceInterface.php
  tests/Admin/AdminTest.php
  tests/App/Exporter/DataSource.php
  tests/Controller/CRUDControllerTest.php
Labels: minor

#7746 Remove isNew occurence in the doc
  docs/cookbook/recipe_dynamic_form_modification.rst
Labels: docs

#7725 Allow to have an other default list mode than list
  src/Admin/AbstractAdmin.php
  src/DependencyInjection/Admin/AbstractTaggedAdmin.php
  src/DependencyInjection/Admin/TaggedAdminInterface.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/Resources/views/CRUD/base_list.html.twig
  src/Resources/views/ajax_layout.html.twig
  src/Resources/views/standard_layout.html.twig
  tests/Admin/AdminTest.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
Labels: minor

#7730 [RFC] Add TemplateType
  docs/reference/action_create_edit.rst
  docs/reference/action_list.rst
  docs/reference/action_show.rst
  src/Form/Type/TemplateType.php
  src/Resources/views/Form/form_admin_fields.html.twig
  tests/App/Admin/FooAdmin.php
  tests/App/AppKernel.php
  tests/App/templates/foo/custom_field.html.twig
Labels: minor

#7749 Remove modelClass and Controller from services configuration of admins
  docs/getting_started/creating_an_admin.rst
  src/Manipulator/ServicesManipulator.php
  tests/Manipulator/ServicesManipulatorTest.php
Labels: minor

#7757 Remove duplicate form_help
  src/Resources/views/Form/form_admin_fields.html.twig
Labels: patch

#7756 Solve some phpstan 9 issues
  src/Block/AdminStatsBlockService.php
  src/Controller/CRUDController.php
  src/Datagrid/Datagrid.php
  src/Datagrid/DatagridMapper.php
  src/Datagrid/ListMapper.php
  src/Form/DataTransformerResolver.php
  src/Form/FormMapper.php
  src/Menu/Matcher/Voter/ActiveVoter.php
  src/Menu/Provider/GroupMenuProvider.php
  src/Show/ShowMapper.php
  src/Twig/RenderElementRuntime.php
  tests/Controller/CRUDControllerTest.php
  tests/Menu/Matcher/Voter/AbstractVoterTest.php
  tests/Menu/Matcher/Voter/ActiveVoterTest.php
  tests/Menu/Matcher/Voter/AdminVoterTest.php
Labels: pedantic
