Repository sonata-project/SonataAdminBundle, pull requests merged in 2022-03, with the labels that each got.

#7760 Add missing use for example CategoryAdmin
  docs/getting_started/creating_an_admin.rst
Labels: docs

#7766 Avoid multiple call to Admin::getObject and ModelManager::find
  src/Controller/CRUDController.php
  tests/Controller/CRUDControllerTest.php
Labels: patch

#7764 Rely on PropertyAccessor in the ObjectManipulator
  src/Manipulator/ObjectManipulator.php
  tests/Admin/AdminHelperTest.php
  tests/FieldDescription/BaseFieldDescriptionTest.php
  tests/Form/Type/AdminTypeTest.php
  tests/Manipulator/ObjectManipulatorTest.php
Labels: pedantic

#7775 Fix build
  composer.json
  docs/requirements.txt
  phpstan-baseline.neon
  tests/Form/DataTransformer/ArrayToModelTransformerTest.php
  tests/Form/DataTransformer/ModelToIdTransformerTest.php
Labels: pedantic

#7776 Fix list of items when using inheritance
  phpstan-baseline.neon
  src/Resources/views/CRUD/base_list.html.twig
Labels: patch

#7779 Fix phpdoc about parentAssociationMappings
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Datagrid/ProxyQueryInterface.php
  src/FieldDescription/BaseFieldDescription.php
  tests/Datagrid/DatagridTest.php
Labels: patch
