Repository sonata-project/SonataAdminBundle, pull requests merged in 2022-10, with the labels that each got.

#7939 Fix baseline
  phpstan-baseline.neon
Labels: pedantic

#7941 Shows a deprecation message when user applies sonata.admin tag to the same service more than once
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
Labels: minor

#7940 Fix an issue that exception is thrown when the admin code is different from its service id
  src/Admin/Pool.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
Labels: minor

#7947 Fix cs
  src/Manipulator/ServicesManipulator.php
Labels: pedantic

#7943 Replace calls to deprecated method Pool::getAdminServiceIds with Pool::getAdminServiceCodes
  src/Command/GenerateObjectAclCommand.php
  src/Command/ListAdminCommand.php
  src/Command/SetupAclCommand.php
  src/Controller/CRUDController.php
  src/Route/AdminPoolLoader.php
  src/Route/RoutesCacheWarmUp.php
  src/Translator/Extractor/AdminExtractor.php
  tests/Admin/PoolTest.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
  tests/Translator/Extractor/AdminExtractorTest.php
Labels: pedantic

#7948 Attach the xhr violation error to the form field
  src/Resources/views/CRUD/Association/edit_many_script.html.twig
Labels: patch

#7949 Make serializer a require dependency
  composer.json
Labels: patch

#7937 Add support of "priority" attribute in service tag definitions
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
Labels: minor

#7952 Fix incorrect model class to service lookup array
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
Labels: patch
