Repository sonata-project/SonataAdminBundle, pull requests merged in 2022-11, with the labels that each got.

#7962 `AbstractAdmin::setSubject()` should use `getModelClass()` instead of `getClass()`
  src/Admin/AbstractAdmin.php
  tests/Admin/AdminTest.php
  tests/Fixtures/Bundle/Entity/NewsPost.php
Labels: patch

#7960 Allow doctrine/collections 2
  composer.json
Labels: minor

#7959 Allow a null limit for findRevisionHistory in next major
  src/Model/AuditReaderInterface.php
Labels: pedantic

#7967 Improve has method with annotation
  src/Admin/AbstractAdmin.php
  src/DependencyInjection/Admin/AbstractTaggedAdmin.php
  src/FieldDescription/BaseFieldDescription.php
  src/Filter/Filter.php
Labels: pedantic

#7961 ChoiceFieldMaskType inside CollectionType does not work - bugfix
  src/Resources/views/Form/form_admin_fields.html.twig
Labels: patch

#7970 Improve AdminExtension doc
  docs/getting_started/the_form_view.rst
  docs/images/customize_admin__adding_position_field.png
  docs/images/customize_admin__reorder_positon_field.png
  docs/reference/extensions.rst
Labels: docs
