Repository sonata-project/SonataAdminBundle, pull requests merged in 2022-08, with the labels that each got.

#7894 Add support for twig-extensions 2
  composer.json
Labels: minor

#7898 Fix psalm
  src/FieldDescription/TypeGuesserChain.php
Labels: pedantic

#7881 Docs: remove/warn about references to FOSUSerBundle.
  docs/reference/security.rst
Labels: docs

#7899 improved the AdminMaker using services input option if set as default
  src/Maker/AdminMaker.php
Labels: patch

#7903 Update code for new config linter
  .php-cs-fixer.dist.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/FieldDescription/BaseFieldDescription.php
  src/Twig/RenderElementRuntime.php
  tests/Controller/CRUDControllerTest.php
  tests/Fixtures/FieldDescription/FieldDescription.php
  tests/Form/AdminLayoutTest.php
  tests/Twig/Extension/RenderElementExtensionTest.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
  tests/Twig/RenderElementRuntimeTest.php
  tests/Twig/SonataAdminRuntimeTest.php
Labels: pedantic

#7906 Introduce ProxyResolverInterface
  src/Admin/AbstractAdmin.php
  src/BCLayer/BCHelper.php
  src/Form/ChoiceList/ModelChoiceLoader.php
  src/Form/DataTransformer/ModelToIdPropertyTransformer.php
  src/Form/DataTransformer/ModelsToArrayTransformer.php
  src/Model/ProxyResolverInterface.php
  src/Twig/SonataAdminRuntime.php
  tests/Admin/AdminTest.php
  tests/Form/FormMapperTest.php
Labels: minor

#7909 Make ProxyQueryInterface generic
  src/Admin/AbstractAdmin.php
  src/Admin/AbstractAdminExtension.php
  src/Admin/AdminExtensionInterface.php
  src/Admin/AdminInterface.php
  src/ArgumentResolver/ProxyQueryResolver.php
  src/Controller/CRUDController.php
  src/Datagrid/DatagridMapper.php
  src/Datagrid/ProxyQueryInterface.php
  src/DependencyInjection/Admin/AbstractTaggedAdmin.php
  src/DependencyInjection/Admin/TaggedAdminInterface.php
  src/Event/BatchActionEvent.php
  src/Event/ConfigureQueryEvent.php
  src/Exporter/DataSourceInterface.php
  src/Filter/FilterInterface.php
  src/Model/ModelManagerInterface.php
  src/Search/SearchHandler.php
  tests/App/Builder/DatagridBuilder.php
  tests/App/Datagrid/Pager.php
  tests/App/Datagrid/ProxyQuery.php
  tests/Datagrid/DatagridMapperTest.php
  tests/Datagrid/DatagridTest.php
  tests/Datagrid/PagerTest.php
  tests/Datagrid/SimplePagerTest.php
  tests/Event/ConfigureQueryEventTest.php
  tests/Fixtures/Controller/BatchAdminController.php
  tests/Fixtures/Controller/BatchOtherController.php
Labels: minor, Needs: Documentation

#7912 Remove FosUser from the doc
  docs/cookbook/recipe_sonata_admin_without_user_bundle.rst
  docs/reference/saving_hooks.rst
  docs/reference/security.rst
Labels: docs

#7913 Add support for Expression
  src/Security/Handler/AclSecurityHandler.php
  src/Security/Handler/RoleSecurityHandler.php
  src/Security/Handler/SecurityHandlerInterface.php
  tests/Security/Handler/RoleSecurityHandlerTest.php
Labels: minor
