Repository sonata-project/SonataAdminBundle, pull requests merged in 2022-01, with the labels that each got.

#7685 Add support for translation-contracts v3
  composer.json
  src/Action/AppendFormFieldElementAction.php
  src/Action/RetrieveFormFieldElementAction.php
  src/Controller/CRUDController.php
Labels: minor

#7701 Fix phpstan issues
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Block/AdminSearchBlockService.php
  src/Command/QuestionableCommand.php
  src/FieldDescription/BaseFieldDescription.php
Labels: pedantic

#7706 Added twig example for Actions Menu
  docs/reference/advanced_configuration.rst
Labels: docs

#7704 Move list field definition doc from SonataDoctrineORMAdminBundle
  docs/reference/action_list.rst
Labels: docs

#7705 Fix error on getNewInstance() when parent object property in uninitialised.
  src/Admin/AbstractAdmin.php
Labels: patch

#7713 3.x into 4.x
  CHANGELOG.md
  src/Admin/AbstractAdmin.php
Labels: pedantic

#7684 Allow to use Admin without constructor
  UPGRADE-4.x.md
  docs/cookbook/recipe_custom_action.rst
  docs/cookbook/recipe_customizing_a_mosaic_list.rst
  docs/cookbook/recipe_improve_performance_large_datasets.rst
  docs/cookbook/recipe_knp_menu.rst
  docs/cookbook/recipe_overwrite_admin_configuration.rst
  docs/cookbook/recipe_persisting_filters.rst
  docs/cookbook/recipe_row_templates.rst
  docs/cookbook/recipe_sortable_listing.rst
  docs/cookbook/recipe_sortable_sonata_type_model.rst
  docs/cookbook/recipe_workflow_integration.rst
  docs/getting_started/creating_an_admin.rst
  docs/getting_started/the_form_view.rst
  docs/reference/action_list.rst
  docs/reference/advanced_configuration.rst
  docs/reference/architecture.rst
  docs/reference/dashboard.rst
  docs/reference/form_types.rst
  docs/reference/routing.rst
  docs/reference/saving_hooks.rst
  docs/reference/search.rst
  docs/reference/templates.rst
  docs/reference/translation.rst
  src/Admin/AbstractAdmin.php
  src/DependencyInjection/Admin/AbstractTaggedAdmin.php
  src/DependencyInjection/Admin/TaggedAdminInterface.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/DependencyInjection/Compiler/ExtensionCompilerPass.php
  tests/Admin/AdminTest.php
  tests/Admin/BaseAdminModelManagerTest.php
  tests/App/config/services.yml
  tests/ArgumentResolver/AdminValueResolverTest.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
  tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php
  tests/Form/FormMapperTest.php
  tests/Show/ShowMapperTest.php
Labels: minor

#7681 Use AdminCode as key instead of id in the AdminSearchCompilerPass
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
  src/DependencyInjection/Compiler/AdminSearchCompilerPass.php
  src/SonataAdminBundle.php
  tests/DependencyInjection/Compiler/AdminSearchCompilerPassTest.php
Labels: patch

#7718 Update phpstan-baseline.neon
  phpstan-baseline.neon
Labels: pedantic
