Repository sonata-project/SonataAdminBundle, pull requests merged in 2022-12, with the labels that each got.

#7981 Replace maximumSelectionSize by maximumSelectionLength
  assets/js/admin.js
  docs/cookbook/recipe_select2.rst
  src/Resources/public/app.js
Labels: patch

#7991 Bump rector
  composer.json
  tests/Action/AppendFormFieldElementActionTest.php
  tests/Action/DashboardActionTest.php
  tests/Action/GetShortObjectDescriptionActionTest.php
  tests/Action/RetrieveAutocompleteItemsActionTest.php
  tests/Action/RetrieveFormFieldElementActionTest.php
  tests/Action/SearchActionTest.php
  tests/Action/SetObjectFieldValueActionTest.php
  tests/Admin/Extension/LockExtensionTest.php
  tests/Block/AdminListBlockServiceTest.php
  tests/Block/AdminSearchBlockServiceTest.php
  tests/Builder/AbstractFormContractorTest.php
  tests/Command/ExplainAdminCommandTest.php
  tests/Controller/CRUDControllerTest.php
  tests/Datagrid/DatagridMapperTest.php
  tests/Datagrid/DatagridTest.php
  tests/Datagrid/ListMapperTest.php
  tests/Datagrid/PagerTest.php
  tests/Datagrid/SimplePagerTest.php
  tests/Event/ConfigureEventTest.php
  tests/Event/ConfigureQueryEventTest.php
  tests/Event/PersistenceEventTest.php
  tests/Filter/Persister/SessionFilterPersisterTest.php
  tests/Form/ChoiceList/ModelChoiceLoaderTest.php
  tests/Form/DataTransformer/ArrayToModelTransformerTest.php
  tests/Form/DataTransformer/ModelToIdPropertyTransformerTest.php
  tests/Form/DataTransformer/ModelToIdTransformerTest.php
  tests/Form/DataTransformerResolverTest.php
  tests/Form/Type/ModelListTypeTest.php
  tests/Form/Type/ModelReferenceTypeTest.php
  tests/Menu/MenuBuilderTest.php
  tests/Menu/Provider/GroupMenuProviderTest.php
  tests/Request/AdminFetcherTest.php
  tests/Security/Handler/RoleSecurityHandlerTest.php
  tests/Show/ShowMapperTest.php
  tests/Translator/Extractor/AdminExtractorTest.php
  tests/Twig/BreadcrumbsRuntimeTest.php
  tests/Twig/Extension/BreadcrumbsExtensionTest.php
  tests/Twig/Extension/RenderElementExtensionTest.php
  tests/Twig/Extension/SonataAdminExtensionTest.php
  tests/Twig/RenderElementRuntimeTest.php
  tests/Twig/SonataAdminRuntimeTest.php
  tests/Util/AdminObjectAclManipulatorTest.php
  tests/Util/ObjectAclManipulatorTest.php
Labels: pedantic

#7964 Add more options to declare admin extensions
  docs/reference/configuration.rst
  docs/reference/extensions.rst
  src/DependencyInjection/Compiler/ExtensionCompilerPass.php
  src/DependencyInjection/Configuration.php
  tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php
Labels: minor
