Repository sonata-project/SonataAdminBundle, pull requests merged in 2023-10, with the labels that each got.

#8115 Fix group mapper remove method
  src/Mapper/BaseGroupedMapper.php
  tests/Fixtures/Mapper/AbstractDummyGroupedMapper.php
  tests/Mapper/BaseGroupedMapperTest.php
Labels: patch

#8116 Autoinject all admin variables
  src/Controller/CRUDController.php
  src/EventListener/AdminEventListener.php
  src/Resources/config/event_listener.php
  tests/EventListener/AdminEventListenerTest.php
Labels: minor, enhancement

#8118 Allow AdminExtractor to be used for abstract admins
  src/Translator/Extractor/AdminExtractor.php
  tests/Translator/Extractor/AdminExtractorTest.php
Labels: bug, patch
