Repository sonata-project/SonataAdminBundle, pull requests merged in 2023-03, with the labels that each got.

#8022 Remove doctrine annotations as dev dependency
  composer.json
Labels: pedantic

#8021 Bump psalm to level 5
  composer.json
  psalm-baseline.xml
  psalm.xml
  src/Admin/Pool.php
  src/Datagrid/ListMapper.php
  src/DependencyInjection/SonataAdminExtension.php
  src/FieldDescription/BaseFieldDescription.php
  src/Form/DataTransformer/ArrayToModelTransformer.php
  src/Form/DataTransformer/ModelToIdPropertyTransformer.php
  src/Form/DataTransformer/ModelsToArrayTransformer.php
  src/Form/DataTransformerResolver.php
  src/Form/DataTransformerResolverInterface.php
  src/Form/Extension/ChoiceTypeExtension.php
  src/Form/Extension/Field/Type/FormTypeFieldExtension.php
  src/Form/Extension/Field/Type/MopaCompatibilityTypeFieldExtension.php
  src/Form/FormMapper.php
  src/Form/Type/AclMatrixType.php
  src/Form/Type/AdminType.php
  src/Form/Type/ChoiceFieldMaskType.php
  src/Form/Type/CollectionType.php
  src/Form/Type/Filter/ChoiceType.php
  src/Form/Type/Filter/DateRangeType.php
  src/Form/Type/Filter/DateTimeRangeType.php
  src/Form/Type/Filter/DateTimeType.php
  src/Form/Type/Filter/DateType.php
  src/Form/Type/Filter/DefaultType.php
  src/Form/Type/Filter/FilterDataType.php
  src/Form/Type/Filter/NumberType.php
  src/Form/Type/ModelAutocompleteType.php
  src/Form/Type/ModelHiddenType.php
  src/Form/Type/ModelListType.php
  src/Form/Type/ModelReferenceType.php
  src/Form/Type/ModelType.php
  src/Form/Type/Operator/ContainsOperatorType.php
  src/Form/Type/Operator/DateOperatorType.php
  src/Form/Type/Operator/DateRangeOperatorType.php
  src/Form/Type/Operator/EqualOperatorType.php
  src/Form/Type/Operator/NumberOperatorType.php
  src/Form/Type/Operator/StringOperatorType.php
  src/Form/Type/TemplateType.php
  src/Manipulator/ServicesManipulator.php
  src/Menu/Provider/GroupMenuProvider.php
  src/Twig/Extension/GroupExtension.php
  src/Twig/GroupRuntime.php
  src/Util/FormBuilderIterator.php
  tests/Datagrid/DatagridMapperTest.php
  tests/Datagrid/DatagridTest.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
  tests/Fixtures/Form/MyCustomType.php
  tests/Form/DataTransformer/ModelToIdPropertyTransformerTest.php
  tests/Form/Extension/Field/Type/FormTypeFieldExtensionTest.php
  tests/Route/DefaultRouteGeneratorTest.php
  tests/Security/Handler/RoleSecurityHandlerTest.php
  tests/Util/ObjectAclManipulatorTest.php
Labels: pedantic

#8025 Improve error message for non existent admin declaration
  src/DependencyInjection/Compiler/AdminSearchCompilerPass.php
Labels: patch

#8027 Fix Rector
  rector.php
  tests/Util/TraversableToCollectionTest.php
Labels: pedantic

#8029 Drop doctrine/inflector for symfony/string
  composer.json
  src/Controller/CRUDController.php
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
Labels: pedantic

#8033 Use attributes on docs
  docs/cookbook/recipe_lock_protection.rst
  docs/cookbook/recipe_sonata_admin_without_user_bundle.rst
  docs/cookbook/recipe_sortable_listing.rst
  docs/getting_started/creating_an_admin.rst
Labels: docs
