Repository sonata-project/SonataAdminBundle, pull requests merged in 2023-11, with the labels that each got.

#8123 DevKit updates for 4.x branch
  .github/workflows/test.yaml
  src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
Labels: automerge, dev-kit

#8124 DevKit updates
  .github/workflows/test.yaml
Labels: automerge, dev-kit

#8125 Set twig globals after first admin instanciation
  src/Controller/CRUDController.php
  src/EventListener/AdminEventListener.php
  src/EventListener/ConfigureCRUDControllerListener.php
  src/Resources/config/event_listener.php
  tests/Controller/CRUDControllerTest.php
  tests/EventListener/AdminEventListenerTest.php
  tests/EventListener/ConfigureCRUDControllerListenerTest.php
Labels: patch

#8127 Add SF 7 support
  .github/workflows/test.yaml
  composer.json
  src/Filter/Model/FilterData.php
  src/Form/Type/Filter/DateTimeRangeType.php
  src/Form/Type/Filter/DateTimeType.php
  src/Route/RoutesCacheWarmUp.php
  src/Security/Handler/AclSecurityHandler.php
  src/Security/Handler/RoleSecurityHandler.php
  src/Util/TraversableToCollection.php
  tests/Filter/Model/FilterDataTest.php
  tests/Filter/Persister/SessionFilterPersisterTest.php
  tests/Form/AdminLayoutTest.php
  tests/Form/Type/Filter/DateTimeRangeTypeTest.php
  tests/Form/Widget/FormChoiceWidgetTest.php
  tests/Util/TraversableToCollectionTest.php
Labels: minor

#8129 DevKit updates for 4.x branch
  .github/workflows/test.yaml
Labels: automerge, dev-kit
