Repository sonata-project/SonataAdminBundle, pull requests merged in 2024-01, with the labels that each got.

#8151 Bump rector
  composer.json
Labels: pedantic

#8149 Fix possible null error in search
  src/Action/SearchAction.php
Labels: bug

#8155 DevKit updates for 4.x branch
  phpstan.neon.dist
Labels: automerge, dev-kit

#8156 DevKit updates for 4.x branch
  .github/workflows/documentation.yaml
  .github/workflows/frontend.yaml
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/symfony-lint.yaml
  .github/workflows/test.yaml
  Makefile
Labels: automerge, dev-kit

#8157 DevKit updates for 5.x branch
  .github/workflows/documentation.yaml
  .github/workflows/frontend.yaml
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/symfony-lint.yaml
  .github/workflows/test.yaml
  Makefile
Labels: automerge, dev-kit
