Repository sonata-project/SonataAdminBundle, pull requests merged in 2024-04, with the labels that each got.

#8167 DevKit updates for 5.x branch
  CONTRIBUTING.md
Labels: automerge, dev-kit

#8166 DevKit updates for 4.x branch
  .php-cs-fixer.dist.php
  CONTRIBUTING.md
  src/Action/SetObjectFieldValueAction.php
  tests/Form/AdminLayoutTest.php
  tests/Form/FormMapperTest.php
  tests/Twig/Extension/RenderElementExtensionTest.php
  tests/Twig/RenderElementRuntimeTest.php
Labels: automerge, dev-kit

#8171 Fix phpstan
  src/Admin/Pool.php
  src/Controller/CRUDController.php
Labels: pedantic

#8170 Introduce SearchHandlerInterface
  src/Block/AdminSearchBlockService.php
  src/Resources/config/core.php
  src/Search/SearchHandler.php
  src/Search/SearchHandlerInterface.php
Labels: minor

#8174 4.30.0
  CHANGELOG.md
Labels: pedantic
