Repository sonata-project/SonataAdminBundle, pull requests merged in 2024-12, with the labels that each got.

#8218 Fix for the styles on the page displaying differences in entity versions
  assets/scss/layout.scss
  src/Resources/public/app.css
Labels: patch

#8219 Support editable mode on FieldDescriptionInterface::TYPE_ENUM
  src/Action/SetObjectFieldValueAction.php
  src/Form/DataTransformer/BackedEnumTransformer.php
  src/Form/DataTransformerResolver.php
  src/Resources/views/CRUD/base_list_field.html.twig
  src/Resources/views/CRUD/list_enum.html.twig
  src/Twig/XEditableRuntime.php
  tests/Form/DataTransformer/BackedEnumTransformerTest.php
  tests/Twig/XEditableRuntimeTest.php
Labels: feature

#8223 DevKit updates for 4.x branch
  .github/workflows/test.yaml
  rector.php
Labels: automerge, dev-kit

#8224 DevKit updates for 5.x branch
  .github/workflows/test.yaml
  rector.php
Labels: automerge, dev-kit

#8226 DevKit updates for 4.x branch
  rector.php
Labels: automerge, dev-kit

#8225 Drop old versions of PHP and Symfony
  composer.json
  src/Command/GenerateObjectAclCommand.php
  src/EventListener/ConfigureCRUDControllerListener.php
  src/Maker/AdminMaker.php
  src/Util/AdminObjectAclData.php
  tests/EventListener/ConfigureCRUDControllerListenerTest.php
  tests/Fixtures/FieldDescription/FieldDescription.php
  tests/Menu/Provider/GroupMenuProviderTest.php
  tests/Twig/Extension/FakeTemplateRegistryExtension.php
Labels: pedantic

#8227 4.34.0
  CHANGELOG.md
Labels: pedantic

#8228 Remove outdated checks php 8.0 in tests
  tests/Form/DataTransformer/BackedEnumTransformerTest.php
  tests/Twig/Extension/RenderElementExtensionTest.php
  tests/Twig/RenderElementRuntimeTest.php
  tests/Twig/XEditableRuntimeTest.php
Labels: pedantic

#8229 DevKit updates for 4.x branch
  rector.php
Labels: automerge, dev-kit

#8233 DevKit updates for 4.x branch
  .eslintrc.js
Labels: automerge, dev-kit

#8234 DevKit updates for 5.x branch
  .eslintrc.js
Labels: automerge, dev-kit

#8231 Remove Admin.set_object_field_value
  assets/js/admin.js
  src/Resources/public/app.js
Labels: minor

#8230 Update filter js
  assets/js/admin.js
  assets/js/controllers/filter_controller.js
  assets/js/controllers/filter_list_controller.js
  assets/js/stimulus.js
  assets/js/utils.js
  assets/scss/styles.scss
  composer.json
  package-lock.json
  package.json
  src/Resources/public/app.css
  src/Resources/public/app.js
  src/Resources/views/CRUD/base_list.html.twig
  tests/App/AppKernel.php
Labels: minor

#8232 Remove jquery-form
  assets/js/app.js
  package-lock.json
  package.json
  src/Resources/public/app.js
Labels: minor
