Repository sonata-project/SonataAdminBundle, pull requests merged in 2025-06, with the labels that each got.

#8299 Update installation docs
  docs/getting_started/installation.rst
Labels: docs

#8300 Introduce assets version strategy
  src/Asset/LastModifiedVersionStrategy.php
  src/Resources/config/core.php
  src/Resources/views/standard_layout.html.twig
  tests/Asset/LastModifiedVersionStrategyTest.php
Labels: minor

#8305 Fix "The Request object has not been set" exception
  src/Admin/AbstractAdmin.php
Labels: patch
