Repository sonata-project/SonataAdminBundle, pull requests merged in 2025-05, with the labels that each got.

#8283 Use TaggedAdminInterface::ADMIN_TAG constant
  src/DependencyInjection/Compiler/AdminAddInitializeCallCompilerPass.php
  tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
  tests/DependencyInjection/Compiler/AdminAddInitializeCallCompilerPassTest.php
  tests/DependencyInjection/Compiler/AdminSearchCompilerPassTest.php
  tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php
Labels: pedantic

#8284 Bugfix: Overrides symfonys return value in `AclSecurityHandler::findObjectAcls`
  src/Security/Handler/AclSecurityHandler.php
Labels: pedantic

#8286 DevKit updates for 4.x branch
  phpstan.neon.dist
Labels: automerge, dev-kit

#8287 DevKit updates for 5.x branch
  phpstan.neon.dist
Labels: automerge, dev-kit

#8291 Remove ext-json requirement
  composer.json
Labels: patch

#8289 Validate list mode exists before setting it
  src/Controller/CRUDController.php
Labels: patch

#8293 4.36.2
  CHANGELOG.md
Labels: pedantic

#8295 Handle JSON.parse exception
  assets/js/core/config.js
  assets/js/core/translation.js
  src/Resources/public/app.js
Labels: patch

#8296 Replace readmore-js
  assets/js/admin.js
  assets/js/app.js
  assets/js/controllers/readmore_controller.js
  assets/scss/app.scss
  assets/scss/readmore.scss
  package-lock.json
  package.json
  src/Resources/public/app.css
  src/Resources/public/app.js
  src/Resources/views/CRUD/base_list_field.html.twig
  src/Resources/views/CRUD/base_show_field.html.twig
  tests/Twig/Extension/RenderElementExtensionTest.php
  tests/Twig/RenderElementRuntimeTest.php
Labels: minor
